[album]
album_id = "4f4ebd6b-1de1-472f-9d06-1c6cbb1b0ecc"
title = "アイドルマスター バースデーシリーズ Vol.2 如月千早 Gratitude"
artist = "如月千早（今井麻美）"
date = 2007-04-24
type = "normal"
catalog = "765PRO-0007"
tags = ["765ショップ"]

[[discs]]
catalog = "765PRO-0007"

[[discs.tracks]]
title = "開幕"
artist = "如月千早（今井麻美）、音無小鳥（滝田樹里）"
type = "drama"

[[discs.tracks]]
title = "オリビアを聴きながら"

[[discs.tracks]]
title = "幕間その1 ～苦悩～"
artist = "如月千早（今井麻美）、音無小鳥（滝田樹里）"
type = "drama"

[[discs.tracks]]
title = "空へ…"

[[discs.tracks]]
title = "幕間その2 ～問題発生！？～"
artist = "如月千早（今井麻美）、音無小鳥（滝田樹里）"
type = "drama"

[[discs.tracks]]
title = "Jupiter"

[[discs.tracks]]
title = "閉幕 ～感謝～"
artist = "如月千早（今井麻美）、音無小鳥（滝田樹里）"
type = "drama"

[[discs.tracks]]
title = "付随 ～如月千早の考察～"
artist = "如月千早（今井麻美）、音無小鳥（滝田樹里）"
type = "drama"

[[discs.tracks]]
title = "蛇"
artist = "如月千早（今井麻美）、音無小鳥（滝田樹里）"
type = "drama"

[[discs.tracks]]
title = "ふたりのもじぴったん"

[[discs.tracks]]
title = "足"
artist = "如月千早（今井麻美）、音無小鳥（滝田樹里）"
type = "drama"
