[album]
title = "アイドルマスター バースデーシリーズ Vol.7 秋月律子 Sound of Raindrops"
artist = "秋月律子（若林直美）、田辺（石井一貴）、如月千早（今井麻美）、菊地真（平田宏美）"
date = { year = 2007, month = 6 }
type = "drama"
catalog = "765PRO-0006"
tags = ["765ショップ"]

[[discs]]
catalog = "765PRO-0006"

[[discs.tracks]]
title = "SCENE 1 ～夢～"

[[discs.tracks]]
title = "SCENE 2 ～変～"

[[discs.tracks]]
title = "SCENE 3 ～倒～"

[[discs.tracks]]
title = "SCENE 4 ～嘘～"

[[discs.tracks]]
title = "SCENE 5 ～揺～"

[[discs.tracks]]
title = "SCENE 6 ～外～"

[[discs.tracks]]
title = "SCENE 7 ～急～"

[[discs.tracks]]
title = "SCENE 8 ～幻～"

[[discs.tracks]]
title = "SCENE 9 ～晴～"
