[album]
album_id = "4917ec75-a7c1-4c3e-ae62-1af233327288"
title = "THE IDOLM@STER MILLION LIVE! DIGITAL MUSIC PLAYER XDP-20 ML"
artist = "Various Artists"
date = "2019-09"
type = "normal"
catalog = "@ML-XDP-20"
tags = ["THE IDOLM@STER MILLION LIVE"]

[[discs]]
catalog = "@ML-XDP-20"

[[discs.tracks]]
title = "Princess Be Ambitious!! (6thLIVE TOUR 神戸公演 Ver.)"
artist = "中谷育（原嶋あかり）、七尾百合子（伊藤美来）、松田亜利沙（村川梨衣）、高山紗代子（駒形友梨）、横山奈緒（渡部優衣）、高坂海美（上田麗奈）、佐竹美奈子（大関英里）、福田のり子（浜崎奈々）、徳川まつり（諏訪彩花）、エミリー スチュアート（郁原ゆう）、春日未来（山崎はるか）、矢吹可奈（木戸衣吹）、田中琴葉（種田梨沙）"

[[discs.tracks]]
title = "FairyTaleじゃいられない (6thLIVE TOUR 福岡公演 Ver.)"
artist = "天空橋朋花（小岩井ことり）、所恵美（藤井ゆきよ）、二階堂千鶴（野村香菜子）、百瀬莉緒（山口立花子）、真壁瑞希（阿部里果）、白石紬（南早紀）、北沢志保（雨宮天）、ジュリア（愛美）、最上静香（田所あずさ）、ロコ（中村温姫）、舞浜歩（戸田めぐみ）、永吉昴（斉藤佑圭）、周防桃子（渡部恵子）"

[[discs.tracks]]
title = "Angelic Parade♪ (6thLIVE TOUR 仙台公演 Ver.)"
artist = "島原エレナ（角元明日香）、宮尾美也（桐谷蝶々）、桜守歌織（香里有佐）、豊川風花（末柄里恵）、北上麗花（平山笑美）、馬場このみ（高橋未奈美）、篠宮可憐（近藤唯）、野々原茜（小笠原早紀）、伊吹翼（Machico）、木下ひなた（田村奈央）、箱崎星梨花（麻倉もも）、大神環（稲川英里）、望月杏奈（夏川椎菜）"
