[album]
album_id = "275ba145-7a3a-4c20-8477-c23ab57d38ad"
title = "22⁄7 Character song CD: Moonlight"
artist = "立川絢香（宮瀬玲奈）"
date = 2020-08-19
type = "normal"
catalog = "ANZX-15230"

[[discs]]
catalog = "ANZX-15230"

[[discs.tracks]]
title = "Moonlight"
artist = "立川絢香（宮瀬玲奈）"

[[discs.tracks]]
title = "Moonlight -off vocal ver.-"
artist = "立川絢香（宮瀬玲奈）"
type = "instrumental"
