[album]
title = "22⁄7 Original Soundtrack"
artist = "中山真斗"
date = 2020-03-25
type = "absolute"
catalog = "ANZX-15222"

[[discs]]
catalog = "ANZX-15222"

[[discs.tracks]]
title = "はじめて嘘をついた"

[[discs.tracks]]
title = "嘘と炭酸水"

[[discs.tracks]]
title = "誰にだって雪は降る"

[[discs.tracks]]
title = "バナナトロピか"

[[discs.tracks]]
title = "Production G.I.P"

[[discs.tracks]]
title = "壁と指令"

[[discs.tracks]]
title = "夕凪"

[[discs.tracks]]
title = "一番やりたくないこと"

[[discs.tracks]]
title = "mi."

[[discs.tracks]]
title = "あなたたちは選ばれた"

[[discs.tracks]]
title = "めまいの真ん中"

[[discs.tracks]]
title = "おいかけっこ"

[[discs.tracks]]
title = "僕に光をくれたんだ"
artist = "目黒良子"

[[discs.tracks]]
title = "つま先がならんだ"

[[discs.tracks]]
title = "前髪のエチュード"

[[discs.tracks]]
title = "私がやりたいことなの"

[[discs.tracks]]
title = "ねえ壁ちゃん"

[[discs.tracks]]
title = "hnh."

[[discs.tracks]]
title = "約束は同じ名前"

[[discs.tracks]]
title = "Blanket"

[[discs.tracks]]
title = "ずぶ濡れの青春"

[[discs.tracks]]
title = "河野家の7人"

[[discs.tracks]]
title = "宇宙警察は泣かない"

[[discs.tracks]]
title = "お好み焼きのワルツ"

[[discs.tracks]]
title = "嗚呼、青春は不埒なり"

[[discs.tracks]]
title = "ゴリラトコニカ"

[[discs.tracks]]
title = "uni."

[[discs.tracks]]
title = "偶数と奇数のあいだ"

[[discs.tracks]]
title = "8+3=?"

[[discs.tracks]]
title = "きみと半分こ"

[[discs.tracks]]
title = "人生は遊園地"

[[discs.tracks]]
title = "秘密のおでこ"
artist = "長沢知亜紀、永野小織"

[[discs.tracks]]
title = "タイムカード・ピチカート"

[[discs.tracks]]
title = "アトリエ"

[[discs.tracks]]
title = "こんにちは、新しい世界"

[[discs.tracks]]
title = "Sister"

[[discs.tracks]]
title = "flw."

[[discs.tracks]]
title = "House of Sugar"

[[discs.tracks]]
title = "vve."

[[discs.tracks]]
title = "さよなら、私たちの世界"

[[discs.tracks]]
title = "1センチだけ開けておいて"
artist = "Yukito"

[[discs.tracks]]
title = "きっと大好きだった"

[[discs.tracks]]
title = "ただその背中を追い続けて"

[[discs.tracks]]
title = "もう雪は止んでいる"
