[album]
album_id = "5235d6c5-ff83-459a-80fa-e0a497089bb5"
title = "にこぷり♡女子道"
artist = "矢澤にこ（徳井青空）"
date = 2013-07-26
type = "normal"
catalog = "BCXA-0701"
tags = ["μ's"]

[[discs]]
catalog = "BCXA-0701"

[[discs.tracks]]
title = "にこぷり♡女子道"

[[discs.tracks]]
title = "にこぷり♡女子道 (Off Vocal)"
type = "instrumental"
