[album]
album_id = "3e362b13-4fc3-4cc1-a50f-c168865f419d"
title = "キズナミュージック♪"
artist = "Poppin'Party（戸山香澄（愛美）、花園たえ（大塚紗英）、牛込りみ（西本りみ）、山吹沙綾（大橋彩香）、市ヶ谷有咲（伊藤彩沙））"
date = 2018-12-12
type = "normal"
catalog = "BRMM-10140"

[[discs]]
catalog = "BRMM-10140"

[[discs.tracks]]
title = "キズナミュージック♪"

[[discs.tracks]]
title = "Home Street"

[[discs.tracks]]
title = "キズナミュージック♪ -instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "Home Street -instrumental-"
type = "instrumental"
