[album]
album_id = "fa81209f-1ea5-419c-a28d-e2604912d1ed"
title = "Daylight -デイライト-"
artist = "Morfonica（倉田ましろ（進藤あまね）、桐ヶ谷透子（直田姫奈）、広町七深（西尾夕香）、二葉つくし（mika）、八潮瑠唯（Ayasa））"
date = 2020-05-27
type = "normal"
catalog = "BRMM-10263"

[[discs]]
catalog = "BRMM-10263"

[[discs.tracks]]
title = "Daylight -デイライト-"

[[discs.tracks]]
title = "金色へのプレリュード"

[[discs.tracks]]
title = "Daylight -デイライト- -instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "金色へのプレリュード -instrumental-"
type = "instrumental"
