[album]
album_id = "2a746b3d-978a-4ad0-a02a-0363cc2bbf0d"
title = "BanG Dream! 3タイトル連動購入 特典CD"
artist = "Various Artists"
date = 2020-03-18
type = "drama"
catalog = "BRMM-10247"
tags = ["BanG Dream!"]

[[discs]]
catalog = "BRMM-10247"

[[discs.tracks]]
title = "羽沢珈琲店、ツグる！？"
artist = "Afterglow（美竹蘭（佐倉綾音）、青葉モカ（三澤紗千香）、上原ひまり（加藤英美里）、宇田川巴（日笠陽子）、羽沢つぐみ（金元寿子））"

[[discs.tracks]]
title = "理想のバケーションは…？"
artist = "Pastel＊Palettes（丸山彩（前島亜美）、氷川日菜（小澤亜李）、白鷺千聖（上坂すみれ）、大和麻弥（中上育実）、若宮イヴ（秦佐和子））"

[[discs.tracks]]
title = "こころ謹製☆スペシャルドリンク"
artist = "ハロー、ハッピーワールド！（弦巻こころ（伊藤美来）、瀬田薫（田所あずさ）、北沢はぐみ（吉田有里）、松原花音（豊田萌絵）、ミッシェル（奥沢美咲（黒沢ともよ）））"
