[album]
album_id = "9ba6a2a8-7819-4937-bc8b-41bc43288071"
title = "FIRE BIRD"
artist = "Roselia（湊友希那（相羽あいな）、氷川紗夜（工藤晴香）、今井リサ（中島由貴）、宇田川あこ（櫻川めぐ）、白金燐子（志崎樺音））"
date = 2019-07-24
type = "normal"
catalog = "BRMM-10194"

[[discs]]
catalog = "BRMM-10194"

[[discs.tracks]]
title = "FIRE BIRD"

[[discs.tracks]]
title = "Ringing Bloom"

[[discs.tracks]]
title = "FIRE BIRD -instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "Ringing Bloom -instrumental-"
type = "instrumental"
