[album]
album_id = "930cd945-50a6-4de1-8aae-7c888fc8bfbe"
title = "Regalia -継承-／アフレぐ！～Aufregendes leben～"
edition = "Blu-ray付生産限定盤"
artist = "シークフェルト音楽学院中等部（高千穂ステラ（青木陽菜）、大賀美詩呂（松澤可苑）、小鳩良子（深川瑠華）、海辺みんく（久家心）、森保クイナ（佐當友莉亜））"
date = 2022-10-12
type = "normal"
catalog = "BRMM-10570"
tags = ["シークフェルト音楽学院"]

[[discs]]
catalog = "BRMM-10570"

[[discs.tracks]]
title = "Regalia -継承-"

[[discs.tracks]]
title = "アフレぐ！～Aufregendes leben～"

[[discs.tracks]]
title = "Regalia -継承- -instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "アフレぐ！～Aufregendes leben～ -instrumental-"
type = "instrumental"
