[album]
album_id = "f886c757-31e1-4b3a-be56-6d55f6bdeb8a"
title = "キラキラだとか夢だとか ～Sing Girls～"
artist = "Poppin'Party（戸山香澄（愛美）、花園たえ（大塚紗英）、牛込りみ（西本りみ）、山吹沙綾（大橋彩香）、市ヶ谷有咲（伊藤彩沙））"
date = 2017-02-15
type = "normal"
catalog = "BRMM-10066"

[[discs]]
catalog = "BRMM-10066"

[[discs.tracks]]
title = "キラキラだとか夢だとか ～Sing Girls～"

[[discs.tracks]]
title = "Happy Happy Party!"

[[discs.tracks]]
title = "キラキラだとか夢だとか ～Sing Girls～ -instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "Happy Happy Party! -instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "バンドリ！ミニドラマ ～お昼休みの過ごし方～"
type = "drama"
