[album]
title = "THE IDOLM@STER 2「SMOKY THRILL」"
artist = "竜宮小町（水瀬伊織（釘宮理恵）、三浦あずさ（たかはし智秋）、双海亜美（下田麻美））"
date = 2011-02-09
type = "normal"
catalog = "COCC-16442"

[[discs]]
catalog = "COCC-16442"

[[discs.tracks]]
title = "SMOKY THRILL（M@STER VERSION）"

[[discs.tracks]]
title = "恋するミカタ"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "トーク01"
artist = "水瀬伊織（釘宮理恵）、三浦あずさ（たかはし智秋）、双海亜美（下田麻美）、秋月律子（若林直美）"
type = "drama"

[[discs.tracks]]
title = "友情出演「チクタク」"
artist = "星井美希（長谷川明子）、萩原雪歩（浅倉杏美）、高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "トーク02"
artist = "水瀬伊織（釘宮理恵）、三浦あずさ（たかはし智秋）、双海亜美（下田麻美）、秋月律子（若林直美）"
type = "drama"

[[discs.tracks]]
title = "SMOKY THRILL（M@STER VERSION）（オリジナル・カラオケ）"
type = "instrumental"

[[discs.tracks]]
title = "恋するミカタ（オリジナル・カラオケ）"
artist = "秋月律子（若林直美）"
type = "instrumental"
