[album]
album_id = "ba1b0927-25ac-4e46-84d9-0fa8844350d2"
title = "THE IDOLM@STER MASTER ARTIST 4 04 菊地真"
artist = "菊地真（平田宏美）"
date = 2020-11-11
type = "normal"
catalog = "COCX-41154"
tags = ["THE IDOLM@STER MASTER ARTIST 4"]

[[discs]]
catalog = "COCX-41154"

[[discs.tracks]]
title = "Ever Sunny"

[[discs.tracks]]
title = "トーク1"
type = "drama"

[[discs.tracks]]
title = "愛のうた"

[[discs.tracks]]
title = "ロマンティック 浮かれモード"

[[discs.tracks]]
title = "トーク2"
type = "drama"

[[discs.tracks]]
title = "マジで…！？"

[[discs.tracks]]
title = "トーク3"
type = "drama"

[[discs.tracks]]
title = "New Me, Continued"

[[discs.tracks]]
title = "トーク4"
type = "drama"

[[discs.tracks]]
title = "Ever Sunny オリジナル・カラオケ"
type = "instrumental"

[[discs.tracks]]
title = "連続ラジオ小説『765色のストーリー～第四話「王子様、現るっ！」～』"
type = "drama"
