[album]
title = "THE IDOLM@STER MASTERWORK 03"
artist = "菊地真（平田宏美）、三浦あずさ（たかはし智秋）、萩原雪歩（落合祐里香）、水瀬伊織（釘宮理恵）、高槻やよい（仁後真耶子）、双海亜美（下田麻美）、双海真美（下田麻美）"
date = 2007-03-28
type = "normal"
catalog = "COCX-34201"

[[discs]]
catalog = "COCX-34201"

[[discs.tracks]]
title = "まっすぐ（M@STER VERSION）"
artist = "菊地真（平田宏美）、三浦あずさ（たかはし智秋）、萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "私はアイドル♥（M@STER VERSION）"
artist = "水瀬伊織（釘宮理恵）、高槻やよい（仁後真耶子）、双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "First Stage（M@STER VERSION）"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "エージェント夜を往く（M@STER VERSION）"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "まっすぐ（M@STER VERSION）オリジナル・カラオケ"
artist = "菊地真（平田宏美）、三浦あずさ（たかはし智秋）、萩原雪歩（落合祐里香）"
type = "instrumental"

[[discs.tracks]]
title = "私はアイドル♥（M@STER VERSION）オリジナル・カラオケ"
artist = "水瀬伊織（釘宮理恵）、高槻やよい（仁後真耶子）、双海亜美（下田麻美）、双海真美（下田麻美）"
type = "instrumental"

[[discs.tracks]]
title = "ボーナス・トラック・トーク"
artist = "萩原雪歩（落合祐里香）、菊地真（平田宏美）、双海亜美（下田麻美）、双海真美（下田麻美）"
type = "drama"
