[album]
title = "THE IDOLM@STER MASTER LIVE 02 REM@STER-B"
artist = "如月千早（今井麻美）、水瀬伊織（釘宮理恵）、秋月律子（若林直美）、菊地真（平田宏美）、萩原雪歩（落合祐里香）、音無小鳥（滝田樹里）"
date = 2008-04-16
type = "normal"
catalog = "COCX-34770"

[[discs]]
catalog = "COCX-34770"

[[discs.tracks]]
title = "開演のあいさつ"
artist = "音無小鳥（滝田樹里）、水瀬伊織（釘宮理恵）"
type = "drama"

[[discs.tracks]]
title = "私はアイドル♥（REM@STER-B）"
artist = "如月千早（今井麻美）、音無小鳥（滝田樹里）、萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "First Stage（REM@STER-B）"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "太陽のジェラシー（REM@STER-B）"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "蒼い鳥（REM@STER-B）"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "エージェント夜を往く（REM@STER-B）"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "My Best Friend（REM@STER-B）"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "まっすぐ（REM@STER-B）"
artist = "音無小鳥（滝田樹里）"

[[discs.tracks]]
title = "THE IDOLM@STER（REM@STER-B）"
artist = "水瀬伊織（釘宮理恵）、菊地真（平田宏美）、秋月律子（若林直美）"

[[discs.tracks]]
title = "It's Show"

[[discs.tracks]]
title = "ボーナス・トラック・トーク"
type = "drama"
