[album]
title = "THE IDOLM@STER MASTER ARTIST 4 10 如月千早"
artist = "如月千早（今井麻美）"
date = 2021-06-16
type = "normal"
catalog = "COCX-41160"
tags = ["THE IDOLM@STER MASTER ARTIST 4"]

[[discs]]
catalog = "COCX-41160"

[[discs.tracks]]
title = "Coming Smile"

[[discs.tracks]]
title = "トーク1"
type = "drama"

[[discs.tracks]]
title = "歌う人"

[[discs.tracks]]
title = "ハロー"

[[discs.tracks]]
title = "トーク2"
type = "drama"

[[discs.tracks]]
title = "マジで…! ?"

[[discs.tracks]]
title = "トーク3"
type = "drama"

[[discs.tracks]]
title = "New Me, Continued"

[[discs.tracks]]
title = "トーク4"
type = "drama"

[[discs.tracks]]
title = "Coming Smile オリジナル・カラオケ"
type = "instrumental"

[[discs.tracks]]
title = "連続ラジオ小説『765色のストーリー ～第十話「小さく、かけがえのないもの」～』"
type = "drama"
