[album]
title = "THE IDOLM@STER MASTER ARTIST 2 -FIRST SEASON- 08"
artist = "双海真美（下田麻美）"
date = 2010-12-29
type = "normal"
catalog = "COCX-36517"

[[discs]]
catalog = "COCX-36517"

[[discs.tracks]]
title = "ジェミー"

[[discs.tracks]]
title = "トーク01 — 挨拶 —"
type = "drama"

[[discs.tracks]]
title = "黎明スターライン"

[[discs.tracks]]
title = "トーク02"
artist = "双海真美（下田麻美）、高槻やよい（仁後真耶子）、萩原雪歩（浅倉杏美）"
type = "drama"

[[discs.tracks]]
title = "夢の中へ"

[[discs.tracks]]
title = "トーク03"
artist = "双海真美（下田麻美）、高槻やよい（仁後真耶子）、萩原雪歩（浅倉杏美）"
type = "drama"

[[discs.tracks]]
title = "スウィートドーナッツ（Version Mami）"

[[discs.tracks]]
title = "トーク04"
artist = "双海真美（下田麻美）、高槻やよい（仁後真耶子）、萩原雪歩（浅倉杏美）"
type = "drama"

[[discs.tracks]]
title = "MEGARE!（M@STER VERSION）"

[[discs.tracks]]
title = "ジェミー（オリジナル・カラオケ）"
type = "instrumental"
