[album]
album_id = "45f69298-b5b0-4c87-9339-6ca39ccba344"
title = "THE IDOLM@STER DREAM SYMPHONY 02"
artist = "秋月涼（三瓶由布子）"
date = 2009-11-04
type = "normal"
catalog = "COCX-35794"

[[discs]]
catalog = "COCX-35794"

[[discs.tracks]]
title = "Dazzling World（M@STER VERSION）"

[[discs.tracks]]
title = "ヒミツの珊瑚礁"

[[discs.tracks]]
title = "エージェント夜を往く（M@STER VERSION）"

[[discs.tracks]]
title = "shiny smile（M@STER VERSION）"

[[discs.tracks]]
title = "“HELLO!!”（M@STER VERSION）"

[[discs.tracks]]
title = "Dazzling World（M@STER VERSION）オリジナル・カラオケ"
type = "instrumental"

[[discs.tracks]]
title = "ヒミツの珊瑚礁 オリジナル・カラオケ"
type = "instrumental"

[[discs.tracks]]
title = "ボーナス・トラック・ドラマ"
artist = "秋月涼（三瓶由布子）、水谷絵理（花澤香菜）、日高愛（戸松遥）"
type = "drama"
