[album]
album_id = "decef783-9603-49bb-ae43-f3a64b67efac"
title = "THE IDOLM@STER MASTER ARTIST 2 -FIRST SEASON- 03"
artist = "星井美希（長谷川明子）"
date = 2010-11-03
type = "normal"
catalog = "COCX-36512"

[[discs]]
catalog = "COCX-36512"

[[discs.tracks]]
title = "トーク01 ―挨拶―"
artist = "星井美希（長谷川明子）、天海春香（中村繪里子）、我那覇響（沼倉愛美）"
type = "drama"

[[discs.tracks]]
title = "Day of the future"

[[discs.tracks]]
title = "ふるふる☆フューチャー"

[[discs.tracks]]
title = "Squall"

[[discs.tracks]]
title = "トーク02"
artist = "星井美希（長谷川明子）、天海春香（中村繪里子）、我那覇響（沼倉愛美）"
type = "drama"

[[discs.tracks]]
title = "Tip Taps Tip（Version Miki）"

[[discs.tracks]]
title = "トーク03"
artist = "星井美希（長谷川明子）、天海春香（中村繪里子）、我那覇響（沼倉愛美）"
type = "drama"

[[discs.tracks]]
title = "MEGARE!（M@STER VERSION）"

[[discs.tracks]]
title = "トーク04"
type = "drama"

[[discs.tracks]]
title = "Day of the future（オリジナル・カラオケ）"
type = "instrumental"
