[album]
title = "THE IDOLM@STER MASTER ARTIST 4 12 水瀬伊織"
artist = "水瀬伊織（釘宮理恵）"
date = 2021-06-16
type = "normal"
catalog = "COCX-41162"
tags = ["THE IDOLM@STER MASTER ARTIST 4"]

[[discs]]
catalog = "COCX-41162"

[[discs.tracks]]
title = "ソナー"

[[discs.tracks]]
title = "トーク1"
type = "drama"

[[discs.tracks]]
title = "やさしい気持ち"

[[discs.tracks]]
title = "あたしを彼女にしたいなら"

[[discs.tracks]]
title = "トーク2"
type = "drama"

[[discs.tracks]]
title = "マジで…! ?"

[[discs.tracks]]
title = "トーク3"
type = "drama"

[[discs.tracks]]
title = "New Me, Continued"

[[discs.tracks]]
title = "トーク4"
type = "drama"

[[discs.tracks]]
title = "ソナー オリジナル・カラオケ"
type = "instrumental"

[[discs.tracks]]
title = "連続ラジオ小説『765色のストーリー ～第十二話「スターダム！」～』"
type = "drama"
