[album]
album_id = "b5721829-f0ae-4cfd-bc74-42256992da97"
title = "THE IDOLM@STER MASTER ARTIST 2 -FIRST SEASON- 02"
artist = "我那覇響（沼倉愛美）"
date = 2010-11-03
type = "normal"
catalog = "COCX-36511"

[[discs]]
catalog = "COCX-36511"

[[discs.tracks]]
title = "TRIAL DANCE"

[[discs.tracks]]
title = "トーク01 ―挨拶―"
type = "drama"

[[discs.tracks]]
title = "TRIAL DANCE（オリジナル・カラオケ）"
type = "instrumental"

[[discs.tracks]]
title = "トーク02"
type = "drama"

[[discs.tracks]]
title = "DREAM"

[[discs.tracks]]
title = "トーク03"
artist = "我那覇響（沼倉愛美）、星井美希（長谷川明子）、天海春香（中村繪里子）"
type = "drama"

[[discs.tracks]]
title = "Tip Taps Tip（Version Hibiki）"

[[discs.tracks]]
title = "トーク04"
artist = "我那覇響（沼倉愛美）、星井美希（長谷川明子）、天海春香（中村繪里子）"
type = "drama"

[[discs.tracks]]
title = "涙そうそう"

[[discs.tracks]]
title = "トーク05"
type = "drama"

[[discs.tracks]]
title = "MEGARE!（M@STER VERSION）"
