[album]
album_id = "cc471185-2ebb-4f38-9c1f-2999a7edaa23"
title = "THE IDOLM@STER MASTER ARTIST 4 02 四条貴音"
artist = "四条貴音（原由実）"
date = 2020-08-05
type = "normal"
catalog = "COCX-41152"
tags = ["THE IDOLM@STER MASTER ARTIST 4"]

[[discs]]
catalog = "COCX-41152"

[[discs.tracks]]
title = "炎ノ鳥"

[[discs.tracks]]
title = "トーク1"
type = "drama"

[[discs.tracks]]
title = "GLAMOROUS SKY"

[[discs.tracks]]
title = "焼け野が原"

[[discs.tracks]]
title = "トーク2"
type = "drama"

[[discs.tracks]]
title = "マジで…！？"

[[discs.tracks]]
title = "トーク3"
type = "drama"

[[discs.tracks]]
title = "New Me, Continued"

[[discs.tracks]]
title = "トーク4"
type = "drama"

[[discs.tracks]]
title = "炎ノ鳥 オリジナル・カラオケ"
type = "instrumental"

[[discs.tracks]]
title = "連続ラジオ小説『765色のストーリー～第二話「ひとり」～』"
type = "drama"
