[album]
album_id = "f7351c98-b054-480d-b266-ea418c8fcc03"
title = "No.6"
artist = "伊藤美来"
date = 2021-04-28
type = "normal"
catalog = "COZC-1743"

[[discs]]
catalog = "COZC-1743"

[[discs.tracks]]
title = "No.6"

[[discs.tracks]]
title = "気づかない?気づきたくない?"

[[discs.tracks]]
title = "No.6(off vocal ver.)"
type = "instrumental"

[[discs.tracks]]
title = "気づかない?気づきたくない?(off vocal ver.)"
type = "instrumental"
