[album]
title = "THE IDOLM@STER SP MASTER SPECIAL 765 Colorful Days"
artist = "天海春香（中村繪里子）、如月千早（今井麻美）、双海亜美（下田麻美）"
date = 2008-12-10
type = "normal"
catalog = "COZC-333"

[[discs]]
catalog = "COZC-333"

[[discs.tracks]]
title = "Colorful Days（M@STER VERSION）"

[[discs.tracks]]
title = "スキ"

[[discs.tracks]]
title = "サイレント ナイト"
artist = "天海春香（中村繪里子）、如月千早（今井麻美）、高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "Colorful Days（M@STER VERSION）オリジナル・カラオケ"
type = "instrumental"

[[discs.tracks]]
title = "スキ オリジナル・カラオケ"
type = "instrumental"
