[album]
album_id = "db1ea5c0-cb4e-4ada-8409-270cf69480b7"
title = "Sign／Candy Flavor"
artist = "内田彩"
date = 2019-03-06
type = "normal"
catalog = "COZC-1514"
tags = ["五等分の花嫁", "内田彩"]

[[discs]]
catalog = "COZC-1514"

[[discs.tracks]]
title = "Sign"

[[discs.tracks]]
title = "Candy Flavor"

[[discs.tracks]]
title = "Sign (Instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "Candy Flavor (Instrumental)"
type = "instrumental"
