[album]
album_id = "ffe85f26-7bbb-497f-b253-5cf73e62f1b6"
title = "「Polestar」華恋・まひる 歌い分けver.CD"
artist = "愛城華恋（小山百代）、露崎まひる（岩田陽葵）"
date = 2021-03-24
type = "normal"
catalog = "DSP-02289"

[[discs]]
catalog = "DSP-02289"

[[discs.tracks]]
title = "Polestar -華恋・まひる ver.-"
