[album]
album_id = "f0435578-ec5f-4bf3-8585-d6f6b8701044"
title = '少女☆歌劇 レヴュースタァライト 1stスタァライブ "Starry Sky" Live CD'
artist = "スタァライト九九組（愛城華恋（小山百代）、神楽ひかり（三森すずこ）、天堂真矢（富田麻帆）、星見純那（佐藤日向）、露崎まひる（岩田陽葵）、大場なな（小泉萌香）、西條クロディーヌ（相羽あいな）、石動双葉（生田輝）、花柳香子（伊藤彩沙））"
date = 2018-12-14
type = "normal"
catalog = "DSP-02186"

[[discs]]
catalog = "DSP-02186"

[[discs.tracks]]
title = "よろしく九九組 [Live]"

[[discs.tracks]]
title = "ディスカバリー！ [Live]"

[[discs.tracks]]
title = "ロマンティッククルージン [Live]"

[[discs.tracks]]
title = "Circle of the Revue [Live]"

[[discs.tracks]]
title = "Star Divine [Live]"

[[discs.tracks]]
title = "情熱の目覚めるとき [Live]"
artist = "星見純那（佐藤日向）、露崎まひる（岩田陽葵）、大場なな（小泉萌香）"

[[discs.tracks]]
title = "GANG☆STAR [Live]"
artist = "天堂真矢（富田麻帆）、西條クロディーヌ（相羽あいな）、石動双葉（生田輝）、花柳香子（伊藤彩沙）"

[[discs.tracks]]
title = "Fancy You [Live]"
artist = "愛城華恋（小山百代）、神楽ひかり（三森すずこ）"

[[discs.tracks]]
title = "星のダイアローグ [Live]"

[[discs.tracks]]
title = "願いは光になって [Live]"

[[discs.tracks]]
title = "キラめきのありか [Live]"

[[discs.tracks]]
title = "舞台少女心得 [Live]"

[[discs.tracks]]
title = "スタァライトシアター [Live]"

[[discs.tracks]]
title = "Glittering Stars -アンコール- [Live]"

[[discs.tracks]]
title = "Star Divine -アンコール- [Live]"
