[album]
album_id = "9f0c0ce9-e27f-44f3-8129-8f5778bdc0ae"
title = "ヤマノススメ オリジナル・サウンドトラック Vol.1"
artist = "Tom-H@ack、yamazo"
date = 2014-11-28
type = "absolute"
catalog = "EAAB-016CD"
tags = ["TVアニメ「ヤマノススメ セカンドシーズン」", "OST"]

[[discs]]
catalog = "EAAB-016CD"

[[discs.tracks]]
title = "メインテーマ・山に登るということ"
artist = "yamazo"

[[discs.tracks]]
title = "あおいのテーマ"
artist = "yamazo"

[[discs.tracks]]
title = "真夏の飯能"
artist = "yamazo"

[[discs.tracks]]
title = "ひなたと二人で"
artist = "yamazo"

[[discs.tracks]]
title = "あおい・じたばた"
artist = "yamazo"

[[discs.tracks]]
title = "自堕落な夏休み"
artist = "Tom-H@ck"

[[discs.tracks]]
title = "あどれなりん・はい"
artist = "yamazo"

[[discs.tracks]]
title = "不思議な体験"
artist = "yamazo"

[[discs.tracks]]
title = "十代の心"
artist = "Tom-H@ck"

[[discs.tracks]]
title = "てへぺろ"
artist = "yamazo"

[[discs.tracks]]
title = "ゆるふわ・ここな"
artist = "Tom-H@ck"

[[discs.tracks]]
title = "サスペンスかな？"
artist = "yamazo"

[[discs.tracks]]
title = "作戦会議"
artist = "yamazo"

[[discs.tracks]]
title = "岳人の歌"
artist = "Tom-H@ck"

[[discs.tracks]]
title = "高いの怖いの"
artist = "yamazo"

[[discs.tracks]]
title = "パンツ、見たな？"
artist = "yamazo"

[[discs.tracks]]
title = "ひたすら坂道"
artist = "Tom-H@ck"

[[discs.tracks]]
title = "明日も山がある"
artist = "yamazo"

[[discs.tracks]]
title = "あの山を目指すんだ"
artist = "yamazo"

[[discs.tracks]]
title = "そして、次の景色へ"
artist = "Tom-H@ck"

[[discs.tracks]]
title = "メインテーマ・ぬくもり"
artist = "yamazo"

[[discs.tracks]]
title = "ひつじが一匹"
artist = "yamazo"

[[discs.tracks]]
title = "人に頼るということ"
artist = "yamazo"

[[discs.tracks]]
title = "またひとり、友達ができました"
artist = "yamazo"

[[discs.tracks]]
title = "口笛吹いて行こう"
artist = "Tom-H@ck"

[[discs.tracks]]
title = "お母さんのダウンジャケット"
artist = "yamazo"

[[discs.tracks]]
title = "メインテーマ・思い出の山"
artist = "yamazo"

[[discs.tracks]]
title = "明日天気になあれ"
artist = "yamazo"

[[discs.tracks]]
title = "サブタイトル1"
artist = "yamazo"
