[album]
album_id = "c544c9b2-ab01-44f2-98b1-3042f9c02432"
title = "夏色プレゼント"
artist = "あおい（井口裕香）、ひなた（阿澄佳奈）、かえで（日笠陽子）、ここな（小倉唯）"
date = 2014-10-03
type = "normal"
catalog = "ESER-013"
tags = ["TVアニメ「ヤマノススメ セカンドシーズン」", "OP"]

[[discs]]
catalog = "ESER-013"

[[discs.tracks]]
title = "夏色プレゼント"

[[discs.tracks]]
title = "夏色プレゼント(あおいバージョン)"
artist = "あおい（井口裕香）"

[[discs.tracks]]
title = "夏色プレゼント(ひなたバージョン)"
artist = "ひなた（阿澄佳奈）"

[[discs.tracks]]
title = "夏色プレゼント(かえでバージョン)"
artist = "かえで（日笠陽子）"

[[discs.tracks]]
title = "夏色プレゼント(ここなバージョン)"
artist = "ここな（小倉唯）"

[[discs.tracks]]
title = "夏色プレゼント (Instrumental)"
artist = "Tom-H@ck"
type = "instrumental"
