[album]
album_id = "e6e75ab5-fc8e-4b5d-8728-be51e31a2e22"
title = "TVアニメ「ご注文はうさぎですか？」キャラクターソング④"
artist = "リゼ（種田梨沙）、シャロ（内田真礼）"
date = 2014-07-24
type = "normal"
catalog = "GNCA-0340"

[[discs]]
catalog = "GNCA-0340"

[[discs.tracks]]
title = "Eを探す日常"

[[discs.tracks]]
title = "夢見るアプレミディ"
artist = "リゼ（種田梨沙）"

[[discs.tracks]]
title = "麗しのShooting star"
artist = "シャロ（内田真礼）"

[[discs.tracks]]
title = "Eを探す日常 (Instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "夢見るアプレミディ (Instrumental)"
artist = "リゼ（種田梨沙）"
type = "instrumental"

[[discs.tracks]]
title = "麗しのShooting star (Instrumental)"
artist = "シャロ（内田真礼）"
type = "instrumental"
