[album]
album_id = "98bad9de-b433-483c-84fe-5d3c7e9a1233"
title = "なかよし！○！なかよし！"
artist = "チマメ隊"
date = 2020-10-28
type = "normal"
catalog = "GNCA-0622"

[[discs]]
catalog = "GNCA-0622"

[[discs.tracks]]
title = "なかよし！〇！なかよし！"

[[discs.tracks]]
title = "ワオワオ動物園"

[[discs.tracks]]
title = "なかよし！〇！なかよし！ ～チノVer.～"
artist = "チノ（水瀬いのり）"

[[discs.tracks]]
title = "なかよし！〇！なかよし！ ～マヤVer.～"
artist = "マヤ（徳井青空）"

[[discs.tracks]]
title = "なかよし！〇！なかよし！ ～メグVer.～"
artist = "メグ（村川梨衣）"

[[discs.tracks]]
title = "なかよし！〇！なかよし！(Instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "ワオワオ動物園 (Instrumental)"
type = "instrumental"
