[album]
album_id = "0d084087-0bc1-48a7-a7d4-fb553586d653"
title = "ごちうさDJブレンド2"
artist = "Various Artists"
date = 2018-12-19
type = "normal"
catalog = "GNCA-1550"

[[discs]]
catalog = "GNCA-1550-01"

[[discs.tracks]]
title = "「PandaBoY」DJ MIX"
artist = "PandaBoY"

[[discs]]
catalog = "GNCA-1550-02"

[[discs.tracks]]
title = "「DJ兎猛者」 DJ MIX"
artist = "DJ兎猛者"

[[discs.tracks]]
title = "ぷちょへんざ☆ゆにばーす"
artist = "マヤ（徳井青空）"
