[album]
album_id = "041e9a32-6527-4a0f-9747-ed25d75c1f90"
title = "order the songs"
artist = "Various Artists"
date = 2016-12-21
type = "normal"
catalog = "GNCA-1501"

[[discs]]
catalog = "GNCA-1501-01"

[[discs.tracks]]
title = "宝箱のジェットコースター"
artist = "Petit Rabbit's"

[[discs.tracks]]
title = "VSマイペース？"
artist = "振り回され隊"

[[discs.tracks]]
title = "色葉おしながき"
artist = "千夜（佐藤聡美）"

[[discs.tracks]]
title = "スマイルメーカー"
artist = "ココア（佐倉綾音）"

[[discs.tracks]]
title = "Love & Gun"
artist = "リゼ（種田梨沙）"

[[discs.tracks]]
title = "カフェインファイター"
artist = "シャロ（内田真礼）"

[[discs.tracks]]
title = "a cup of happiness"
artist = "チノ（水瀬いのり）"

[[discs.tracks]]
title = "ナマイキTiny Heart"
artist = "マヤ（徳井青空）"

[[discs.tracks]]
title = "ナイショのはなしは夢の中で"
artist = "メグ（村川梨衣）"

[[discs.tracks]]
title = "ずっと一緒"
artist = "千夜（佐藤聡美）、シャロ（内田真礼）"

[[discs.tracks]]
title = "Eを探す日常"
artist = "リゼ（種田梨沙）、シャロ（内田真礼）"

[[discs.tracks]]
title = "Rabbit Hole"
artist = "ココア（佐倉綾音）、リゼ（種田梨沙）"

[[discs.tracks]]
title = "きらきらエブリディ"
artist = "チマメ隊"

[[discs.tracks]]
title = "ぽっぴんジャンプ♪"
artist = "チマメ隊"

[[discs]]
catalog = "GNCA-1501-02"

[[discs.tracks]]
title = "ぴょん'sぷりんぷるん"
artist = "チマメ隊"

[[discs.tracks]]
title = "ハートぷるぷる事件です"
artist = "振り回され隊"

[[discs.tracks]]
title = "月夜にお砂糖星"
artist = "千夜（佐藤聡美）"

[[discs.tracks]]
title = "チョコリズムチョコルール"
artist = "ココア（佐倉綾音）"

[[discs.tracks]]
title = "ミカヅキドロップ"
artist = "リゼ（種田梨沙）"

[[discs.tracks]]
title = "麗しのShooting star"
artist = "シャロ（内田真礼）"

[[discs.tracks]]
title = "魔法少女チノ"
artist = "チノ（水瀬いのり）"

[[discs.tracks]]
title = "Theme of Phantom Thief Lapin"
artist = "川田瑠夏"
type = "absolute"

[[discs.tracks]]
title = "怪盗ラパン －The Phantom Thief Lapin－"
artist = "シャロ（内田真礼）"

[[discs.tracks]]
title = "うさぎになったバリスタ"
artist = "青山ブルーマウンテン（早見沙織）"

[[discs.tracks]]
title = "出かけましょうと答えましょう"
artist = "チノ（水瀬いのり）"

[[discs.tracks]]
title = "全天候型いらっしゃいませ"
artist = "ココア（佐倉綾音）、チノ（水瀬いのり）"

[[discs.tracks]]
title = "一匙のお姫さま物語"
artist = "Petit Rabbit's"

[[discs.tracks]]
title = "Daydream café"
artist = "Petit Rabbit's"
