[album]
album_id = "f78e3747-3d96-41ec-8159-9f881d7f0339"
title = "ぽっぴんジャンプ♪"
artist = "チマメ隊"
date = 2014-05-28
type = "normal"
catalog = "GNCA-0335"

[[discs]]
catalog = "GNCA-0335"

[[discs.tracks]]
title = "ぽっぴんジャンプ♪"

[[discs.tracks]]
title = "ぽっぴんジャンプ♪ ～チノ～ ソロVer."
artist = "チノ（水瀬いのり）"

[[discs.tracks]]
title = "ぽっぴんジャンプ♪ ～マヤ～ ソロVer."
artist = "マヤ（徳井青空）"

[[discs.tracks]]
title = "ぽっぴんジャンプ♪ ～メグ～ ソロVer."
artist = "メグ（村川梨衣）"

[[discs.tracks]]
title = "ぽっぴんジャンプ♪ (Instrumental)"
type = "instrumental"
