[album]
album_id = "983a93cd-bc7f-47ec-9c1f-d8ec6612d556"
title = "ご注文はうさぎですか？？キャラクターソングシリーズ 04"
artist = "シャロ（内田真礼）"
date = 2016-09-28
type = "normal"
catalog = "GNCA-0454"

[[discs]]
catalog = "GNCA-0454"

[[discs.tracks]]
title = "夢・もしもしもしも？"

[[discs.tracks]]
title = "＠ぐ～るぐるわーるど＠"

[[discs.tracks]]
title = "WELCOME【う・さ！】シャロVer."

[[discs.tracks]]
title = "夢・もしもしもしも？ (Instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "＠ぐ～るぐるわーるど＠ (Instrumental)"
type = "instrumental"
