[album]
title = "ef - a tale of melodies. ORIGINAL SOUNDTRACK 2 ~felice~"
artist = "天門、柳英一朗"
date = 2009-02-27
type = "absolute"
catalog = "GNCA-1166"

[[discs]]
catalog = "GNCA-1166"

[[discs.tracks]]
title = "Selfish proposal"

[[discs.tracks]]
title = "ebullient future (English TV-EDIT ver.2)"
artist = "ELISA"
type = "normal"

[[discs.tracks]]
title = "New town, Old town"

[[discs.tracks]]
title = "Believes, or doubts"

[[discs.tracks]]
title = "Lights"

[[discs.tracks]]
title = "Sedition"

[[discs.tracks]]
title = "Dependence"

[[discs.tracks]]
title = "願いのカケラ (TV-EDIT ver.B)"
artist = "雨宮優子（中嶋裕美子）"
type = "normal"

[[discs.tracks]]
title = "Collapsing feelings"

[[discs.tracks]]
title = "It returns to the dark"

[[discs.tracks]]
title = "Bluffs regret"

[[discs.tracks]]
title = "W all of ice"

[[discs.tracks]]
title = "Fragility and scary"

[[discs.tracks]]
title = "Hand of light"

[[discs.tracks]]
title = "Nonchalant happiness"

[[discs.tracks]]
title = "The wished world"

[[discs.tracks]]
title = "The past and the future"

[[discs.tracks]]
title = "Angel's stairs IE mix."

[[discs.tracks]]
title = "ebullient future (Piano Ver.)"

[[discs.tracks]]
title = "It starts here"

[[discs.tracks]]
title = "First step that realizes dream"

[[discs.tracks]]
title = "Painful notification"

[[discs.tracks]]
title = "Two courages"

[[discs.tracks]]
title = "The smile is bet"

[[discs.tracks]]
title = "笑顔のカケラ (TV-EDIT ver.B)"
artist = "羽山ミズキ（後藤麻衣）"
type = "normal"

[[discs.tracks]]
title = "Uneasy time"

[[discs.tracks]]
title = "Two are brought together"

[[discs.tracks]]
title = "A moon filled sky"
artist = "羽山ミズキ（後藤麻衣）"
type = "normal"

[[discs.tracks]]
title = "In front of the grave"

[[discs.tracks]]
title = "W atches it from the sky"

[[discs.tracks]]
title = "The place promised"

[[discs.tracks]]
title = "Two becomes one"

[[discs.tracks]]
title = "It through all eternity"

[[discs.tracks]]
title = "ebullient future (Japanese TV-EDIT)"

[[discs.tracks]]
title = "ever forever OG mix."
artist = "羽山ミズキ（後藤麻衣）、雨宮優子（中嶋裕美子）、宮村みやこ（田口宏子）、新藤景（岡田純子）、‎新藤千尋（やなせなつみ）"
type = "normal"
