[album]
title = "ef - a tale of memories. ORIGINAL SOUNDTRACK ~espressivo~"
artist = "天門、柳英一朗"
date = 2008-02-08
type = "absolute"
catalog = "GNCA-1135"

[[discs]]
catalog = "GNCA-1135"

[[discs.tracks]]
title = "Less than 45sec."

[[discs.tracks]]
title = "Holy day"

[[discs.tracks]]
title = "Church's bell"

[[discs.tracks]]
title = "Meets girl"

[[discs.tracks]]
title = "Snowly star"

[[discs.tracks]]
title = "A sheep as for a lamb"

[[discs.tracks]]
title = "I'm here (TV-EDIT cho.1)"
artist = "‎宮村みやこ（田口宏子）"
type = "normal"

[[discs.tracks]]
title = "Single line"

[[discs.tracks]]
title = "Unattended Station"

[[discs.tracks]]
title = "Handing over"

[[discs.tracks]]
title = "Stay with..."

[[discs.tracks]]
title = "Euphoric night"

[[discs.tracks]]
title = "刻む季節 (TV-EDIT cho.1)"
artist = "新藤景（岡田純子）"
type = "normal"

[[discs.tracks]]
title = "Every morning"

[[discs.tracks]]
title = "A moon filled sky ARmix"

[[discs.tracks]]
title = "Free and easy ARmix"

[[discs.tracks]]
title = "Promise"

[[discs.tracks]]
title = "Secret story"

[[discs.tracks]]
title = "The diary"

[[discs.tracks]]
title = "Sorrowful feather C2Rmix"

[[discs.tracks]]
title = "Impulsive step"

[[discs.tracks]]
title = "空の夢 (TV-EDIT cho.1)"
artist = "‎新藤千尋（やなせなつみ）"
type = "normal"

[[discs.tracks]]
title = "Junior girl ARmix"

[[discs.tracks]]
title = "Shiny walking"

[[discs.tracks]]
title = "Deep thinking"

[[discs.tracks]]
title = "Unexpected"

[[discs.tracks]]
title = "Early days"

[[discs.tracks]]
title = "Bad friend ARmix"

[[discs.tracks]]
title = "Mistake"

[[discs.tracks]]
title = "Early Childfood ARmix"

[[discs.tracks]]
title = "euphoric field (English TV-EDIT cho.1)"
artist = "ELISA"
type = "normal"
