[album]
album_id = "3b052e16-9ede-49de-bb9e-916643bc6cfd"
title = "ご注文はうさぎですか？BLOOM ORIGINAL SOUNDTRACK"
artist = "川田瑠夏"
date = 2020-12-25
type = "absolute"
catalog = "GNCA-1599"

[[discs]]
catalog = "GNCA-1599"

[[discs.tracks]]
title = "いつものRabbit Houseです♪"

[[discs.tracks]]
title = "うぇるかむかもーん!"

[[discs.tracks]]
title = "今日ものんびり"

[[discs.tracks]]
title = "賑やかフェスティバル"

[[discs.tracks]]
title = "良い感じだね～"

[[discs.tracks]]
title = "青山先生はここですかー!?"

[[discs.tracks]]
title = "はじまりのショータイム"

[[discs.tracks]]
title = "天空カフェテリア ～solo piano ver.～"

[[discs.tracks]]
title = "今日もお疲れ様♪"

[[discs.tracks]]
title = "いつもそばに"

[[discs.tracks]]
title = "夢色のじかん"

[[discs.tracks]]
title = "10年後の私達"

[[discs.tracks]]
title = "きらめきの魔法"

[[discs.tracks]]
title = "木組みの街のハロウィーン"

[[discs.tracks]]
title = "トリックオアトリート!～ようこそ魔女の館へ～"

[[discs.tracks]]
title = "千夜のおばあちゃん"

[[discs.tracks]]
title = "おしとやかにごきげんよう"

[[discs.tracks]]
title = "捜索中…!"

[[discs.tracks]]
title = "たすけてぇ～～"

[[discs.tracks]]
title = "ヒュ～～～ドロドロドロ"

[[discs.tracks]]
title = "やめてぇぇ～～～!!!"

[[discs.tracks]]
title = "まちなさーい！"

[[discs.tracks]]
title = "なかよし！〇！なかよし！～solo piano ver.～"

[[discs.tracks]]
title = "決戦の火蓋"

[[discs.tracks]]
title = "悶々と"

[[discs.tracks]]
title = "先輩は私が守るっ!!"

[[discs.tracks]]
title = "今日だけお嬢様"

[[discs.tracks]]
title = "覚悟はいいかっ!?"

[[discs.tracks]]
title = "怪盗ラパン参上!"

[[discs.tracks]]
title = "ウサギ警部の過去"

[[discs.tracks]]
title = "木組みの街のX'mas"

[[discs.tracks]]
title = "ほんわかクリスマス"

[[discs.tracks]]
title = "木組みの街に降る雪"

[[discs.tracks]]
title = "みんなでいっしょに!!"

[[discs.tracks]]
title = "優しさのお返し"
