[album]
album_id = "cda9831f-b8b9-47b6-b1c3-2dac411e7495"
title = "ゼンゼントモダチ"
artist = "山崎はるか"
date = 2018-05-23
type = "normal"
catalog = "GNCA-0528"

[[discs]]
catalog = "GNCA-0528"

[[discs.tracks]]
title = "ゼンゼントモダチ"

[[discs.tracks]]
title = "金曜日のBambi"

[[discs.tracks]]
title = "ゼンゼントモダチ＜instrumental＞"
type = "instrumental"

[[discs.tracks]]
title = "金曜日のBambi＜instrumental＞"
type = "instrumental"

[[discs.tracks]]
title = "選手宣誓ガール"
