[album]
album_id = "9d4ec744-a3a8-47c7-880f-4550f74a9aa0"
title = "ご注文はうさぎですか？？キャラクターソングシリーズ 01"
artist = "ココア（佐倉綾音）"
date = 2016-08-27
type = "normal"
catalog = "GNCA-0451"

[[discs]]
catalog = "GNCA-0451"

[[discs.tracks]]
title = "きらきら印を見つけたら"

[[discs.tracks]]
title = "ショコラティーヌ de 3時"

[[discs.tracks]]
title = "WELCOME【う・さ！】ココアVer."

[[discs.tracks]]
title = "きらきら印を見つけたら (Instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "ショコラティーヌ de 3時 (Instrumental)"
type = "instrumental"
