[album]
title = "ef - a tale of melodies. ORIGINAL SOUNDTRACK ~elegia~"
artist = "天門、柳英一朗"
date = 2008-12-26
type = "absolute"
catalog = "GNCA-1165"

[[discs]]
catalog = "GNCA-1165"

[[discs.tracks]]
title = "Overture"

[[discs.tracks]]
title = "ebullient future (English TV-EDIT ver.1)"
artist = "ELISA"
type = "normal"

[[discs.tracks]]
title = "A moon filled sky"

[[discs.tracks]]
title = "The other side of mask"

[[discs.tracks]]
title = "Dissembles"

[[discs.tracks]]
title = "Separate way"

[[discs.tracks]]
title = "Answer of asking oneself"

[[discs.tracks]]
title = "Embarrassed"

[[discs.tracks]]
title = "Still alive"

[[discs.tracks]]
title = "Scary"

[[discs.tracks]]
title = "Determined herself"

[[discs.tracks]]
title = "Because, he is here."

[[discs.tracks]]
title = "Who's problem"

[[discs.tracks]]
title = "Abnormal smile"

[[discs.tracks]]
title = "Twins, separate place"

[[discs.tracks]]
title = "Two standpoints"

[[discs.tracks]]
title = "Evening calm"

[[discs.tracks]]
title = "Confession"

[[discs.tracks]]
title = "A girl whom you deserted"

[[discs.tracks]]
title = "願いのカケラ (TV-EDIT ver.A)"
artist = "雨宮優子（中嶋裕美子）"
type = "normal"

[[discs.tracks]]
title = "Entropy"

[[discs.tracks]]
title = "Small revenge"

[[discs.tracks]]
title = "Kill and come."

[[discs.tracks]]
title = "Why? Why? Why?"

[[discs.tracks]]
title = "笑顔のチカラ (TV-EDIT ver.A)"
artist = "羽山ミズキ（後藤麻衣）"
type = "normal"
