[album]
album_id = "3d6016ba-e1ed-4336-979d-9503578266b1"
title = "にっこりカフェの魔法使い"
artist = "Petit Rabbit's"
date = 2015-12-25
type = "normal"
catalog = "GNXA-1771"

[[discs]]
catalog = "GNXA-1771"

[[discs.tracks]]
title = "にっこりカフェの魔法使い"

[[discs.tracks]]
title = "にっこりカフェの魔法使い (Instrumental)"
type = "instrumental"
