[album]
album_id = "8fd5ede5-d08d-4fdc-82b2-4e7eddebbe01"
title = "ご注文はうさぎですか？？～Dear My Sister～ ORIGINAL SOUNDTRACK"
artist = "川田瑠夏"
date = 2018-05-30
type = "absolute"
catalog = "GNXA-1217-02"

[[discs]]
catalog = "GNXA-1217-02"

[[discs.tracks]]
title = "帰ってきたよ！"

[[discs.tracks]]
title = "おかえりココア"

[[discs.tracks]]
title = "声が小さい!!"

[[discs.tracks]]
title = "今日もいざ焼かん！"

[[discs.tracks]]
title = "2人でどこへでも"

[[discs.tracks]]
title = "ゆっくりおしゃべり"

[[discs.tracks]]
title = "大繁盛!!"

[[discs.tracks]]
title = "サプライズをどうぞ"

[[discs.tracks]]
title = "みんなうさぎにしちゃうよ！"

[[discs.tracks]]
title = "あたたかい場所"

[[discs.tracks]]
title = "木組みの街のフェスティバル"

[[discs.tracks]]
title = "もうひとつのおかえりなさい"

[[discs.tracks]]
title = "セカイがカフェになっちゃった！～solo piano ver.～"

[[discs.tracks]]
title = "ハピネスアンコール～solo guitar ver.～"
