[album]
album_id = "8a02bc48-e214-4be3-8f47-7ad1339a88f0"
title = "お手伝いのラララン添えはいかがですか？"
artist = "チマメ隊"
date = 2016-05-02
type = "normal"
catalog = "GNXA-1775"

[[discs]]
catalog = "GNXA-1775"

[[discs.tracks]]
title = "お手伝いのラララン添えはいかがですか？"

[[discs.tracks]]
title = "お手伝いのラララン添えはいかがですか？(Instrumental)"
type = "instrumental"
