[album]
album_id = "7a2a3155-d4ee-41da-b559-6af89b8f35f4"
title = "スキでスゴイになりたいな"
artist = "看板娘隊"
date = 2021-05-28
type = "normal"
catalog = "GNXA-1596"

[[discs]]
catalog = "GNXA-1596"

[[discs.tracks]]
title = "スキでスゴイになりたいな"

[[discs.tracks]]
title = "スキでスゴイになりたいな (Instrumental)"
type = "instrumental"
