[album]
album_id = "3301db4e-96ab-4968-a814-d6f4280e59eb"
title = "アイドルマスター ミリオンライブ! 2 オリジナルCD"
artist = "春日未来（山崎はるか）、最上静香（田所あずさ）、箱崎星梨花（麻倉もも）、望月杏奈（夏川椎菜）、馬場このみ（高橋未奈美）"
date = 2015-08-12
type = "drama"
catalog = "ISBN-9784091592132"
tags = ["THE IDOLM@STER MILLION LIVE! オリジナルCD"]

[[discs]]
catalog = "ISBN-9784091592132"

[[discs.tracks]]
title = "ドラマパート1"

[[discs.tracks]]
title = "ドラマパート2"

[[discs.tracks]]
title = "ビジョナリー"
artist = "箱崎星梨花（麻倉もも）、望月杏奈（夏川椎菜）"
type = "normal"

[[discs.tracks]]
title = "ドラマパート3"

[[discs.tracks]]
title = "キミはメロディ"
artist = "春日未来（山崎はるか）"
type = "normal"

[[discs.tracks]]
title = "ドラマパート4"
