[album]
title = "アイドルマスター ミリオンライブ! Blooming Clover 7 オリジナルCD"
artist = "Various Artists"
date = 2020-08-27
type = "normal"
catalog = "ISBN-9784049131376"
tags = ["THE IDOLM@STER MILLION LIVE! Blooming Clover オリジナルCD"]

[[discs]]
catalog = "ISBN-9784049131376"

[[discs.tracks]]
title = "Vertex Meister"
artist = "高坂海美（上田麗奈）、宮尾美也（桐谷蝶々）"

[[discs.tracks]]
title = "Just be myself!!"
artist = "百瀬莉緒（山口立花子）、桜守歌織（香里有佐）"

[[discs.tracks]]
title = "ボイスドラマ"
artist = "北沢志保（雨宮天）、最上静香（田所あずさ）、佐竹美奈子（大関英里）、大神環（稲川英里）"
type = "drama"
