[album]
album_id = "c09e23b0-4a75-4f35-a472-a8a7cdc86fe1"
title = "THE IDOLM@STER MILLION LIVE! THEATER DAYS Brand New Song 1巻 特典CD"
artist = "七尾百合子（伊藤美来）、白石紬（南早紀）"
date = 2018-10-31
type = "normal"
catalog = "ISBN-9784758016261"
tags = ["THE IDOLM@STER MILLION LIVE! THEATER DAYS Brand New Song"]

[[discs]]
catalog = "ISBN-9784758016261"

[[discs.tracks]]
title = "地球儀にない国 -Live Sound Mix-"
artist = "七尾百合子（伊藤美来）"

[[discs.tracks]]
title = "瑠璃色金魚と花菖蒲 -Live Sound Mix-"
artist = "白石紬（南早紀）"
