[album]
title = "アイドルマスター ミリオンライブ! 1 オリジナルCD"
artist = "春日未来（山崎はるか）、最上静香（田所あずさ）、伊吹翼（Machico）、横山奈緒（渡部優衣）、田中琴葉（種田梨沙）、島原エレナ（角元明日香）、永吉昴（斉藤佑圭）"
date = 2015-03-12
type = "drama"
catalog = "ISBN-9784091592033"
tags = ["THE IDOLM@STER MILLION LIVE! オリジナルCD"]

[[discs]]
catalog = "ISBN-9784091592033"

[[discs.tracks]]
title = "ドラマパート1"

[[discs.tracks]]
title = "ドラマパート2"

[[discs.tracks]]
title = "ドラマパート3"

[[discs.tracks]]
title = "蒼い鳥"
artist = "最上静香（田所あずさ）"
type = "normal"

[[discs.tracks]]
title = "ドラマパート4"

[[discs.tracks]]
title = "GO MY WAY!!"
artist = "春日未来（山崎はるか）、最上静香（田所あずさ）"
type = "normal"

[[discs.tracks]]
title = "ドラマパート5"
