[album]
album_id = "cba4ff0e-87ff-48ed-8449-ddc212d29b82"
title = "CHAOS;CHILD AUDIO DRAMA & RADIO DIGEST VOL.6"
artist = "Various Artists"
date = 2017-08-25
type = "radio"
catalog = "KAXA-7496CD"
tags = ["CHAOS;CHILD:アニメ"]

[[discs]]
catalog = "KAXA-7496CD"

[[discs.tracks]]
title = "サウンドドラマ「願い」(黒世莉架編) #1"
artist = "宮代拓留（松岡禎丞）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、香月華（仲谷明香）、伊藤真二（藤原祐規）、橘結衣（原由実）、山添うき（水瀬いのり）、有村雛絵（三森すずこ）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「願い」(黒世莉架編) #2"
artist = "宮代拓留（松岡禎丞）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、香月華（仲谷明香）、伊藤真二（藤原祐規）、橘結衣（原由実）、山添うき（水瀬いのり）、有村雛絵（三森すずこ）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「願い」(黒世莉架編) #3"
artist = "宮代拓留（松岡禎丞）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、香月華（仲谷明香）、伊藤真二（藤原祐規）、橘結衣（原由実）、山添うき（水瀬いのり）、有村雛絵（三森すずこ）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「願い」(黒世莉架編) #4"
artist = "宮代拓留（松岡禎丞）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、香月華（仲谷明香）、伊藤真二（藤原祐規）、橘結衣（原由実）、山添うき（水瀬いのり）、有村雛絵（三森すずこ）"
type = "drama"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第11回・第12回ダイジェスト> #1"
artist = "ブリドカットセーラ恵美、三森すずこ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第11回・第12回ダイジェスト> #2"
artist = "ブリドカットセーラ恵美、三森すずこ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第11回・第12回ダイジェスト> #3"
artist = "ブリドカットセーラ恵美、三森すずこ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第11回・第12回ダイジェスト> #4"
artist = "ブリドカットセーラ恵美、三森すずこ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第11回・第12回ダイジェスト> #5"
artist = "ブリドカットセーラ恵美、三森すずこ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第11回・第12回ダイジェスト> #6"
artist = "ブリドカットセーラ恵美、三森すずこ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第11回・第12回ダイジェスト> #7"
artist = "ブリドカットセーラ恵美、三森すずこ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第11回・第12回ダイジェスト> #8"
artist = "ブリドカットセーラ恵美、三森すずこ"
