[album]
album_id = "4bd5766b-2c77-45d2-bd64-4b0636667ffb"
title = "CHAOS;CHILD AUDIO DRAMA & RADIO DIGEST VOL.3"
artist = "Various Artists"
date = 2017-05-26
type = "radio"
catalog = "KAXA-7493CD"
tags = ["CHAOS;CHILD:アニメ"]

[[discs]]
catalog = "KAXA-7493CD"

[[discs.tracks]]
title = "サウンドドラマ「黒革じゃない手帖」(山添うき編) #1"
artist = "宮代拓留（松岡禎丞）、山添うき（水瀬いのり）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、香月華（仲谷明香）、伊藤真二（藤原祐規）、橘結衣（原由実）、橘結人（菊池こころ）、有村雛絵（三森すずこ）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「黒革じゃない手帖」(山添うき編) #2"
artist = "宮代拓留（松岡禎丞）、山添うき（水瀬いのり）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、香月華（仲谷明香）、伊藤真二（藤原祐規）、橘結衣（原由実）、橘結人（菊池こころ）、有村雛絵（三森すずこ）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「黒革じゃない手帖」(山添うき編) #3"
artist = "宮代拓留（松岡禎丞）、山添うき（水瀬いのり）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、香月華（仲谷明香）、伊藤真二（藤原祐規）、橘結衣（原由実）、橘結人（菊池こころ）、有村雛絵（三森すずこ）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「黒革じゃない手帖」(山添うき編) #4"
artist = "宮代拓留（松岡禎丞）、山添うき（水瀬いのり）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、香月華（仲谷明香）、伊藤真二（藤原祐規）、橘結衣（原由実）、橘結人（菊池こころ）、有村雛絵（三森すずこ）"
type = "drama"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #1"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #2"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #3"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #4"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #5"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #6"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #7"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #8"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #9"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #10"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #11"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #12"
artist = "ブリドカットセーラ恵美、上坂すみれ"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第5回・第6回ダイジェスト> #13"
artist = "ブリドカットセーラ恵美、上坂すみれ"
