[album]
title = "CHAOS;CHILD AUDIO DRAMA & RADIO DIGEST VOL.1"
artist = "Various Artists"
date = 2017-03-24
type = "radio"
catalog = "KAXA-7491CD"
tags = ["CHAOS;CHILD:アニメ"]

[[discs]]
catalog = "KAXA-7491CD"

[[discs.tracks]]
title = "サウンドドラマ「情報強者の、とある休日」(来栖乃々編) #1"
artist = "宮代拓留（松岡禎丞）、来栖乃々（ブリドカットセーラ恵美）、橘結衣（原由実）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「情報強者の、とある休日」(来栖乃々編) #2"
artist = "宮代拓留（松岡禎丞）、来栖乃々（ブリドカットセーラ恵美）、橘結衣（原由実）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「情報強者の、とある休日」(来栖乃々編) #3"
artist = "宮代拓留（松岡禎丞）、来栖乃々（ブリドカットセーラ恵美）、橘結衣（原由実）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「情報強者の、とある休日」(来栖乃々編) #4"
artist = "宮代拓留（松岡禎丞）、来栖乃々（ブリドカットセーラ恵美）、橘結衣（原由実）"
type = "drama"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #1"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #2"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #3"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #4"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #5"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #6"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #7"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #8"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #9"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #10"
artist = "ブリドカットセーラ恵美、松岡禎丞"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第1回・第2回ダイジェスト> #11"
artist = "ブリドカットセーラ恵美、松岡禎丞"
