[album]
title = "CHAOS;CHILD AUDIO DRAMA & RADIO DIGEST VOL.5"
artist = "Various Artists"
date = 2017-07-28
type = "radio"
catalog = "KAXA-7495CD"
tags = ["CHAOS;CHILD:アニメ"]

[[discs]]
catalog = "KAXA-7495CD"

[[discs.tracks]]
title = "サウンドドラマ「天使の贖罪」(久野里澪編) #1"
artist = "宮代拓留（松岡禎丞）、久野里澪（真田アサミ）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、有村雛絵（三森すずこ）、香月華（仲谷明香）、伊藤真二（藤原祐規）、百瀬克子（くじら）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「天使の贖罪」(久野里澪編) #2"
artist = "宮代拓留（松岡禎丞）、久野里澪（真田アサミ）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、有村雛絵（三森すずこ）、香月華（仲谷明香）、伊藤真二（藤原祐規）、百瀬克子（くじら）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「天使の贖罪」(久野里澪編) #3"
artist = "宮代拓留（松岡禎丞）、久野里澪（真田アサミ）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、有村雛絵（三森すずこ）、香月華（仲谷明香）、伊藤真二（藤原祐規）、百瀬克子（くじら）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「天使の贖罪」(久野里澪編) #4"
artist = "宮代拓留（松岡禎丞）、久野里澪（真田アサミ）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、有村雛絵（三森すずこ）、香月華（仲谷明香）、伊藤真二（藤原祐規）、百瀬克子（くじら）"
type = "drama"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #1"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #2"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #3"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #4"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #5"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #6"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #7"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #8"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #9"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #10"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第9回・第10回ダイジェスト> #11"
artist = "ブリドカットセーラ恵美、藤原祐規、原由実"
