[album]
title = "CHAOS;CHILD AUDIO DRAMA & RADIO DIGEST VOL.4"
artist = "Various Artists"
date = 2017-06-30
type = "radio"
catalog = "KAXA-7494CD"
tags = ["CHAOS;CHILD:アニメ"]

[[discs]]
catalog = "KAXA-7494CD"

[[discs.tracks]]
title = "サウンドドラマ「感染型超誇大妄想能力」(香月華編) #1"
artist = "宮代拓留（松岡禎丞）、香月華（仲谷明香）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、伊藤真二（藤原祐規）、有村雛絵（三森すずこ）、神成岳志（桐本琢也）、和久井修一（加藤将之）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「感染型超誇大妄想能力」(香月華編) #2"
artist = "宮代拓留（松岡禎丞）、香月華（仲谷明香）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、伊藤真二（藤原祐規）、有村雛絵（三森すずこ）、神成岳志（桐本琢也）、和久井修一（加藤将之）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「感染型超誇大妄想能力」(香月華編) #3"
artist = "宮代拓留（松岡禎丞）、香月華（仲谷明香）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、伊藤真二（藤原祐規）、有村雛絵（三森すずこ）、神成岳志（桐本琢也）、和久井修一（加藤将之）"
type = "drama"

[[discs.tracks]]
title = "サウンドドラマ「感染型超誇大妄想能力」(香月華編) #4"
artist = "宮代拓留（松岡禎丞）、香月華（仲谷明香）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、伊藤真二（藤原祐規）、有村雛絵（三森すずこ）、神成岳志（桐本琢也）、和久井修一（加藤将之）"
type = "drama"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #1"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #2"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #3"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #4"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #5"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #6"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #7"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #8"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #9"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #10"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #11"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #12"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #13"
artist = "ブリドカットセーラ恵、仲谷明香"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第7回・第8回ダイジェスト> #14"
artist = "ブリドカットセーラ恵、仲谷明香"
