[album]
album_id = "2a93f6f2-62ca-403c-bcc5-2204519a3df7"
title = "素晴らしき日々 サウンドトラックCD"
artist = "Various Artists"
date = 2010-05-03
type = "absolute"
catalog = "KEROQ-011-01"

[[discs]]
catalog = "KEROQ-011-01-01"

[[discs.tracks]]
title = "音に出来る事"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "夜の向日葵"
artist = "szak"

[[discs.tracks]]
title = "変わらないからこそ"
artist = "szak"

[[discs.tracks]]
title = "OMOSHIRO MUSIC"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "Happy Material"
artist = "szak"

[[discs.tracks]]
title = "夢見る魚 -Erik Satie-"
artist = "szak"

[[discs.tracks]]
title = "リビングゲーム"
artist = "ryo"

[[discs.tracks]]
title = "不安の立像"
artist = "ryo"

[[discs.tracks]]
title = "FURYOUミュージック"
artist = "ryo"

[[discs.tracks]]
title = "電波リレーの勝者"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "ピカデリー -Erik Satie-"
artist = "szak"

[[discs.tracks]]
title = "言葉と旋律"
artist = "ryo"

[[discs.tracks]]
title = "Les Enfants du Paradis"
artist = "szak"

[[discs.tracks]]
title = "beautiful everyday"
artist = "ryo"

[[discs.tracks]]
title = "邂逅"
artist = "ryo"

[[discs.tracks]]
title = "小さな旋律"
artist = "szak"

[[discs.tracks]]
title = "風の吹く丘"
artist = "ryo"

[[discs.tracks]]
title = "組曲の行方"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "ナグルファルの船上にて -Orgel Ver.-"
artist = "Pixelbee"

[[discs.tracks]]
title = "夏の大三角"
artist = "ryo"

[[discs]]
catalog = "KEROQ-011-01-02"

[[discs.tracks]]
title = "空気力学少女と少年の詩 -Orgel Ver.-"
artist = "szak"

[[discs.tracks]]
title = "平坦、そして美しき日常"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "見慣れた風景"
artist = "szak"

[[discs.tracks]]
title = "怪優奇優侏儒巨人美少女等募集"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "updowncity"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "電磁波ト世界の関係"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "主よ、人の望みの喜びよ"
artist = "ryo"

[[discs.tracks]]
title = "終ワリノ旋律"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "なぜ日は傾くのか"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "人よ、幸福に！"
artist = "ryo"

[[discs.tracks]]
title = "小さな記憶"
artist = "ryo"

[[discs.tracks]]
title = "同じ空はどこにも無い"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "窓と光"
artist = "szak"

[[discs.tracks]]
title = "黒い翼の舞"
artist = "szak"

[[discs.tracks]]
title = "少年とナイフ"
artist = "szak"

[[discs.tracks]]
title = "Tractatus Logico-philosophicus"
artist = "szak"

[[discs.tracks]]
title = "空気力学少女と少年の詩 -Piano Ver.-"
artist = "szak"

[[discs.tracks]]
title = "最果ての空"
artist = "H.B STUDIO"

[[discs.tracks]]
title = "KAROYAKAGirls"
artist = "H.B STUDIO"
