[album]
album_id = "0f52fe59-105b-400d-9a8b-ed9e61ecafc4"
title = "PHANTOM MINDS"
artist = "水樹奈々"
date = 2010-01-13
type = "normal"
catalog = "KICM-1299"

[[discs]]
catalog = "KICM-1299"

[[discs.tracks]]
title = "PHANTOM MINDS"

[[discs.tracks]]
title = "Don’t be long"

[[discs.tracks]]
title = "Song Communication"

[[discs.tracks]]
title = "十字架のスプレッド"
