[album]
album_id = "0f9bf75a-8341-4d7c-b59a-fc180855a0f9"
title = "SECRET AMBITION"
artist = "水樹奈々"
date = 2007-04-18
type = "normal"
catalog = "KICM-1199"

[[discs]]
catalog = "KICM-1199"

[[discs.tracks]]
title = "SECRET AMBITION"

[[discs.tracks]]
title = "Heart-shaped chant"

[[discs.tracks]]
title = "Level Hi！"

[[discs.tracks]]
title = "SECRET AMBITION（without nana）"
type = "instrumental"

[[discs.tracks]]
title = "Heart-shaped chant（without nana）"
type = "instrumental"

[[discs.tracks]]
title = "Level Hi！（without nana）"
type = "instrumental"
