[album]
album_id = "0c874118-3f7f-4450-953b-9b9453c11db2"
title = "POP MASTER"
artist = "水樹奈々"
date = 2011-04-13
type = "normal"
catalog = "KICM-1336"

[[discs]]
catalog = "KICM-1336"

[[discs.tracks]]
title = "POP MASTER"

[[discs.tracks]]
title = "UNBREAKABLE"
