[album]
album_id = "4d6fe5e9-8535-457b-b338-0eec8ef8aadd"
title = "BRIGHT STREAM"
artist = "水樹奈々"
date = 2012-08-01
type = "normal"
catalog = "KICM-1403"

[[discs]]
catalog = "KICM-1403"

[[discs.tracks]]
title = "BRIGHT STREAM"

[[discs.tracks]]
title = "FEARLESS HERO"

[[discs.tracks]]
title = "Sacred Force"
