[album]
album_id = "256094d3-1695-4623-a4a2-5370f3c02058"
title = "君のYELL"
artist = "ゆいかおり（小倉唯、石原夏織）"
date = 2012-03-14
type = "normal"
catalog = "KICM-91385"

[[discs]]
catalog = "KICM-91385"

[[discs.tracks]]
title = "君のYELL"

[[discs.tracks]]
title = "圧倒的な GO!!"

[[discs.tracks]]
title = "君のYELL (off vocal ver.)"
type = "instrumental"

[[discs.tracks]]
title = "圧倒的な GO!! (off vocal ver.)"
type = "instrumental"
