[album]
album_id = "fad0d308-f588-4bf5-b091-973b486ee87e"
title = "NEVER SURRENDER"
artist = "水樹奈々"
date = 2018-10-24
type = "normal"
catalog = "KICM-1889"

[[discs]]
catalog = "KICM-1889"

[[discs.tracks]]
title = "NEVER SURRENDER"

[[discs.tracks]]
title = "GET BACK"

[[discs.tracks]]
title = "サーチライト"

[[discs.tracks]]
title = "嘆きの華"
