[album]
album_id = "98a75b3e-8181-4516-a5c2-65511743eef6"
title = "パノラマ-Panorama-"
artist = "水樹奈々"
date = 2004-04-07
type = "normal"
catalog = "KICM-1100"

[[discs]]
catalog = "KICM-1100"

[[discs.tracks]]
title = "パノラマ-Panorama-"

[[discs.tracks]]
title = "cherish"

[[discs.tracks]]
title = "Heartbeat"

[[discs.tracks]]
title = "パノラマ-Panorama- (off vocal ver.)"
type = "instrumental"

[[discs.tracks]]
title = "cherish (off vocal ver.)"
type = "instrumental"

[[discs.tracks]]
title = "Heartbeat (off vocal ver.)"
type = "instrumental"
