[album]
album_id = "f3e9c693-57d9-4f7a-8153-f231b05b5a4b"
title = "深愛"
artist = "水樹奈々"
date = 2009-01-21
type = "normal"
catalog = "KICM-1270"

[[discs]]
catalog = "KICM-1270"

[[discs.tracks]]
title = "深愛"

[[discs.tracks]]
title = "PRIDE OF GLORY"

[[discs.tracks]]
title = "午前0時のBaby Doll"
