[album]
album_id = "37953965-bf96-4239-ae7e-d1a8ede4524f"
title = "Justice to Believe／アオイイロ"
artist = "水樹奈々"
date = 2006-11-15
type = "normal"
catalog = "KICM-1185"

[[discs]]
catalog = "KICM-1185"

[[discs.tracks]]
title = "Justice to Believe"

[[discs.tracks]]
title = "アオイイロ"

[[discs.tracks]]
title = "Justice to Believe（without NANA）"
type = "instrumental"

[[discs.tracks]]
title = "アオイイロ（without NANA）"
type = "instrumental"
