[album]
album_id = "51ea742e-3df0-4629-af07-57d556301282"
title = "still in the groove"
artist = "水樹奈々"
date = 2003-07-16
type = "normal"
catalog = "KICM-1075"

[[discs]]
catalog = "KICM-1075"

[[discs.tracks]]
title = "still in the groove"

[[discs.tracks]]
title = "refrain"

[[discs.tracks]]
title = "恋してる..."

[[discs.tracks]]
title = "still in the groove (off vocal version)"
type = "instrumental"

[[discs.tracks]]
title = "refrain (off vocal version)"
type = "instrumental"

[[discs.tracks]]
title = "恋してる... (off vocal version)"
type = "instrumental"
