[album]
album_id = "37a9ff01-943f-402b-89e2-67539613101e"
title = "MASSIVE WONDERS"
artist = "水樹奈々"
date = 2007-08-22
type = "normal"
catalog = "KICM-1211"

[[discs]]
catalog = "KICM-1211"

[[discs.tracks]]
title = "MASSIVE WONDERS"

[[discs.tracks]]
title = "Happy Dive"

[[discs.tracks]]
title = "Pray"

[[discs.tracks]]
title = "MASSIVE WONDERS（without NANA）"
type = "instrumental"

[[discs.tracks]]
title = "Happy Dive（without NANA）"
type = "instrumental"

[[discs.tracks]]
title = "Pray（without NANA）"
type = "instrumental"
