[album]
album_id = "9ff7beb1-3a37-4f5f-8eed-48d21a73efed"
title = "ETERNAL BLAZE"
artist = "水樹奈々"
date = 2005-10-19
type = "normal"
catalog = "KICM-1148"

[[discs]]
catalog = "KICM-1148"

[[discs.tracks]]
title = "ETERNAL BLAZE"

[[discs.tracks]]
title = "RUSH＆DASH!"

[[discs.tracks]]
title = "Inside of mind"
