[album]
album_id = "08c8e249-f3fa-4ebd-82b5-695b28b850cf"
title = "アイマイモコ"
artist = "水瀬いのり"
date = 2017-08-09
type = "normal"
catalog = "KICM-1783"

[[discs]]
catalog = "KICM-1783"

[[discs.tracks]]
title = "アイマイモコ"

[[discs.tracks]]
title = "リトルシューゲイザー"

[[discs.tracks]]
title = "夏夢"
