[album]
album_id = "bbc5b1d0-c1ab-4d0e-8b77-2e1d824c74cb"
title = "禁断のレジスタンス"
artist = "水樹奈々"
date = 2014-10-15
type = "normal"
catalog = "KICM-1542"

[[discs]]
catalog = "KICM-1542"

[[discs.tracks]]
title = "禁断のレジスタンス"

[[discs.tracks]]
title = "BLUE"

[[discs.tracks]]
title = "ドリームライダー"
