[album]
album_id = "52cd8a16-9f0e-4f69-b13a-18f67c86b8dd"
title = "suddenly ～巡り合えて～／Brilliant Star"
artist = "水樹奈々"
date = 2002-09-25
type = "normal"
catalog = "KICM-1057"

[[discs]]
catalog = "KICM-1057"

[[discs.tracks]]
title = "suddenly ～巡り合えて～"

[[discs.tracks]]
title = "Brilliant Star"

[[discs.tracks]]
title = "suddenly ～巡り合えて～（OFF VOCAL VERSION）"
type = "instrumental"

[[discs.tracks]]
title = "Brilliant Star（OFF VOCAL VERSION）"
type = "instrumental"
