[album]
album_id = "6d427dd6-b0f7-4d95-bdd2-8c9101979b19"
title = "STARTING NOW！"
artist = "水樹奈々"
date = 2016-07-13
type = "normal"
catalog = "KICM-1690"

[[discs]]
catalog = "KICM-1690"

[[discs.tracks]]
title = "STARTING NOW！"

[[discs.tracks]]
title = "アンティフォーナ"

[[discs.tracks]]
title = "恋想花火"
