[album]
album_id = "5fc484aa-b0e0-4a4c-839d-8a34d1adf853"
title = "ROCKBOUND NEIGHBORS"
artist = "水樹奈々"
date = 2012-12-12
type = "normal"
catalog = "KICS-91847"

[[discs]]
catalog = "KICS-91847"

[[discs.tracks]]
title = "アヴァロンの王冠"

[[discs.tracks]]
title = "Naked Soldier"

[[discs.tracks]]
title = "Get my drift？"

[[discs.tracks]]
title = "Lovely Fruit"

[[discs.tracks]]
title = "ダーリンプラスティック"

[[discs.tracks]]
title = "BRIGHT STREAM"

[[discs.tracks]]
title = "星屑シンフォニー"

[[discs.tracks]]
title = "LINKAGE"

[[discs.tracks]]
title = "STAR ROAD"

[[discs.tracks]]
title = "Synchrogazer -Aufwachen Form-"

[[discs.tracks]]
title = "Crescent Child"

[[discs.tracks]]
title = "奇跡のメロディア"

[[discs.tracks]]
title = "METRO BAROQUE"

[[discs.tracks]]
title = "Happy☆Go-Round!"

[[discs.tracks]]
title = "Sacred Force -Extended Mix-"

[[discs.tracks]]
title = "約束"
