[album]
album_id = "9b1bbd25-eb4e-4306-a03d-0dafae50db9f"
title = "IMPACT EXCITER"
artist = "水樹奈々"
date = 2010-07-07
type = "normal"
catalog = "KICS-1564"

[[discs]]
catalog = "KICS-1564"

[[discs.tracks]]
title = "TIME TO IMPACT EXCITER"

[[discs.tracks]]
title = "NEXT ARCADIA"

[[discs.tracks]]
title = "ミュステリオン"

[[discs.tracks]]
title = "Silent Bible"

[[discs.tracks]]
title = "Young Alive!"

[[discs.tracks]]
title = "SCOOP SCOPE"

[[discs.tracks]]
title = "DRAGONIA"

[[discs.tracks]]
title = "夢幻"

[[discs.tracks]]
title = "夏恋模様"

[[discs.tracks]]
title = "恋の抑止力 -type EXCITER-"

[[discs.tracks]]
title = "PHANTOM MINDS"

[[discs.tracks]]
title = "ストロボシネマ"

[[discs.tracks]]
title = "囚われのBabel"

[[discs.tracks]]
title = "アルビレオ"

[[discs.tracks]]
title = "Don't be long"

[[discs.tracks]]
title = "7月7日"
