[album]
album_id = "2757423e-c8ea-4c6d-b759-21efc8735731"
title = "SUPERNAL LIBERTY"
artist = "水樹奈々"
date = 2014-04-16
type = "normal"
catalog = "KICS-93036"

[[discs]]
catalog = "KICS-93036"

[[discs.tracks]]
title = "VIRGIN CODE"

[[discs.tracks]]
title = "GUILTY"

[[discs.tracks]]
title = "アパッショナート"

[[discs.tracks]]
title = "笑顔の行方"

[[discs.tracks]]
title = "アンティークナハトムジーク"

[[discs.tracks]]
title = "Fun Fun★People"

[[discs.tracks]]
title = "FATE"

[[discs.tracks]]
title = "Vitalization -Aufwachen Form-"

[[discs.tracks]]
title = "哀愁トワイライト"

[[discs.tracks]]
title = "セツナキャパシティー"

[[discs.tracks]]
title = "Ladyspiker"

[[discs.tracks]]
title = "Rock you baby！"

[[discs.tracks]]
title = "Million Ways=One Destination"

[[discs.tracks]]
title = "僕らの未来"

[[discs.tracks]]
title = "愛の星 -two hearts-"
