[album]
album_id = "3eb637be-8450-429a-aa81-0945cd0a98ba"
title = "ULTIMATE DIAMOND"
artist = "水樹奈々"
date = 2009-06-03
type = "normal"
catalog = "KICS-91470"

[[discs]]
catalog = "KICS-91470"

[[discs.tracks]]
title = "MARIA&JOKER"

[[discs.tracks]]
title = "悦楽カメリア"

[[discs.tracks]]
title = "PERFECT SMILE"

[[discs.tracks]]
title = "Trickster"

[[discs.tracks]]
title = "Mr.Bunny！"

[[discs.tracks]]
title = "沈黙の果実"

[[discs.tracks]]
title = "Brand New Tops"

[[discs.tracks]]
title = "少年"

[[discs.tracks]]
title = "Gimmick Game"

[[discs.tracks]]
title = "Dancing in the velvet moon"

[[discs.tracks]]
title = "ray of change"

[[discs.tracks]]
title = "深愛"

[[discs.tracks]]
title = "蒼き光の果て-ULTIMATE MODE-"

[[discs.tracks]]
title = "Astrogation"

[[discs.tracks]]
title = "夢の続き"
