[album]
album_id = "0a6ce3c6-8733-4f2b-a7c1-cc8c1795ccfc"
title = "Y＆K"
artist = "ゆいかおり（小倉唯、石原夏織）"
date = 2017-06-21
type = "normal"
catalog = "KIZC-395~6"

[[discs]]
catalog = "KIZC-395"

[[discs.tracks]]
title = "Our Steady Boy"

[[discs.tracks]]
title = "ふたり"

[[discs.tracks]]
title = "VIVIVID PARTY!"

[[discs.tracks]]
title = "HEARTBEATが止まらないっ！"

[[discs.tracks]]
title = "Shooting☆Smile"

[[discs.tracks]]
title = "君のYELL"

[[discs.tracks]]
title = "ウェィカッ!!"

[[discs.tracks]]
title = "Shiny Blue"

[[discs.tracks]]
title = "LUCKY DUCKY!!"

[[discs.tracks]]
title = "Intro Situation"

[[discs.tracks]]
title = "NEO SIGNALIFE"

[[discs.tracks]]
title = "Ring Ring Rainbow!!"

[[discs.tracks]]
title = "Promise You!!"

[[discs.tracks]]
title = "B Ambitious!"

[[discs]]
catalog = "KIZC-396"

[[discs.tracks]]
title = "恋のオーバーテイク"

[[discs.tracks]]
title = "PUPPY LOVE!!"

[[discs.tracks]]
title = "CUE the Future　～「Q」のテーマ～"

[[discs.tracks]]
title = "君が世界で世界は君で"

[[discs.tracks]]
title = "翼になるよ"

[[discs.tracks]]
title = "marble"

[[discs.tracks]]
title = "Jumpin’ Bunny Flash!!"

[[discs.tracks]]
title = "星降る夜のハッピーリンク"

[[discs.tracks]]
title = "恋するストール"

[[discs.tracks]]
title = "オリオンからのメッセージ"

[[discs.tracks]]
title = "Calling Calling"

[[discs.tracks]]
title = "倍速∞ラブストレート"

[[discs.tracks]]
title = "カナリア"

[[discs.tracks]]
title = "Rainy Day"

[[discs.tracks]]
title = "ハツコイメイズ *Sugar time ver."
artist = "小倉唯"

[[discs.tracks]]
title = "Shiny Blue *Right on! Dream ver."
artist = "石原夏織"
