[album]
album_id = "74352866-01cf-4f6a-a006-857cc5dbc4ed"
title = "TVアニメ「神様になった日」 Original Soundtrack"
artist = "Key Sounds Label"
date = 2021-03-24
type = "absolute"
catalog = "KSLA-0179~80"

[[discs]]
catalog = "KSLA-0179"
artist = "麻枝准"

[[discs.tracks]]
title = "君という神話 -short ver.-"
artist = "やなぎなぎ"
type = "normal"

[[discs.tracks]]
title = "Everyday"

[[discs.tracks]]
title = "Toy Soldiers"

[[discs.tracks]]
title = "神様降臨"

[[discs.tracks]]
title = "Heroines"

[[discs.tracks]]
title = "Creepy Biscuits"

[[discs.tracks]]
title = "Library"

[[discs.tracks]]
title = "Match make"

[[discs.tracks]]
title = "Confrontation"

[[discs.tracks]]
title = "トラブルメーカー"

[[discs.tracks]]
title = "God only knows"

[[discs.tracks]]
title = "Strategy"

[[discs.tracks]]
title = "Mystery"

[[discs.tracks]]
title = "Movement"

[[discs.tracks]]
title = "Adultism"

[[discs.tracks]]
title = "夏凪ぎ -uptempo ver.-"

[[discs.tracks]]
title = "Winner"

[[discs.tracks]]
title = "勝利目指して"

[[discs.tracks]]
title = "一日の始まり"

[[discs.tracks]]
title = "黄昏"

[[discs.tracks]]
title = "帰還"

[[discs.tracks]]
title = "イザナミサーン!"

[[discs.tracks]]
title = "消滅大陸"

[[discs.tracks]]
title = "唐突な達人"

[[discs.tracks]]
title = "君という神話 -piano ver.-"

[[discs.tracks]]
title = "Goodbye Seven Seas -piano ver.-"

[[discs.tracks]]
title = "夏凪ぎ -episode2 piano ver.-"

[[discs.tracks]]
title = "神様になった日 -instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "Goodbye Seven Seas -short ver.-"
artist = "やなぎなぎ"
type = "normal"

[[discs]]
catalog = "KSLA-0180"
artist = "麻枝准"

[[discs.tracks]]
title = "夏凪ぎ -episode 9 ver.-"
artist = "やなぎなぎ"
type = "normal"

[[discs.tracks]]
title = "天才ハッカー"

[[discs.tracks]]
title = "Brain War"

[[discs.tracks]]
title = "サイバーダイブ"

[[discs.tracks]]
title = "Agent"

[[discs.tracks]]
title = "焦燥"

[[discs.tracks]]
title = "Battle Start"

[[discs.tracks]]
title = "Tactics"

[[discs.tracks]]
title = "Black Curtain"

[[discs.tracks]]
title = "Anxious Feelings"

[[discs.tracks]]
title = "Passed Each Other"

[[discs.tracks]]
title = "宵闇の旋律"

[[discs.tracks]]
title = "禍"

[[discs.tracks]]
title = "Irritation"

[[discs.tracks]]
title = "Rain"

[[discs.tracks]]
title = "Tenhou"

[[discs.tracks]]
title = "ゼウスサーガフィールド"

[[discs.tracks]]
title = "ゼウスサーガバトル"

[[discs.tracks]]
title = "ゼウスサーガリザルト"

[[discs.tracks]]
title = "ゼウスサーガダンジョン"

[[discs.tracks]]
title = "ゼウスサーガイベント"

[[discs.tracks]]
title = "ゼウスサーガボスバトル"

[[discs.tracks]]
title = "ゼウスサーガゲームオーバー"

[[discs.tracks]]
title = "Karma -intro-"
artist = "ANANT-GARDE EYES"

[[discs.tracks]]
title = "Karma -interlude-"
artist = "ANANT-GARDE EYES"

[[discs.tracks]]
title = "Karma -climax-"
artist = "ANANT-GARDE EYES"

[[discs.tracks]]
title = "夏凪ぎ -piano ver.-"

[[discs.tracks]]
title = "君という神話 -music box ver.-"

[[discs.tracks]]
title = "僕らの恋心"

[[discs.tracks]]
title = "宝物になった日 -episode 5 ver.-"
artist = "やなぎなぎ"
type = "normal"
