[album]
album_id = "c5495739-5d98-4389-928d-c70660b6552e"
title = "Summer Pockets Original SoundTrack"
artist = "Key Sounds Label"
date = 2018-09-26
type = "absolute"
catalog = "KSLM-0149~51"

[[discs]]
catalog = "KSLM-0149"

[[discs.tracks]]
title = "アルカテイル (Game Size Ver)"
artist = "鈴木このみ"
type = "normal"

[[discs.tracks]]
title = "Summer Pockets"
artist = "水月陵"

[[discs.tracks]]
title = "Sea, You & Me"
artist = "麻枝准"

[[discs.tracks]]
title = "蝉声とともに"
artist = "水月陵"

[[discs.tracks]]
title = "夏休みの過ごし方"
artist = "折戸伸治"

[[discs.tracks]]
title = "坂の上の陽炎"
artist = "どんまる"

[[discs.tracks]]
title = "White Loneliness"
artist = "水月陵"

[[discs.tracks]]
title = "Other side Blue"
artist = "折戸伸治"

[[discs.tracks]]
title = "Adventure for Black"
artist = "折戸伸治"

[[discs.tracks]]
title = "Golden Hours"
artist = "竹下智博"

[[discs.tracks]]
title = "宿題は8月32日に"
artist = "どんまる"

[[discs.tracks]]
title = "日射しの暇"
artist = "どんまる"

[[discs.tracks]]
title = "振り返らなくてもヤツはいる"
artist = "折戸伸治"

[[discs.tracks]]
title = "ひと夏のたわむれ"
artist = "どんまる"

[[discs.tracks]]
title = "さま～あばんちゅ～る"
artist = "どんまる"

[[discs.tracks]]
title = "夏の子守歌"
artist = "折戸伸治"

[[discs.tracks]]
title = "Lasting Moment (Game Size Ver)"
artist = "鈴木このみ"
type = "normal"

[[discs]]
catalog = "KSLM-0150"

[[discs.tracks]]
title = "White with You"
artist = "水月陵"

[[discs.tracks]]
title = "木陰の憩"
artist = "水月陵"

[[discs.tracks]]
title = "手の平の向こうの太陽"
artist = "どんまる"

[[discs.tracks]]
title = "今だけは暑さを忘れ"
artist = "竹下智博"

[[discs.tracks]]
title = "虹の蝶"
artist = "折戸伸治"

[[discs.tracks]]
title = "影は色濃くて"
artist = "どんまる"

[[discs.tracks]]
title = "かの記憶、あの記憶"
artist = "折戸伸治"

[[discs.tracks]]
title = "眼差しの後ろ"
artist = "竹下智博"

[[discs.tracks]]
title = "夜迷い"
artist = "折戸伸治"

[[discs.tracks]]
title = "Deep Blue Blue"
artist = "折戸伸治"

[[discs.tracks]]
title = "二人の冒険"
artist = "どんまる"

[[discs.tracks]]
title = "髭猫団の冒険"
artist = "どんまる"

[[discs.tracks]]
title = "Wing of Glass"
artist = "竹下智博"

[[discs.tracks]]
title = "蝉時雨の隙間に…"
artist = "折戸伸治"

[[discs.tracks]]
title = "夏を刻んだ、波の音は…"
artist = "竹下智博"

[[discs.tracks]]
title = "紬の夏休み"
artist = "紬ヴェンダース（岩井映美里）"

[[discs.tracks]]
title = "夜は短く、空は遠くて…"
artist = "水月陵"

[[discs.tracks]]
title = "アルカテイル -recall-"
artist = "折戸伸治"

[[discs]]
catalog = "KSLM-0151"

[[discs.tracks]]
title = "Sea, You Next"
artist = "麻枝准"

[[discs.tracks]]
title = "Twinkle of Alcor"
artist = "どんまる"

[[discs.tracks]]
title = "Childish White"
artist = "折戸伸治"

[[discs.tracks]]
title = "時編み"
artist = "水月陵"

[[discs.tracks]]
title = "眩しさの中"
artist = "水月陵"

[[discs.tracks]]
title = "夜奏花"
artist = "YURiKA"
type = "normal"

[[discs.tracks]]
title = "Sea, Your Memory"
artist = "麻枝准"

[[discs.tracks]]
title = "羽のゆりかご"
artist = "水谷瑠奈"
type = "normal"

[[discs.tracks]]
title = "アルカテイル -story-"
artist = "折戸伸治"

[[discs.tracks]]
title = "ポケットをふくらませて"
artist = "rionos"
type = "normal"

[[discs.tracks]]
title = "アルカテイル"
artist = "鈴木このみ"
type = "normal"

[[discs.tracks]]
title = "Lasting Moment"
artist = "鈴木このみ"
type = "normal"

[[discs.tracks]]
title = "アルカテイル (Instrumental Game Size Ver)"
artist = "折戸伸治"
type = "instrumental"
