[album]
title = "TVアニメ『魔女の旅々』Original Sound Track"
artist = "AstroNoteS"
date = 2021-01-27
type = "absolute"
catalog = "LACA-9808~9"

[[discs]]
catalog = "LACA-9808"

[[discs.tracks]]
title = "魔女の旅々のメインテーマ"

[[discs.tracks]]
title = "インプレッシブ"
artist = "関野元規"

[[discs.tracks]]
title = "なぜ。。。"
artist = "関野元規"

[[discs.tracks]]
title = "奇妙"

[[discs.tracks]]
title = "緊張"
artist = "関野元規"

[[discs.tracks]]
title = "趣のある街"
artist = "谷島シュン"

[[discs.tracks]]
title = "サヤの事情"
artist = "関野元規"

[[discs.tracks]]
title = "恋の芽生"
artist = "関野元規"

[[discs.tracks]]
title = "愛憎"

[[discs.tracks]]
title = "新しい私"

[[discs.tracks]]
title = "魔法のレッスン"
artist = "谷島シュン"

[[discs.tracks]]
title = "イレイナの憂鬱"
artist = "谷島シュン"

[[discs.tracks]]
title = "母性"

[[discs.tracks]]
title = "似たもの同士"
artist = "谷島シュン"

[[discs.tracks]]
title = "衰亡"
artist = "関野元規"

[[discs.tracks]]
title = "違和感"

[[discs.tracks]]
title = "疑念"
artist = "関野元規"

[[discs.tracks]]
title = "謎"
artist = "関野元規"

[[discs.tracks]]
title = "幸せの記憶"
artist = "谷島シュン"

[[discs.tracks]]
title = "おとぎばなし"

[[discs]]
catalog = "LACA-9809"

[[discs.tracks]]
title = "異変"

[[discs.tracks]]
title = "発動"
artist = "谷島シュン"

[[discs.tracks]]
title = "作戦開始"
artist = "谷島シュン"

[[discs.tracks]]
title = "仄暗く漂う残酷な気配"

[[discs.tracks]]
title = "素敵な街"
artist = "谷島シュン"

[[discs.tracks]]
title = "大賑わい"
artist = "谷島シュン"

[[discs.tracks]]
title = "魔女の記憶"
artist = "谷島シュン"

[[discs.tracks]]
title = "ちゃっかりイレイナ"
artist = "谷島シュン"

[[discs.tracks]]
title = "自立の時"

[[discs.tracks]]
title = "知的な振る舞い"
artist = "関野元規"

[[discs.tracks]]
title = "サヤのテーマ"
artist = "関野元規"

[[discs.tracks]]
title = "汗ジト"
artist = "谷島シュン"

[[discs.tracks]]
title = "イレイナの不満"
artist = "関野元規"

[[discs.tracks]]
title = "空飛ぶ旅"

[[discs.tracks]]
title = "追いかけっこ"
artist = "関野元規"

[[discs.tracks]]
title = "不快"
artist = "関野元規"

[[discs.tracks]]
title = "焦燥"
artist = "関野元規"

[[discs.tracks]]
title = "おもいやり"
artist = "谷島シュン"

[[discs.tracks]]
title = "満足感"

[[discs.tracks]]
title = "リテラチュア（AnimeSize）"
artist = "上田麗奈"
type = "normal"

[[discs.tracks]]
title = "灰色のサーガ（AnimeSize）"
artist = "ChouCho"
type = "normal"
