[album]
album_id = "b0c31024-5df8-4f6c-8be9-af10fbc1c123"
title = "「花咲くいろは」オリジナルサウンドトラック『湯乃鷺メモリィズ』"
artist = "浜口史郎"
date = 2011-09-28
type = "absolute"
catalog = "LACA-9217~8"

[[discs]]
catalog = "LACA-9217"

[[discs.tracks]]
title = "始まりの音色"
artist = "浜口史郎"

[[discs.tracks]]
title = "微笑の空気"
artist = "浜口史郎"

[[discs.tracks]]
title = "微笑の空気～ふわりと～"
artist = "浜口史郎"

[[discs.tracks]]
title = "日常と平和の狭間で"
artist = "浜口史郎"

[[discs.tracks]]
title = "愉快の種"
artist = "浜口史郎"

[[discs.tracks]]
title = "夕焼けに溶け込む時間"
artist = "浜口史郎"

[[discs.tracks]]
title = "笑顔に至る時間"
artist = "浜口史郎"

[[discs.tracks]]
title = "綺麗な風が吹く"
artist = "浜口史郎"

[[discs.tracks]]
title = "余裕の心は油断の心"
artist = "浜口史郎"

[[discs.tracks]]
title = "そよ風になびく草のように"
artist = "浜口史郎"

[[discs.tracks]]
title = "前向きのココロ"
artist = "浜口史郎"

[[discs.tracks]]
title = "前向きのココロ～ちらりと～"
artist = "浜口史郎"

[[discs.tracks]]
title = "緩やかさは暖かさ"
artist = "浜口史郎"

[[discs.tracks]]
title = "優しい少女は引っ込み思案"
artist = "浜口史郎"

[[discs.tracks]]
title = "時を刻む場所"
artist = "浜口史郎"

[[discs.tracks]]
title = "ここがぼんぼり時"
artist = "浜口史郎"

[[discs.tracks]]
title = "空回るパッション"
artist = "浜口史郎"

[[discs.tracks]]
title = "熱意が動く時"
artist = "浜口史郎"

[[discs.tracks]]
title = "新しい存在感"
artist = "浜口史郎"

[[discs.tracks]]
title = "そんなことってあるんだ感"
artist = "浜口史郎"

[[discs.tracks]]
title = "迫る人、迫られる人"
artist = "浜口史郎"

[[discs.tracks]]
title = "この世には色んな人がいる"
artist = "浜口史郎"

[[discs.tracks]]
title = "陽気であれば大丈夫"
artist = "浜口史郎"

[[discs.tracks]]
title = "イラムカな時もある"
artist = "浜口史郎"

[[discs.tracks]]
title = "空気読まんかい"
artist = "浜口史郎"

[[discs.tracks]]
title = "気持ちのスピードがちょっと遅い時"
artist = "浜口史郎"

[[discs.tracks]]
title = "弱くなった気持ち"
artist = "浜口史郎"

[[discs.tracks]]
title = "縛りのキツさよ"
artist = "浜口史郎"

[[discs.tracks]]
title = "徐々にそして段々と"
artist = "浜口史郎"

[[discs.tracks]]
title = "花いろ軍の行進"
artist = "浜口史郎"

[[discs.tracks]]
title = "戦いの後には感動がある"
artist = "浜口史郎"

[[discs.tracks]]
title = "懸命なる戦略会議"
artist = "浜口史郎"

[[discs.tracks]]
title = "これはさすがに疑う"
artist = "浜口史郎"

[[discs.tracks]]
title = "クライマックスに向かって叫べ!"
artist = "浜口史郎"

[[discs]]
catalog = "LACA-9218"

[[discs.tracks]]
title = "妄想は個人の自由"
artist = "浜口史郎"

[[discs.tracks]]
title = "騒がしくて楽しい時"
artist = "浜口史郎"

[[discs.tracks]]
title = "軽快なムード"
artist = "浜口史郎"

[[discs.tracks]]
title = "グイグイ進め"
artist = "浜口史郎"

[[discs.tracks]]
title = "遠い目で考える"
artist = "浜口史郎"

[[discs.tracks]]
title = "想いを告げる難しさ"
artist = "浜口史郎"

[[discs.tracks]]
title = "不器用な乙女ほど美しく"
artist = "浜口史郎"

[[discs.tracks]]
title = "考えの果ては夢の中"
artist = "浜口史郎"

[[discs.tracks]]
title = "郷愁という気持ち～from ハナノイロ～"
artist = "浜口史郎"

[[discs.tracks]]
title = "悲しさは曇り空に似てる"
artist = "浜口史郎"

[[discs.tracks]]
title = "想いは言葉にしたらいい"
artist = "浜口史郎"

[[discs.tracks]]
title = "募る想いと悲しさは裏表"
artist = "浜口史郎"

[[discs.tracks]]
title = "解放されていく感情"
artist = "浜口史郎"

[[discs.tracks]]
title = "一生懸命さの時間"
artist = "浜口史郎"

[[discs.tracks]]
title = "受け止めてくれる優しさ～from ハナノイロ～"
artist = "浜口史郎"

[[discs.tracks]]
title = "笑顔で思い出せるあの日のこと"
artist = "浜口史郎"

[[discs.tracks]]
title = "氷が優しく溶けるように分かり合う"
artist = "浜口史郎"

[[discs.tracks]]
title = "新しい時間に出会える喜び"
artist = "浜口史郎"

[[discs.tracks]]
title = "文化の違いは生活の違い"
artist = "浜口史郎"

[[discs.tracks]]
title = "アイディアがまとまっていく瞬間"
artist = "浜口史郎"

[[discs.tracks]]
title = "行動する少女たち"
artist = "浜口史郎"

[[discs.tracks]]
title = "綺麗な気持ちになりました"
artist = "浜口史郎"

[[discs.tracks]]
title = "安心感は嬉しさに繋がる"
artist = "浜口史郎"

[[discs.tracks]]
title = "Ray of Light"
artist = "浜口史郎"

[[discs.tracks]]
title = "祭りの時"
artist = "浜口史郎"

[[discs.tracks]]
title = "懐かしさは微笑みをもたらす"
artist = "浜口史郎"

[[discs.tracks]]
title = "嬉しさ優しさ暖かさ"
artist = "浜口史郎"

[[discs.tracks]]
title = "不安の脈動"
artist = "浜口史郎"

[[discs.tracks]]
title = "ぼんぼり夜"
artist = "浜口史郎"
