[album]
album_id = "8a828a5e-6492-4e10-808e-77c84c496cf8"
title = "『劇場版 響け！ユーフォニアム～北宇治高校吹奏楽部へようこそ～』オリジナルサウンドトラック「Reflection of youthful music」"
artist = "松田彬人"
date = 2016-04-27
type = "absolute"
catalog = "LACA-15563"

[[discs]]
catalog = "LACA-15563"

[[discs.tracks]]
title = "私たちの曲が始まる"

[[discs.tracks]]
title = "桜舞うなかで"

[[discs.tracks]]
title = "学校生活"

[[discs.tracks]]
title = "未来はまだ見えない"

[[discs.tracks]]
title = "イントロダクション"

[[discs.tracks]]
title = "新たな出会い"

[[discs.tracks]]
title = "目指せ、全国"

[[discs.tracks]]
title = "不穏"

[[discs.tracks]]
title = "純粋な想い"

[[discs.tracks]]
title = "猛練習"

[[discs.tracks]]
title = "順調な日々"

[[discs.tracks]]
title = "一歩踏み出すこと"

[[discs.tracks]]
title = "小さな変化"

[[discs.tracks]]
title = "あがた祭りの夜"

[[discs.tracks]]
title = "特別になること"

[[discs.tracks]]
title = "それぞれの意思"

[[discs.tracks]]
title = "積層する想い"

[[discs.tracks]]
title = "宣告"

[[discs.tracks]]
title = "渦巻く想い"

[[discs.tracks]]
title = "告白"

[[discs.tracks]]
title = "確かな決意"

[[discs.tracks]]
title = "譲れないもの"

[[discs.tracks]]
title = "ふたりきり"

[[discs.tracks]]
title = "答え"

[[discs.tracks]]
title = "大切なもの"

[[discs.tracks]]
title = "いざ本番"

[[discs.tracks]]
title = "そして扉が開く"

[[discs.tracks]]
title = "未来への旋律"

[[discs.tracks]]
title = "DREAM SOLISTER (Movie Ver.)"
artist = "TRUE"
type = "normal"
