[album]
title = "TV アニメ『魔王城でおやすみ』オリジナルサウンドトラック"
artist = "橋本由香利"
date = 2020-12-23
type = "absolute"
catalog = "LACA-15853"

[[discs]]
catalog = "LACA-15853"

[[discs.tracks]]
title = "快眠！安眠！スヤリスト生活(TV Size)"
artist = "スヤリス姫（水瀬いのり）"
type = "normal"

[[discs.tracks]]
title = "カイミーン王国"

[[discs.tracks]]
title = "すやぁ、、、、、"

[[discs.tracks]]
title = "魔王城"

[[discs.tracks]]
title = "黄昏るタソガレ"

[[discs.tracks]]
title = "魔導書アラージフ"

[[discs.tracks]]
title = "カイミンを探して"

[[discs.tracks]]
title = "魔族も眠いんですけど"

[[discs.tracks]]
title = "むぅ～"

[[discs.tracks]]
title = "最高の眠りとは？"

[[discs.tracks]]
title = "快眠の材料を集めよう"

[[discs.tracks]]
title = "混乱する姫と魔物"

[[discs.tracks]]
title = "あ、そういうことね"

[[discs.tracks]]
title = "暗闇からモフモフ"

[[discs.tracks]]
title = "フェニックスの卵を守れ！"

[[discs.tracks]]
title = "十傑会議"

[[discs.tracks]]
title = "爽やかな目覚め"

[[discs.tracks]]
title = "アイテム庫へ侵入"

[[discs.tracks]]
title = "魔物達のピンチ"

[[discs.tracks]]
title = "でびあくま、危ないっ！！"

[[discs.tracks]]
title = "懐かしい故郷"

[[discs.tracks]]
title = "城外へ行ってみよう"

[[discs.tracks]]
title = "勇者アカツキ"

[[discs.tracks]]
title = "進む勇者達"

[[discs.tracks]]
title = "悪魔修道士"

[[discs.tracks]]
title = "旧魔王城"

[[discs.tracks]]
title = "ハデスは長男"

[[discs.tracks]]
title = "オワリノシティ、街探訪"

[[discs.tracks]]
title = "クエスト攻略"

[[discs.tracks]]
title = "クエスト発生～のんびり行こう～"

[[discs.tracks]]
title = "クエスト。。。。発生なの？"

[[discs.tracks]]
title = "魔族のクエスト攻略、、、、ボチボチやね"

[[discs.tracks]]
title = "ざんね～ん、失敗です"

[[discs.tracks]]
title = "クエスト達成～よくできました～"

[[discs.tracks]]
title = "クエスト達成です～ファンファーレ～"

[[discs.tracks]]
title = "つかのまの休息"

[[discs.tracks]]
title = "私は囚われの姫、オーロラ・栖夜・リース・カイミーン"

[[discs.tracks]]
title = "快眠の達人"

[[discs.tracks]]
title = "ヒューマンズショッピング"

[[discs.tracks]]
title = "私はさっきゅん♡モテたーい！！"

[[discs.tracks]]
title = "アなんとか君"

[[discs.tracks]]
title = "素敵な言葉"

[[discs.tracks]]
title = "姫にしてやられるレッドシベリアン・改"

[[discs.tracks]]
title = "とほほほ、、、"

[[discs.tracks]]
title = "今日もめげずに頑張ってます"

[[discs.tracks]]
title = "推理する姫"

[[discs.tracks]]
title = "不思議なこともあるもんだ"

[[discs.tracks]]
title = "姫の帰還・魔王城のクリスマス"

[[discs.tracks]]
title = "Gimmme!(TV Size)"
artist = "ORESAMA"

[[discs.tracks]]
title = "魔王城サブタイトル"

[[discs.tracks]]
title = "アイキャッチ～でびあくまの日常～"

[[discs.tracks]]
title = "アイキャッチ～魔王城で快眠～"

[[discs.tracks]]
title = "アイキャッチ～はりとげマジロとのんきな魔物達～"

[[discs.tracks]]
title = "アイキャッチ～怖い系魔物～"

[[discs.tracks]]
title = "アイキャッチ～おばけふろしき～"
