[album]
album_id = "a5553840-28c2-4b0b-8b0e-e14912bfdb83"
title = "THE IDOLM@STER SHINY COLORS GR@DATE WING 01"
artist = "シャイニーカラーズ"
date = 2020-04-08
type = "normal"
catalog = "LACM-14982"
tags = [
  "THE IDOLM@STER Shiny Colors",
  "THE IDOLM@STER SHINY COLORS GR@DATE WING"
]

[[discs]]
catalog = "LACM-14982"

[[discs.tracks]]
title = "シャイノグラフィ"

[[discs.tracks]]
title = "Dye the sky."
