[album]
album_id = "e9d7f3e2-c74c-45f6-aa00-154441c097b6"
title = "VOY@GER【ミリオンライブ！盤】"
artist = "THE IDOLM@STER FIVE STARS!!!!!"
date = 2021-08-04
type = "normal"
catalog = "LACM-24163"

[[discs]]
catalog = "LACM-24163"

[[discs.tracks]]
title = "VOY@GER THE IDOLM@STER FIVE STARS!!!!!"

[[discs.tracks]]
title = "VOY@GER (Off Vocal)"
type = "instrumental"

[[discs.tracks]]
title = "VOY@GER ミリオンライブ！バージョン"
artist = "高坂海美（上田麗奈）、白石紬（南早紀）、望月杏奈（夏川椎菜）"

[[discs.tracks]]
title = "VOY@GER 高坂海美ソロバージョン"
artist = "高坂海美（上田麗奈）"

[[discs.tracks]]
title = "VOY@GER 白石 紬ソロバージョン"
artist = "白石紬（南早紀）"

[[discs.tracks]]
title = "VOY@GER 望月杏奈ソロバージョン"
artist = "望月杏奈（夏川椎菜）"
