[album]
album_id = "2113db23-656f-443c-9a3e-aa23a16b6195"
title = "RESOLVE"
artist = "田所あずさ"
date = 2018-07-25
type = "normal"
catalog = "LACM-14776"

[[discs]]
catalog = "LACM-14776"

[[discs.tracks]]
title = "RESOLVE"

[[discs.tracks]]
title = "SHAKA BOOM"

[[discs.tracks]]
title = "スキライ"
