[album]
album_id = "524b1a85-47f3-4b53-b792-9e6a624ab247"
title = "君との約束を数えよう【Type.A】"
artist = "田所あずさ"
date = 2015-09-02
type = "normal"
catalog = "LACM-14383"

[[discs]]
catalog = "LACM-14383"

[[discs.tracks]]
title = "君との約束を数えよう"

[[discs.tracks]]
title = "Straight Forward"

[[discs.tracks]]
title = "シーソー"
