[album]
album_id = "452fb893-41a0-459f-9c38-06648b525dc4"
title = "TVアニメ『響け！ユーフォニアム』キャラクターソング Vol.3"
artist = "川島緑輝（豊田萌絵）"
date = 2015-07-15
type = "normal"
catalog = "LACM-14366"

[[discs]]
catalog = "LACM-14366"

[[discs.tracks]]
title = "流線コントラスト"

[[discs.tracks]]
title = "I LOVE MUSIC"

[[discs.tracks]]
title = "北宇治四重奏 第3番 コントラバス"
type = "absolute"

[[discs.tracks]]
title = "流線コントラスト (OFF VOCAL)"
type = "instrumental"

[[discs.tracks]]
title = "I LOVE MUSIC (OFF VOCAL)"
type = "instrumental"
