[album]
album_id = "b60e7ab9-9ccc-4c48-b160-e3cd136b7271"
title = "ヤサシイセカイ"
artist = "田所あずさ"
date = 2020-11-11
type = "normal"
catalog = "LACM-24048"

[[discs]]
catalog = "LACM-24048"

[[discs.tracks]]
title = "ヤサシイセカイ"

[[discs.tracks]]
title = "New-me"

[[discs.tracks]]
title = "Visual Vampire"
