[album]
album_id = "30da208c-709a-483f-ae50-067ba8737867"
title = "sleepland"
artist = "上田麗奈"
date = 2018-02-07
type = "normal"
catalog = "LACM-14724"

[[discs]]
catalog = "LACM-14724"

[[discs.tracks]]
title = "sleepland"

[[discs.tracks]]
title = "誰もわたしを知らない世界へ"

[[discs.tracks]]
title = "fairy taleの明けに"
