[album]
album_id = "73470e65-9596-4b10-9dff-6b70981e52f6"
title = "運命ジレンマ"
artist = "田所あずさ"
date = 2017-01-25
type = "normal"
catalog = "LACM-14567"

[[discs]]
catalog = "LACM-14567"

[[discs.tracks]]
title = "運命ジレンマ"

[[discs.tracks]]
title = "スーパースタールーザー"

[[discs.tracks]]
title = "EMOTION"
