[album]
album_id = "88d27f68-e6d3-48fa-9b60-374d5d9399f2"
title = "THE IDOLM@STER SHINY COLORS FR@GMENT WING 01"
artist = "シャイニーカラーズ"
date = 2019-04-10
type = "normal"
catalog = "LACM-14861"
tags = [
  "THE IDOLM@STER Shiny Colors",
  "THE IDOLM@STER SHINY COLORS FR@GMENT WING"
]

[[discs]]
catalog = "LACM-14861"

[[discs.tracks]]
title = "Ambitious Eve"

[[discs.tracks]]
title = "いつか Shiny Days"
