[album]
album_id = "a497b807-8844-44a1-849c-09f167b3a8ac"
title = "DREAM LINE【ビジュアル盤】"
artist = "田所あずさ"
date = 2015-04-22
type = "normal"
catalog = "LACM-14336"

[[discs]]
catalog = "LACM-14336"

[[discs.tracks]]
title = "DREAM LINE"

[[discs.tracks]]
title = "POSITIVE SHAKING"

[[discs.tracks]]
title = "セツナレター"
