[album]
album_id = "c4516f72-0c74-44e5-b228-8259c1607fd9"
title = "サウンドスケープ"
artist = "TRUE"
date = 2016-10-12
type = "normal"
catalog = "LACM-14535"

[[discs]]
catalog = "LACM-14535"

[[discs.tracks]]
title = "サウンドスケープ"

[[discs.tracks]]
title = "Hello,Good bye"

[[discs.tracks]]
title = "サウンドスケープ（off vocal）"
type = "instrumental"
