[album]
album_id = "11b1c75b-488e-46ad-b4c5-9a555eeb37b8"
title = "イコール"
artist = "田所あずさ"
date = 2019-08-21
type = "normal"
catalog = "LACM-14920"

[[discs]]
catalog = "LACM-14920"

[[discs.tracks]]
title = "イコール"

[[discs.tracks]]
title = "あずさ２号のテーマ"

[[discs.tracks]]
title = "焦らずにいこう"
