[album]
album_id = "b191e34d-60d9-474f-918e-b804244ef12e"
title = "Magic Words"
artist = "Liyuu"
date = 2020-01-22
type = "normal"
catalog = "LACM-34927"

[[discs]]
catalog = "LACM-34927"

[[discs.tracks]]
title = "Magic Words"

[[discs.tracks]]
title = "魔法とガムと勇気"

[[discs.tracks]]
title = "Magic Words -instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "魔法とガムと勇気 -instrumental-"
type = "instrumental"
