[album]
album_id = "6e8582b5-7e30-422c-a7b1-6d6f500161de"
title = "DEAREST DROP"
artist = "田所あずさ"
date = 2017-04-26
type = "normal"
catalog = "LACM-14588"

[[discs]]
catalog = "LACM-14588"

[[discs.tracks]]
title = "DEAREST DROP"

[[discs.tracks]]
title = "残存エレジー"

[[discs.tracks]]
title = "レッドラズベリー"
