[album]
album_id = "da9b62cc-5889-4170-bf9b-0ee601d7f2be"
title = "THE IDOLM@STER LIVE THE@TER DREAMERS 05"
artist = "木下ひなた（田村奈央）、双海亜美（下田麻美）、四条貴音（原由実）、豊川風花（末柄里恵）、野々原茜（小笠原早紀）、ロコ（中村温姫）、松田亜利沙（村川梨衣）、横山奈緒（渡部優衣）、三浦あずさ（たかはし智秋）、百瀬莉緒（山口立花子）"
date = 2016-01-27
type = "normal"
catalog = "LACM-15525"
tags = ["THE IDOLM@STER LIVE THE@TER DREAMERS"]

[[discs]]
catalog = "LACM-15525"

[[discs.tracks]]
title = "765PRO LIVE THE@TER大阪公演初日・早朝"
type = "drama"

[[discs.tracks]]
title = "765PRO LIVE THE@TER大阪公演開演前"
type = "drama"

[[discs.tracks]]
title = "Dreaming!"

[[discs.tracks]]
title = '"Your" HOME TOWN'
artist = "木下ひなた（田村奈央）、双海亜美（下田麻美）"

[[discs.tracks]]
title = "fruity love"
artist = "野々原茜（小笠原早紀）、ロコ（中村温姫）"

[[discs.tracks]]
title = "765PRO LIVE THE@TER大阪公演幕間"
type = "drama"

[[discs.tracks]]
title = "夜に輝く星座のように"
artist = "松田亜利沙（村川梨衣）、横山奈緒（渡部優衣）"

[[discs.tracks]]
title = "秘密のメモリーズ"
artist = "四条貴音（原由実）、豊川風花（末柄里恵）"

[[discs.tracks]]
title = "たしかな足跡"
artist = "三浦あずさ（たかはし智秋）、百瀬莉緒（山口立花子）"

[[discs.tracks]]
title = "765PRO LIVE THE@TER大阪公演終演後"
type = "drama"
