[album]
album_id = "3684bf09-e071-4e86-a2bf-9e6dd3ea5d16"
title = "THE IDOLM@STER SHINY COLORS L@YERED WING 03"
artist = "アンティーカ"
date = 2021-06-09
type = "normal"
catalog = "LACM-24113"
tags = ["アンティーカ", "THE IDOLM@STER SHINY COLORS L@YERED WING"]

[[discs]]
catalog = "LACM-24113"

[[discs.tracks]]
title = "abyss of conflict"

[[discs.tracks]]
title = "革命進化論"

[[discs.tracks]]
title = "Resonance⁺（アンティーカ Ver.）"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「Labyrinthus」"
type = "drama"

[[discs.tracks]]
title = "abyss of conflict（Off Vocal）"
type = "instrumental"

[[discs.tracks]]
title = "革命進化論 (Off Vocal)"
type = "instrumental"
