[album]
album_id = "3420b8ae-e072-4e95-9fa4-feb2c841f5fe"
title = "THE IDOLM@STER LIVE THE@TER SOLO COLLECTION 07 プリンセススターズ"
artist = "Various Artists"
date = 2019-04-27
type = "normal"
catalog = "LACZ-10020"
tags = ["THE IDOLM@STER LIVE THE@TER SOLO COLLECTION"]

[[discs]]
catalog = "LACZ-10020"

[[discs.tracks]]
title = "Dreaming!"
artist = "横山奈緖（渡部優衣）"

[[discs.tracks]]
title = "赤い世界が消える頃"
artist = "佐竹美奈子（大関英里）"

[[discs.tracks]]
title = "ゲキテキ！ムテキ！恋したい！"
artist = "中谷育（原嶋あかり）"

[[discs.tracks]]
title = "Bonnes! Bonnes!! Vacances!!!"
artist = "福田のり子（浜崎奈々）"

[[discs.tracks]]
title = "メメント？モメント♪ルルルルル☆"
artist = "徳川まつり（諏訪彩花）"

[[discs.tracks]]
title = "Brand New Theater!"
artist = "矢吹可奈（木戸衣吹）"

[[discs.tracks]]
title = "Tomorrow Program"
artist = "七尾百合子（伊藤美来）"

[[discs.tracks]]
title = "咲くは浮世の君花火"
artist = "高山紗代子（駒形友梨）"

[[discs.tracks]]
title = "BORN ON DREAM! ～HANABI☆NIGHT～"
artist = "高坂海美（上田麗奈）"

[[discs.tracks]]
title = "UNION!!"
artist = "松田亜利沙（村川梨衣）"

[[discs.tracks]]
title = "ラスト・アクトレス"
artist = "田中琴葉（種田梨沙）"

[[discs.tracks]]
title = "ミラージュ・ミラー"
artist = "エミリー スチュアート（郁原ゆう）"

[[discs.tracks]]
title = "Episode. Tiara"
artist = "春日未来（山崎はるか）"
