[album]
album_id = "a9db8dc8-7024-436d-befc-60815230cb89"
title = "THE IDOLM@STER LIVE THE@TER SOLO COLLECTION 07 エンジェルスターズ"
artist = "Various Artists"
date = 2019-04-27
type = "normal"
catalog = "LACZ-10022"
tags = ["THE IDOLM@STER LIVE THE@TER SOLO COLLECTION"]

[[discs]]
catalog = "LACZ-10022"

[[discs.tracks]]
title = "piece of cake"
artist = "北上麗花（平山笑美）"

[[discs.tracks]]
title = "fruity love"
artist = "野々原茜（小笠原早紀）"

[[discs.tracks]]
title = "創造ははじまりの風を連れて"
artist = "箱崎星梨花（麻倉もも）"

[[discs.tracks]]
title = "俠気乱舞"
artist = "大神環（稲川英里）"

[[discs.tracks]]
title = "ランニング・ハイッ！"
artist = "木下ひなた（田村奈央）"

[[discs.tracks]]
title = "Starry Melody"
artist = "馬場このみ（高橋未奈美）"

[[discs.tracks]]
title = "虹色letters"
artist = "島原エレナ（角元明日香）"

[[discs.tracks]]
title = "想い出はクリアスカイ"
artist = "宮尾美也（桐谷蝶々）"

[[discs.tracks]]
title = "花ざかりWeekend✿"
artist = "豊川風花（末柄里恵）"

[[discs.tracks]]
title = "RED ZONE"
artist = "桜守歌織（香里有佐）"

[[discs.tracks]]
title = "ハルマチ女子"
artist = "伊吹翼（Machico）"

[[discs.tracks]]
title = "彼氏になってよ。"
artist = "篠宮可憐（近藤唯）"

[[discs.tracks]]
title = "ピコピコIIKO! インベーダー"
artist = "望月杏奈（夏川椎菜）"
