[album]
album_id = "e94fbc3e-ca2b-46fb-8b83-dd4da222e918"
title = "ご注文はうさぎですか？？キャラクターソロシリーズ Special Disc"
artist = "Various Artists"
date = 2018-12-05
type = "normal"
catalog = "LPR-794"

[[discs]]
catalog = "LPR-794"

[[discs.tracks]]
title = "わーいわーいトライ！"
artist = "ココア（佐倉綾音）、チノ（水瀬いのり）、リゼ（種田梨沙）、千夜（佐藤聡美）、シャロ（内田真礼）、マヤ（徳井青空）、メグ（村川梨衣）、青山ブルーマウンテン（早見沙織）、モカ（茅野愛衣）"

[[discs.tracks]]
title = "Have a Nice Drink"
artist = "タカヒロ（速水奨）"

[[discs.tracks]]
title = "わーいわーいトライ！(Instrumental)"
artist = "ココア（佐倉綾音）、チノ（水瀬いのり）、リゼ（種田梨沙）、千夜（佐藤聡美）、シャロ（内田真礼）、マヤ（徳井青空）、メグ（村川梨衣）、青山ブルーマウンテン（早見沙織）、モカ（茅野愛衣）"
type = "instrumental"

[[discs.tracks]]
title = "Have a Nice Drink (Instrumental)"
artist = "タカヒロ（速水奨）"
type = "instrumental"
