[album]
title = "ダイヤモンド・クラリティ"
artist = "BRIGHT DIAMOND（春日未来（山崎はるか）、田中琴葉（種田梨沙）、徳川まつり（諏訪彩花）、所恵美（藤井ゆきよ）、百瀬莉緒（山口立花子）、周防桃子（渡部恵子）、伊吹翼（Machico）、宮尾美也（桐谷蝶々）、桜守歌織（香里有佐）、萩原雪歩（浅倉杏美）、水瀬伊織（釘宮理恵）、四条貴音（原由実）、双海真美（下田麻美））"
date = 2021-09-28
type = "normal"
catalog = "LZC-1941"

[[discs]]
catalog = "LZC-1941"

[[discs.tracks]]
title = "ダイヤモンド・クラリティ"
