[album]
title = "THE IDOLM@STER LIVE THE@TER SOLO COLLECTION 04 Starlight Theater"
artist = "Various Artists"
date = 2017-03-09
type = "normal"
catalog = "LZM-2157"
tags = ["THE IDOLM@STER LIVE THE@TER SOLO COLLECTION"]

[[discs]]
catalog = "LZM-2157"

[[discs.tracks]]
title = "瞳の中のシリウス"
artist = "宮尾美也（桐谷蝶々）"

[[discs.tracks]]
title = "U・N・M・E・I ライブ"
artist = "春日未来（山崎はるか）"

[[discs.tracks]]
title = "ジレるハートに火をつけて"
artist = "田中琴葉（種田梨沙）"

[[discs.tracks]]
title = "Cut. Cut. Cut."
artist = "周防桃子（渡部恵子）"

[[discs.tracks]]
title = "Smiling Crescent"
artist = "箱崎星梨花（麻倉もも）"

[[discs.tracks]]
title = "Decided"
artist = "徳川まつり（諏訪彩花）"

[[discs.tracks]]
title = "夜に輝く星座のように"
artist = "松田亜利沙（村川梨衣）"

[[discs.tracks]]
title = "秘密のメモリーズ"
artist = "豊川風花（末柄里恵）"

[[discs.tracks]]
title = "Understand? Understand!"
artist = "高坂海美（上田麗奈）"

[[discs.tracks]]
title = "ジャングル☆パーティー"
artist = "大神環（稲川英里）"

[[discs.tracks]]
title = "リフレインキス"
artist = "北沢志保（雨宮天）"

[[discs.tracks]]
title = "Sweet Sweet Soul"
artist = "野々原茜（小笠原早紀）"

[[discs.tracks]]
title = "永遠の花"
artist = "馬場このみ（高橋未奈美）"
