[album]
album_id = "1bbb2a68-e23a-45cd-ad7e-4bb7c1e1482b"
title = "サクラノ詩 サウンドトラックCD"
artist = "松本文紀"
date = 2015-10-23
type = "absolute"
catalog = "MAKURA-801-S1~2"

[[discs]]
catalog = "MAKURA-801-S1"

[[discs.tracks]]
title = "美しい音色で世界が鳴った"

[[discs.tracks]]
title = "見上げた青の果て"

[[discs.tracks]]
title = "櫻ノ詩 (OP short ver.)"
artist = "はな"
type = "normal"

[[discs.tracks]]
title = "舞い上がる因果交流のひかり"

[[discs.tracks]]
title = "絵画は歌う"

[[discs.tracks]]
title = "瞬間を閉じ込めた永遠"

[[discs.tracks]]
title = "螺旋に伸びる色彩"

[[discs.tracks]]
title = "音符は歩き出す"

[[discs.tracks]]
title = "バカはバカのごとく現れる"

[[discs.tracks]]
title = "陽射し入る窓"

[[discs.tracks]]
title = "夜の流れはゆっくりと"

[[discs.tracks]]
title = "昼間の絵画達"

[[discs.tracks]]
title = "紳士ゲェム"

[[discs.tracks]]
title = "君の筆は世界を奏でる"

[[discs.tracks]]
title = "遊ぶ絵画"

[[discs.tracks]]
title = "数秒交差"

[[discs.tracks]]
title = "透明な嘘の花"

[[discs.tracks]]
title = "色彩力無限"

[[discs.tracks]]
title = "君が立つ大地だ"

[[discs.tracks]]
title = "ざくざくと散る錆びた夢"

[[discs.tracks]]
title = "花弁となり 世界は大いに歌う"

[[discs.tracks]]
title = "ZYPRESSENは櫻に変わる"

[[discs]]
catalog = "MAKURA-801-S2"

[[discs.tracks]]
title = "この櫻ノ詩の下"

[[discs.tracks]]
title = "透明な白い日常"

[[discs.tracks]]
title = "呼吸のように筆は踊る"

[[discs.tracks]]
title = "心模型"

[[discs.tracks]]
title = "花弁となり桜は大いに歌う"

[[discs.tracks]]
title = "因果的交流の世界"

[[discs.tracks]]
title = "舞い上がる因果交流"

[[discs.tracks]]
title = "夢の歩みを見上げて"

[[discs.tracks]]
title = "優雅な音階"

[[discs.tracks]]
title = "♪模型"

[[discs.tracks]]
title = "月の眼球譚"

[[discs.tracks]]
title = "心象の中の光"

[[discs.tracks]]
title = "在りし日のために - inst ver. -"

[[discs.tracks]]
title = "空を舞う月 空を舞う翼"

[[discs.tracks]]
title = "ジムノペディ"

[[discs.tracks]]
title = "軽やかに! 軽やかに!"

[[discs.tracks]]
title = "夜空は奏でるだろう"

[[discs.tracks]]
title = "真っ赤な真実"

[[discs.tracks]]
title = "天球の奇蹟"

[[discs.tracks]]
title = "シューマン交響曲第一番的日常"

[[discs.tracks]]
title = "ありがとう在りし日"

[[discs.tracks]]
title = "風の筆射す春日花抄"
