[album]
title = "Fly Me to the Star"
artist = "スタァライト九九組（愛城華恋（小山百代）、神楽ひかり（三森すずこ）、天堂真矢（富田麻帆）、星見純那（佐藤日向）、露崎まひる（岩田陽葵）、大場なな（小泉萌香）、西條クロディーヌ（相羽あいな）、石動双葉（生田輝）、花柳香子（伊藤彩沙））"
date = 2018-08-01
type = "normal"
catalog = "PCCG-01703"

[[discs]]
catalog = "PCCG-01703"

[[discs.tracks]]
title = "Fly Me to the Star"

[[discs.tracks]]
title = "よろしく九九組"

[[discs.tracks]]
title = "ロマンティッククルージン"

[[discs.tracks]]
title = "Fly Me to the Star［Instrumental］"
type = "instrumental"

[[discs.tracks]]
title = "よろしく九九組［Instrumental］"
type = "instrumental"

[[discs.tracks]]
title = "ロマンティッククルージン［Instrumental］"
type = "instrumental"
