[album]
album_id = "33ce4d96-6df2-4aa1-a3be-bcd3fb7be7b9"
title = "モノクロームオーバードライブ"
artist = "遠藤ゆりか"
date = 2014-02-05
type = "normal"
catalog = "PCCG-01383"
tags = ["遠藤ゆりか"]

[[discs]]
catalog = "PCCG-01383"

[[discs.tracks]]
title = "モノクロームオーバードライブ"

[[discs.tracks]]
title = "REBORN"

[[discs.tracks]]
title = "モノクロームオーバードライブ (instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "REBORN (instrumental)"
type = "instrumental"
