[album]
album_id = "3da2fe3f-0a0d-4a91-93e6-a194d943e7ed"
title = "DIALOGUE＋1"
artist = "DIALOGUE+（内山悠里菜、稗田寧々、守屋亨香、緒方佑奈、鷹村彩花、宮原颯希、飯塚麻結、村上まなつ）"
date = 2021-09-01
type = "normal"
catalog = "PCCG-2052"

[[discs]]
catalog = "PCCG-2052"

[[discs.tracks]]
title = "Sincere Grace"

[[discs.tracks]]
title = "人生イージー？"

[[discs.tracks]]
title = "ドラマティックピース!!"

[[discs.tracks]]
title = "謎解きはキスのあとで"

[[discs.tracks]]
title = "プライベイト"

[[discs.tracks]]
title = "あやふわアスタリスク"

[[discs.tracks]]
title = "夏の花火と君と青"

[[discs.tracks]]
title = "I my me mind"

[[discs.tracks]]
title = "アイガッテ♡ランテ"

[[discs.tracks]]
title = "おもいでしりとり"

[[discs.tracks]]
title = "20xxMUEの光"

[[discs.tracks]]
title = "透明できれい"

[[discs.tracks]]
title = "はじめてのかくめい！2021"
