[album]
album_id = "7052ed0c-6762-4a11-9c4a-4cfb739d2bcf"
title = "おもいでしりとり"
artist = "DIALOGUE+（内山悠里菜、稗田寧々、守屋亨香、緒方佑奈、鷹村彩花、宮原颯希、飯塚麻結、村上まなつ）"
date = 2021-05-19
type = "normal"
catalog = "PCCG-02010"

[[discs]]
catalog = "PCCG-02010"

[[discs.tracks]]
title = "おもいでしりとり"

[[discs.tracks]]
title = "シュガーロケット"

[[discs.tracks]]
title = "おもいでしりとり（TVサイズ）"

[[discs.tracks]]
title = "おもいでしりとり（Instrumental）"
type = "instrumental"

[[discs.tracks]]
title = "シュガーロケット（Instrumental）"
type = "instrumental"
