[album]
album_id = "5c2bbf04-69f4-42f6-a8a7-8631142bcd37"
title = "プロローグ -Star Divine-"
artist = "スタァライト九九組（愛城華恋（小山百代）、神楽ひかり（三森すずこ）、天堂真矢（富田麻帆）、星見純那（佐藤日向）、露崎まひる（岩田陽葵）、大場なな（小泉萌香）、西條クロディーヌ（相羽あいな）、石動双葉（生田輝）、花柳香子（伊藤彩沙））"
date = 2017-09-20
type = "normal"
catalog = "PCCG-01633"

[[discs]]
catalog = "PCCG-01633"

[[discs.tracks]]
title = "Star Divine"

[[discs.tracks]]
title = "舞台少女心得"

[[discs.tracks]]
title = "願いは光になって"

[[discs.tracks]]
title = "Star Divine［Instrumental］"
type = "instrumental"

[[discs.tracks]]
title = "舞台少女心得［Instrumental］"
type = "instrumental"

[[discs.tracks]]
title = "願いは光になって［Instrumental］"
type = "instrumental"
