[album]
title = "9-nine- ここのつここのかここのいろ メロンブックス特典ドラマCD 「都ちゃん、はじめての耳かき。」"
artist = "九條都（澤田なつ（福圓美里））"
date = 2017-04-28
type = "drama"
catalog = "PLT-1704MB"

[[discs]]
catalog = "PLT-1704MB"

[[discs.tracks]]
title = "都ちゃん、はじめての耳かき。"
