[album]
title = "9-nine- ここのつここのかここのいろ ソフマップ特典ドラマCD 「都ちゃん、ちょっとえっちなマッサージ。」"
artist = "九條都（澤田なつ（福圓美里））"
date = 2017-04-28
type = "drama"
catalog = "PLT-1704SM"

[[discs]]
catalog = "PLT-1704SM"

[[discs.tracks]]
title = "都ちゃん、ちょっとえっちなマッサージ。"
