[album]
album_id = "c4f0125e-a2d4-4b9b-a9d6-dda908894061"
title = "魔法少女まどか☆マギカ『魔法少女たちのお茶会』"
artist = "Various Artists"
date = 2011-06-22
type = "drama"
catalog = "SBCV-80091"
tags = ["魔法少女まどか☆マギカ"]

[[discs]]
catalog = "SBCV-80091"

[[discs.tracks]]
title = "魔法少女たちのお茶会"
