[album]
album_id = "1463513c-e889-4142-b482-47b2fcea33c9"
title = "ひまわり -Pebble in the Sky- Portable オリジナルサウンドトラック"
artist = "Various Artists"
date = 2010-04-23
type = "absolute"
catalog = "SDCR-0030"

[[discs]]
catalog = "SDCR-0030-01"
type = "normal"

[[discs.tracks]]
title = "gleaming sky"
artist = "eufonius"

[[discs.tracks]]
title = "サヨナラ。"
artist = "yuiko"

[[discs.tracks]]
title = "WISH"
artist = "癒月"

[[discs.tracks]]
title = "星のロケット"
artist = "真理絵"

[[discs.tracks]]
title = "向日葵"
artist = "茶太"

[[discs.tracks]]
title = "gleaming sky ～cuckool mix～"
artist = "eufonius"

[[discs]]
catalog = "SDCR-0030-02"
artist = "中畑丈治"

[[discs.tracks]]
title = "百花"

[[discs.tracks]]
title = "あさがお (オルゴールバージョン)"

[[discs.tracks]]
title = "everyday morning"

[[discs.tracks]]
title = "daylight"

[[discs.tracks]]
title = "あさがお"

[[discs.tracks]]
title = "I My Me"

[[discs.tracks]]
title = "あじさい"

[[discs.tracks]]
title = "4 Steps"

[[discs.tracks]]
title = "8 Steps"

[[discs.tracks]]
title = "GALAXY"

[[discs.tracks]]
title = "war hero"

[[discs.tracks]]
title = "Shooting Star Child"

[[discs.tracks]]
title = "虚空"

[[discs.tracks]]
title = "Starlight"

[[discs.tracks]]
title = "さくら"

[[discs.tracks]]
title = "星空の下"

[[discs.tracks]]
title = "Beautiful Dreamer"

[[discs.tracks]]
title = "パピリオ"

[[discs.tracks]]
title = "薄氷の道"

[[discs.tracks]]
title = "You can't Forget"

[[discs.tracks]]
title = "偉大なる一歩"
artist = "dai"

[[discs.tracks]]
title = "ひまわりも寝る夜"
artist = "dai"

[[discs.tracks]]
title = "ひまわりの微笑み"
artist = "dai"

[[discs.tracks]]
title = "Red and Blue"
artist = "dai"

[[discs.tracks]]
title = "残念賞"
artist = "dai"

[[discs.tracks]]
title = "Gt"
artist = "dai"

[[discs.tracks]]
title = "ホラー"
artist = "dai"

[[discs.tracks]]
title = "ひまわりの帰り道"
artist = "dai"

[[discs.tracks]]
title = "星"
artist = "dai"

[[discs.tracks]]
title = "Android's Dream"

[[discs.tracks]]
title = "順風"

[[discs.tracks]]
title = "underground"

[[discs.tracks]]
title = "Ghost buster"

[[discs.tracks]]
title = "星海の彼方へ"

[[discs.tracks]]
title = "白銀の大河"

[[discs.tracks]]
title = "青空の下"

[[discs.tracks]]
title = "最後に君がいた"

[[discs.tracks]]
title = "Neverending Story"

[[discs.tracks]]
title = "月光蝶"

[[discs.tracks]]
title = "繚乱"
