[album]
album_id = "a969325a-83b5-4628-a872-4f2e3d252db8"
title = "SPARK-AGAIN"
artist = "Aimer"
date = 2020-09-09
type = "normal"
catalog = "SECL-2605"

[[discs]]
catalog = "SECL-2605"

[[discs.tracks]]
title = "SPARK-AGAIN"

[[discs.tracks]]
title = "悲しみの向こう側"

[[discs.tracks]]
title = "Ash flame"

[[discs.tracks]]
title = "Work it out"
