[album]
album_id = "5d2f8fc8-a8e8-4e21-b36d-8f21ce76aa17"
title = "Ref:rain／眩いばかり"
artist = "Aimer"
date = 2018-02-21
type = "normal"
catalog = "SECL-2252"

[[discs]]
catalog = "SECL-2252"

[[discs.tracks]]
title = "Ref:rain"

[[discs.tracks]]
title = "眩いばかり"

[[discs.tracks]]
title = "After Rain –Scarlet ver.-"

[[discs.tracks]]
title = "Raining"
