[album]
title = "Magia"
edition = "まどか☆マギカ盤"
artist = "Kalafina（Wakana、Keiko、Hikaru）"
date = 2011-02-16
type = "normal"
catalog = "SECL-942"
tags = ["Kalafina", "魔法少女まどか☆マギカ"]

[[discs]]
catalog = "SECL-942"

[[discs.tracks]]
title = "Magia"

[[discs.tracks]]
title = "Magia ～magic mix～"

[[discs.tracks]]
title = "Magia ～TV Version～"

[[discs.tracks]]
title = "Magia ～instrumental～"
type = "instrumental"
