[album]
album_id = "099045ca-a80a-4d42-9b74-29deb449c894"
title = "Magia"
edition = "初回生産限定盤"
artist = "Kalafina（Wakana、Keiko、Hikaru）"
date = 2011-02-16
type = "normal"
catalog = "SECL-939"
tags = ["Kalafina"]

[[discs]]
catalog = "SECL-939"

[[discs.tracks]]
title = "Magia"

[[discs.tracks]]
title = "snow falling"

[[discs.tracks]]
title = "Magia (Instrumental)"
type = "instrumental"
