[album]
album_id = "64600c4a-8b4f-4719-bd30-3fa77cec552e"
title = "Prover／Tell me"
artist = "milet"
date = 2020-02-19
type = "normal"
catalog = "SECL-2537"
tags = ["milet"]

[[discs]]
catalog = "SECL-2537"

[[discs.tracks]]
title = "Prover"
tags = ["TVアニメ「Fate/Grand Order -絶対魔獣戦線バビロニア-」", "ED"]

[[discs.tracks]]
title = "Tell me"
tags = ["TVアニメ「Fate/Grand Order -絶対魔獣戦線バビロニア-」", "ED"]

[[discs.tracks]]
title = "Your Light"

[[discs.tracks]]
title = "レッドネオン"
