[album]
title = "コネクト"
edition = "期間生産限定盤"
artist = "ClariS（クララ、アリス）"
date = 2011-02-02
type = "normal"
catalog = "SECL-949"
tags = ["ClariS", "魔法少女まどか☆マギカ"]

[[discs]]
catalog = "SECL-949"

[[discs.tracks]]
title = "コネクト"

[[discs.tracks]]
title = "Dreamin'"

[[discs.tracks]]
title = "キミとふたり"

[[discs.tracks]]
title = "コネクト -TV MIX-"
