[album]
album_id = "bcf8bbc5-9e66-483d-aba1-bb49a030601f"
title = "君の銀の庭"
artist = "Kalafina（Wakana、Keiko、Hikaru）"
date = 2013-11-06
type = "normal"
catalog = "SECL-1422"
tags = ["劇場版 魔法少女まどか☆マギカ [新編] 叛逆の物語"]

[[discs]]
catalog = "SECL-1422"

[[discs.tracks]]
title = "君の銀の庭"

[[discs.tracks]]
title = "misterioso"

[[discs.tracks]]
title = "追憶"

[[discs.tracks]]
title = "君の銀の庭 (instrumental)"
type = "instrumental"
