[album]
album_id = "af4abc46-c20d-40e9-9be7-3aac559eb13b"
title = "Penny Rain"
artist = "Aimer"
date = 2019-04-10
type = "normal"
catalog = "SECL-2421"

[[discs]]
catalog = "SECL-2421"

[[discs.tracks]]
title = "pluie"

[[discs.tracks]]
title = "I beg you"

[[discs.tracks]]
title = "Black Bird"

[[discs.tracks]]
title = "Sailing"

[[discs.tracks]]
title = "眩いばかり"

[[discs.tracks]]
title = "Stand By You"

[[discs.tracks]]
title = "Ref:rain"

[[discs.tracks]]
title = "i-mage ＜in/AR＞"

[[discs.tracks]]
title = "花の唄"

[[discs.tracks]]
title = "April Showers"
