[album]
album_id = "a29bfcf2-701f-4091-9ab4-01a877e1a84d"
title = "VIPER"
artist = "雨宮天"
date = 2019-07-10
type = "normal"
catalog = "SMCL-604"

[[discs]]
catalog = "SMCL-604"

[[discs.tracks]]
title = "VIPER"

[[discs.tracks]]
title = "メリーゴーランド"

[[discs.tracks]]
title = "VIPER (Instrumental)"
type = "instrumental"
