[album]
album_id = "9bd7fcf6-d405-4e92-982c-1b1ffd5bfd47"
title = "誓い"
artist = "雨宮天"
date = 2018-05-09
type = "normal"
catalog = "SMCL-539"

[[discs]]
catalog = "SMCL-539"

[[discs.tracks]]
title = "誓い"

[[discs.tracks]]
title = "Abyss"

[[discs.tracks]]
title = "誓い (Instrumental)"
type = "instrumental"
