[album]
album_id = "fdf38631-a5f3-4304-b8a5-94bb16654c6e"
title = "永遠のAria"
artist = "雨宮天"
date = 2021-05-12
type = "normal"
catalog = "SMCL-700"

[[discs]]
catalog = "SMCL-700"

[[discs.tracks]]
title = "永遠のAria"

[[discs.tracks]]
title = "BLUE BLUES"

[[discs.tracks]]
title = "永遠のAria (Instrumental)"
type = "instrumental"
