[album]
album_id = "565abb5e-02a2-4905-8380-2a0e2ba7a279"
title = "irodori"
artist = "雨宮天"
date = 2017-07-26
type = "normal"
catalog = "SMCL-492"

[[discs]]
catalog = "SMCL-492"

[[discs.tracks]]
title = "irodori"

[[discs.tracks]]
title = "Fleeting Dream"

[[discs.tracks]]
title = "irodori (Instrumental)"
type = "instrumental"
