[album]
album_id = "bf26d8b2-4e98-4eb7-ba77-023929b8cfe7"
title = "フリイジア"
artist = "雨宮天"
date = 2021-07-21
type = "normal"
catalog = "SMCL-717"

[[discs]]
catalog = "SMCL-717"

[[discs.tracks]]
title = "フリイジア"

[[discs.tracks]]
title = "情熱のテ・アモ"

[[discs.tracks]]
title = "Emerald"

[[discs.tracks]]
title = "フリイジア (Instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "情熱のテ・アモ (Instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "Emerald (Instrumental)"
type = "instrumental"
