[album]
album_id = "c6edf28c-19b4-41fe-a795-e85b0604ab47"
title = "365×LOVE"
artist = "麻倉もも"
date = 2019-02-13
type = "normal"
catalog = "SMCL-591"

[[discs]]
catalog = "SMCL-591"

[[discs.tracks]]
title = "365×LOVE"

[[discs.tracks]]
title = "さよなら観覧車"

[[discs.tracks]]
title = "365×LOVE (Instrumental)"
type = "instrumental"
