[album]
album_id = "d4ab16ca-d295-4cdf-9a78-dd4be9ae80e0"
title = "PARADOX"
artist = "雨宮天"
date = 2020-01-15
type = "normal"
catalog = "SMCL-640"

[[discs]]
catalog = "SMCL-640"

[[discs.tracks]]
title = "PARADOX"

[[discs.tracks]]
title = "一番星"

[[discs.tracks]]
title = "PARADOX (Instrumental)"
type = "instrumental"
