[album]
title = "蒼の彼方のフォーリズム MAXI SINGLE CD, SOUND TRACK CD & DRAMA CD"
artist = "Various Artists"
date = 2016-02-25
type = "normal"
catalog = "SPRCS001PCD01~3"

[[discs]]
catalog = "SPRCS001PCD01"
artist = "川田まみ"

[[discs.tracks]]
title = "crossing way"

[[discs.tracks]]
title = "rays of the sun"

[[discs]]
catalog = "SPRCS001PCD02"
artist = "sprite"
type = "absolute"

[[discs.tracks]]
title = "はじまりの風"

[[discs.tracks]]
title = "めぐり逢う者達"

[[discs.tracks]]
title = "日々喧騒"

[[discs.tracks]]
title = "走れ、飛べ！"

[[discs.tracks]]
title = "翼の休息"

[[discs.tracks]]
title = "夏の夕暮れ"

[[discs.tracks]]
title = "夕焼けと音楽室"

[[discs.tracks]]
title = "暖かな日々の中で"

[[discs.tracks]]
title = "残念無念"

[[discs.tracks]]
title = "気の抜けたラムネ"

[[discs.tracks]]
title = "大脱走"

[[discs.tracks]]
title = "黒く粘りつくもの"

[[discs.tracks]]
title = "遠い光"

[[discs.tracks]]
title = "折れた道標"

[[discs.tracks]]
title = "君がいるから"

[[discs.tracks]]
title = "明日への一歩"

[[discs.tracks]]
title = "胸の奥底"

[[discs.tracks]]
title = "辿り着いた場所"

[[discs.tracks]]
title = "遠い記憶"

[[discs.tracks]]
title = "勇気の向こうに"

[[discs.tracks]]
title = "きみのこえ"

[[discs.tracks]]
title = "愛しい時間"

[[discs.tracks]]
title = "比翼の鳥"

[[discs.tracks]]
title = "ちいさな約束"

[[discs.tracks]]
title = "大きな空の下で"

[[discs.tracks]]
title = "高まる胸と食欲"

[[discs.tracks]]
title = "転がる子猫様"

[[discs.tracks]]
title = "殻の中の小鳥"

[[discs.tracks]]
title = "四島に咲く一輪の薔薇"

[[discs.tracks]]
title = "潜む影"

[[discs.tracks]]
title = "笑わない月"

[[discs.tracks]]
title = "コントレイル"

[[discs.tracks]]
title = "一進一退"

[[discs.tracks]]
title = "無限軌道"

[[discs.tracks]]
title = "逆風を超えて"

[[discs.tracks]]
title = "王者の風格"

[[discs.tracks]]
title = "空域の支配者"

[[discs.tracks]]
title = "蒼の彼方へ"

[[discs.tracks]]
title = "世界の変革者"

[[discs.tracks]]
title = "健闘の握手"

[[discs.tracks]]
title = "INFINITE SKY (ピアノアレンジ)"

[[discs.tracks]]
title = "Wings of Courage (ピアノアレンジ1)"

[[discs.tracks]]
title = "Wings of Courage (ピアノアレンジ2)"

[[discs.tracks]]
title = "Wings of Courage -空を超えて- (次回予告Ver.)"

[[discs.tracks]]
title = "Wings of Courage -空を超えて- (Piano Style Instrumental Ver.)"

[[discs]]
catalog = "SPRCS001PCD03"
type = "drama"
artist = "福圓美里・浅倉杏美・山本希望・米澤円・若林直美・近藤孝行・水橋かおり・高森奈津美・儀武ゆう子・興津和幸・水島大宙・清水愛・生天目仁美"

[[discs.tracks]]
title = "激闘!四島対抗ましろうどん早食いトーナメント! #01"

[[discs.tracks]]
title = "激闘!四島対抗ましろうどん早食いトーナメント! #02"

[[discs.tracks]]
title = "激闘!四島対抗ましろうどん早食いトーナメント! #03"

[[discs.tracks]]
title = "激闘!四島対抗ましろうどん早食いトーナメント! #04"

[[discs.tracks]]
title = "激闘!四島対抗ましろうどん早食いトーナメント! #05"

[[discs.tracks]]
title = "激闘!四島対抗ましろうどん早食いトーナメント! #06"

[[discs.tracks]]
title = "激闘!四島対抗ましろうどん早食いトーナメント! #07"

[[discs.tracks]]
title = "激闘!四島対抗ましろうどん早食いトーナメント! #08"

[[discs.tracks]]
title = "激闘!四島対抗ましろうどん早食いトーナメント! #09"
