[album]
album_id = "7a3c53e9-0b75-4937-9c6e-5b0d86ada262"
title = "何もしてあげられない【初回仕様限定盤 Type-B】"
artist = "22/7"
date = 2019-08-21
type = "normal"
catalog = "SRCL-11242"

[[discs]]
catalog = "SRCL-11242"

[[discs.tracks]]
title = "何もしてあげられない"

[[discs.tracks]]
title = "君はMoon"

[[discs.tracks]]
title = "ロマンスの積み木"

[[discs.tracks]]
title = "何もしてあげられない -off vocal ver.-"
type = "instrumental"

[[discs.tracks]]
title = "君はMoon -off vocal ver.-"
type = "instrumental"

[[discs.tracks]]
title = "ロマンスの積み木 -off vocal ver.-"
type = "instrumental"
