[album]
album_id = "b443bbb2-cdbc-4b90-968b-48af6f666a30"
title = "Catch the Moment"
artist = "LiSA"
date = 2017-02-15
type = "normal"
catalog = "SVWC-70233"

[[discs]]
catalog = "SVWC-70233"

[[discs.tracks]]
title = "Catch the Moment"

[[discs.tracks]]
title = "リングアベル"

[[discs.tracks]]
title = "Merry Hurry Berry"
