[album]
album_id = "2e42fb23-5c95-435b-b856-cf1ddd6dea50"
title = "冴えない彼女の育てかた Character Song Collection"
artist = "澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）、加藤恵（安野希世乃）"
date = 2017-06-28
type = "normal"
catalog = "SVWC-70269"
tags = ["冴えない彼女の育てかた:キャラクターイメージソング"]

[[discs]]
catalog = "SVWC-70269"

[[discs.tracks]]
title = "LOVE iLLUSION"

[[discs.tracks]]
title = "Blooming Lily"
artist = "澤村・スペンサー・英梨々（大西沙織）"

[[discs.tracks]]
title = "LOVE iLLUSION"
artist = "澤村・スペンサー・英梨々（大西沙織）"

[[discs.tracks]]
title = "饒舌スキャンダラス"
artist = "霞ヶ丘詩羽（茅野愛衣）"

[[discs.tracks]]
title = "LOVE iLLUSION"
artist = "霞ヶ丘詩羽（茅野愛衣）"

[[discs.tracks]]
title = "M♭"
artist = "加藤恵（安野希世乃）"

[[discs.tracks]]
title = "LOVE iLLUSION"
artist = "加藤恵（安野希世乃）"

[[discs.tracks]]
title = "Cherish you"
artist = "氷堂美智留（矢作紗友里）"

[[discs.tracks]]
title = "Daydreamer"
artist = "氷堂美智留（矢作紗友里）"

[[discs.tracks]]
title = "365色パレット"
artist = "波島出海（赤﨑千夏）"

[[discs.tracks]]
title = "ETERNAL♭"
artist = "加藤恵（安野希世乃）"

[[discs.tracks]]
title = "DOUBLE RAINBOW DREAMS"
artist = "澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）"

[[discs.tracks]]
title = "GLISTENING♭"
artist = "加藤恵（安野希世乃）"
