[album]
album_id = "4d80cfb3-e5f5-4a89-91d5-2b7c26fb95a1"
title = "オリジナル。"
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
date = 2017-02-08
type = "normal"
catalog = "SVWC-70228"

[[discs]]
catalog = "SVWC-70228"

[[discs.tracks]]
title = "オリジナル。"

[[discs.tracks]]
title = "Chip log"

[[discs.tracks]]
title = "オリジナル。Instrumental"
type = "instrumental"

[[discs.tracks]]
title = "Chip log Instrumental"
type = "instrumental"
