[album]
album_id = "a9ebf5bb-ff7f-4885-943f-cf0ee27f3d23"
title = "シルシ"
artist = "LiSA"
date = 2014-12-10
type = "normal"
catalog = "SVWC-70031"

[[discs]]
catalog = "SVWC-70031"

[[discs.tracks]]
title = "シルシ"

[[discs.tracks]]
title = "No More Time Machine"

[[discs.tracks]]
title = "crossing field -English ver.-"
