[album]
album_id = "d5bda85d-854d-4605-9663-ae362a00e7b6"
title = "冴えない彼女の育てかた キャラクターイメージソング 澤村・スペンサー・英梨々"
artist = "澤村・スペンサー・英梨々（大西沙織）"
date = 2014-12-03
type = "normal"
catalog = "SVWC-70037"
tags = ["冴えない彼女の育てかた:キャラクターイメージソング"]

[[discs]]
catalog = "SVWC-70037"

[[discs.tracks]]
title = "Blooming Lily"

[[discs.tracks]]
title = "LOVE iLLUSiON (Eriri Solo Ver.)"

[[discs.tracks]]
title = "Blooming Lily (Off Vocal Ver.)"
type = "instrumental"

[[discs.tracks]]
title = "Message from Eriri"
artist = "澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）、加藤恵（安野希世乃）"
type = "drama"
