[album]
title = "冴えない彼女の育てかた ギャルゲーカバーソングコレクション"
artist = "加藤恵（安野希世乃）、澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）、波島出海（赤﨑千夏）、氷堂美智留（矢作紗友里）、安芸倫也（松岡禎丞）"
date = 2019-09-25
type = "normal"
catalog = "SVWC-70409~10"

[[discs]]
catalog = "SVWC-70409"

[[discs.tracks]]
title = "Leaf ticket"
artist = "加藤恵（安野希世乃）"

[[discs.tracks]]
title = "勇気の神様"
artist = "澤村・スペンサー・英梨々（大西沙織）"

[[discs.tracks]]
title = "you(Vocal)"
artist = "霞ヶ丘詩羽（茅野愛衣）"

[[discs.tracks]]
title = "グリーングリーン"
artist = "氷堂美智留（矢作紗友里）"

[[discs.tracks]]
title = "Heart To Heart"
artist = "波島出海（赤﨑千夏）"

[[discs.tracks]]
title = "季節を抱きしめて"
artist = "加藤恵（安野希世乃）"

[[discs.tracks]]
title = "allegretto ～そらときみ～"
artist = "澤村・スペンサー・英梨々（大西沙織）"

[[discs.tracks]]
title = "届かない恋"
artist = "霞ヶ丘詩羽（茅野愛衣）"

[[discs.tracks]]
title = "Little Busters!"
artist = "氷堂美智留（矢作紗友里）"

[[discs.tracks]]
title = "true my heart"
artist = "波島出海（赤﨑千夏）"

[[discs.tracks]]
title = "檄！帝国華撃団"
artist = "加藤恵（安野希世乃）、澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）、波島出海（赤﨑千夏）、氷堂美智留（矢作紗友里）"

[[discs]]
catalog = "SVWC-70410"

[[discs.tracks]]
title = "ダ・カーポ ～第２ボタンの誓い～"
artist = "加藤恵（安野希世乃）"

[[discs.tracks]]
title = "小さなてのひら"
artist = "加藤恵（安野希世乃）"

[[discs.tracks]]
title = "恋わずらい"
artist = "澤村・スペンサー・英梨々（大西沙織）"

[[discs.tracks]]
title = "Rumbling hearts"
artist = "霞ヶ丘詩羽（茅野愛衣）"

[[discs.tracks]]
title = "LeMU〜遙かなるレムリア大陸〜"
artist = "氷堂美智留（矢作紗友里）"

[[discs.tracks]]
title = "恋愛CHU!"
artist = "波島出海（赤﨑千夏）"

[[discs.tracks]]
title = "未来への咆哮"
artist = "安芸倫也（松岡禎丞）"
