[album]
title = "冴えない彼女の育てかた キャラクターイメージソング 加藤恵"
artist = "加藤恵（安野希世乃）"
date = 2014-12-03
type = "normal"
catalog = "SVWC-70039"

[[discs]]
catalog = "SVWC-70039"

[[discs.tracks]]
title = "M♭"

[[discs.tracks]]
title = "LOVE iLLUSiON (Megumi Solo Ver.)"

[[discs.tracks]]
title = "M♭ (Off Vocal Ver.)"
type = "instrumental"

[[discs.tracks]]
title = "Message from Megumi"
artist = "澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）、加藤恵（安野希世乃）"
type = "drama"
