[album]
album_id = "714e98a8-fa71-4bb1-9f79-8ce30bc24089"
title = "best day,best way"
artist = "LiSA"
date = 2013-04-03
type = "normal"
catalog = "SVWC-7935"

[[discs]]
catalog = "SVWC-7935"

[[discs.tracks]]
title = "best day, best way"

[[discs.tracks]]
title = "I'm a Rock star"

[[discs.tracks]]
title = "シロイトイキ"

[[discs.tracks]]
title = "best day, best way (Instrumental)"
type = "instrumental"
