[album]
album_id = "65b0c8b8-b3fd-4822-a248-6eda1d283f77"
title = "träumerei"
artist = "LiSA"
date = 2013-08-07
type = "normal"
catalog = "SVWC-7948"

[[discs]]
catalog = "SVWC-7948"

[[discs.tracks]]
title = "träumerei"

[[discs.tracks]]
title = "I doubt it"

[[discs.tracks]]
title = "SPiCE"

[[discs.tracks]]
title = "träumerei (Instrumental)"
type = "instrumental"
