[album]
album_id = "286a4c69-873a-4a76-8eb6-9f74d35c6416"
title = "High Free Spirits"
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
date = 2016-05-11
type = "normal"
catalog = "SVWC-70153"

[[discs]]
catalog = "SVWC-70153"

[[discs.tracks]]
title = "High Free Spirits"

[[discs.tracks]]
title = "僕らのシンフォニー"

[[discs.tracks]]
title = "High Free Spirits -TV.ver-"

[[discs.tracks]]
title = "High Free Spirits -Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "僕らのシンフォニー -Instrumental-"
type = "instrumental"
