[album]
album_id = "6f3f81c9-0dfd-464d-b61f-5bbcc4e32ced"
title = "マギアレコード 魔法少女まどか☆マギカ外伝 Music Collection"
artist = "Various Artists"
date = 2018-08-22
type = "absolute"
catalog = "SVWC-70359~60"
tags = ["マギアレコード 魔法少女まどか☆マギカ外伝"]

[[discs]]
catalog = "SVWC-70359"

[[discs.tracks]]
title = "Inception"
artist = "古川亮"

[[discs.tracks]]
title = "Infinite Battle"
artist = "古川亮"

[[discs.tracks]]
title = "First Contact"
artist = "井上泰久"

[[discs.tracks]]
title = "Awaken"
artist = "小澤享平"

[[discs.tracks]]
title = "Place to Hunt"
artist = "井上泰久"

[[discs.tracks]]
title = "Intermediate"
artist = '千葉"naotyu-"直樹'

[[discs.tracks]]
title = "Welcome to Mirrors"
artist = '千葉"naotyu-"直樹'

[[discs.tracks]]
title = "Repeat Days"
artist = "井上泰久"

[[discs.tracks]]
title = "Memories"
artist = "井上泰久"

[[discs.tracks]]
title = "Twilight"
artist = "井上泰久"

[[discs.tracks]]
title = "To Remember"
artist = "小澤享平"

[[discs.tracks]]
title = "Remain"
artist = "小澤享平"

[[discs.tracks]]
title = "Coordinator"
artist = "井上泰久"

[[discs.tracks]]
title = "Lost Tension"
artist = "小澤享平"

[[discs.tracks]]
title = "Anxiety"
artist = "井上泰久"

[[discs.tracks]]
title = "Touch One's Heart"
artist = "小澤享平"

[[discs.tracks]]
title = "Be Terrified"
artist = "古川亮"

[[discs.tracks]]
title = "Creation"
artist = "井上泰久"

[[discs.tracks]]
title = "Wings of Magius"
artist = "井上泰久"

[[discs.tracks]]
title = "Full Moon"
artist = "井上泰久"

[[discs.tracks]]
title = "The Imaginator"
artist = "井上泰久"

[[discs.tracks]]
title = "Uwasa-san"
artist = "井上泰久"

[[discs.tracks]]
title = "The Lecture"
artist = "井上泰久"

[[discs.tracks]]
title = "Into The Territory"
artist = "小澤享平"

[[discs.tracks]]
title = "Hotel Fenthope"
artist = "小澤享平"

[[discs.tracks]]
title = "Thought of You"
artist = "小澤享平"

[[discs.tracks]]
title = "Battle Fields"
artist = "古川亮"

[[discs.tracks]]
title = "Initiation Battle"
artist = "井上泰久"

[[discs.tracks]]
title = "The Crow"
artist = "斎木達彦"

[[discs.tracks]]
title = "Magical Artist"
artist = "小澤享平"

[[discs.tracks]]
title = "Calculated Future"
artist = "井上泰久"

[[discs.tracks]]
title = "Last Dungeon"
artist = "古川亮"

[[discs.tracks]]
title = "Reunion"
artist = "古川亮"

[[discs.tracks]]
title = "The Other Side"
artist = "井上泰久"

[[discs.tracks]]
title = "Battle Bell"
artist = '千葉"naotyu-"直樹'

[[discs.tracks]]
title = "Depth in the Mirror"
artist = '千葉"naotyu-"直樹'

[[discs.tracks]]
title = "One Day She Meets"
artist = '千葉"naotyu-"直樹'

[[discs.tracks]]
title = "Sunshine of the Mind"
artist = "小澤享平"

[[discs.tracks]]
title = "Day of Rest"
artist = "井上泰久"

[[discs.tracks]]
title = "Plot"
artist = "古川亮"

[[discs.tracks]]
title = "Farewell"
artist = "斎木達彦"

[[discs.tracks]]
title = "Complex Home"
artist = "小澤享平"

[[discs.tracks]]
title = "Painful Memories"
artist = '千葉"naotyu-"直樹'

[[discs.tracks]]
title = "Inerasable"
artist = "小澤享平"

[[discs.tracks]]
title = "This Morning"
artist = "斎木達彦"

[[discs.tracks]]
title = "There is"
artist = "小澤享平"

[[discs.tracks]]
title = "Little Trick"
artist = "小澤享平"

[[discs.tracks]]
title = "Hot Summer Day"
artist = "小澤享平"

[[discs.tracks]]
title = "かかわり"
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
type = "normal"

[[discs]]
catalog = "SVWC-70360"
type = "drama"

[[discs.tracks]]
title = "ミニドラマ 「うん、水徳湯に行こう!」"

[[discs.tracks]]
title = "うん、水徳湯に行こう! Chapter2"

[[discs.tracks]]
title = "うん、水徳湯に行こう! Chapter3"

[[discs.tracks]]
title = "うん、水徳湯に行こう! Chapter4"
