[album]
title = "ef - a fairy tale of the two. Original Soundtrack. Alato"
artist = "天門、柳英一朗"
date = 2008-12-28
type = "absolute"
catalog = "SW-049"

[[discs]]
catalog = "SW-049-01"

[[discs.tracks]]
title = "Two, Only Two."

[[discs.tracks]]
title = "eternal feather"
artist = "原田ひとみ"
type = "normal"

[[discs.tracks]]
title = "Snowly night."

[[discs.tracks]]
title = "Church."

[[discs.tracks]]
title = "Mysteric position."

[[discs.tracks]]
title = "Dreaming Dreaming."

[[discs.tracks]]
title = "Over night."

[[discs.tracks]]
title = "A moon filled sky."

[[discs.tracks]]
title = "Imagination."

[[discs.tracks]]
title = "Morning air."

[[discs.tracks]]
title = "Early childhood."

[[discs.tracks]]
title = "Junior girl."

[[discs.tracks]]
title = "Bad friend."

[[discs.tracks]]
title = "Free and easy."

[[discs.tracks]]
title = "Twilight."

[[discs.tracks]]
title = "A wish."

[[discs.tracks]]
title = "Sorrowful feather."

[[discs.tracks]]
title = "Silent talk."

[[discs.tracks]]
title = "Eye level."

[[discs.tracks]]
title = "Hit Hit Hit."

[[discs.tracks]]
title = "Boisterous."

[[discs.tracks]]
title = "Hand with Hand."

[[discs.tracks]]
title = "Walk around."

[[discs.tracks]]
title = "Heart to Heart."

[[discs.tracks]]
title = "Frailty feather."

[[discs.tracks]]
title = "Tear."

[[discs.tracks]]
title = "Start again."

[[discs.tracks]]
title = "Warm color."

[[discs.tracks]]
title = "Genuine."

[[discs]]
catalog = "SW-049-02"

[[discs.tracks]]
title = "Good-bye my friend."

[[discs.tracks]]
title = "Adult room."

[[discs.tracks]]
title = "Stroll of puppy."

[[discs.tracks]]
title = "Angel's smile."

[[discs.tracks]]
title = "Happy summer vacation"

[[discs.tracks]]
title = "Soft ice cream !!"

[[discs.tracks]]
title = "Towering cloud in summer."

[[discs.tracks]]
title = "Conversation like aquarium."

[[discs.tracks]]
title = "Giraffe's feelings."

[[discs.tracks]]
title = "The last performance."

[[discs.tracks]]
title = "emotinal flutter"
artist = "原田ひとみ"
type = "normal"

[[discs.tracks]]
title = "Girl's mask."

[[discs.tracks]]
title = "After school in summer."

[[discs.tracks]]
title = "Art and Art."

[[discs.tracks]]
title = "It dances with the note."

[[discs.tracks]]
title = "Nostalgic spectacle."

[[discs.tracks]]
title = "Time spent with friends."

[[discs.tracks]]
title = "Word that doesn't reach."

[[discs.tracks]]
title = "The beautiful one is here."

[[discs.tracks]]
title = "The black truth."

[[discs.tracks]]
title = "Revenge in the past."

[[discs.tracks]]
title = "It is solved from the chain."

[[discs.tracks]]
title = "Ringleader."

[[discs.tracks]]
title = "Myself, another."

[[discs.tracks]]
title = "The white truth."

[[discs]]
catalog = "SW-049-03"

[[discs.tracks]]
title = "Clam night of summer."

[[discs.tracks]]
title = "New winter."

[[discs.tracks]]
title = "Winter when summer is expected."

[[discs.tracks]]
title = "Regained time."

[[discs.tracks]]
title = "The girl who doesn't smile."

[[discs.tracks]]
title = "To meet you someday."

[[discs.tracks]]
title = "The sweet world."

[[discs.tracks]]
title = "Angel's stairs."

[[discs.tracks]]
title = "Baby-sister song."

[[discs.tracks]]
title = "Will."

[[discs.tracks]]
title = "Imperfect answer."

[[discs.tracks]]
title = "First step that realizes dream."

[[discs.tracks]]
title = "A moon filled sky in Vn."

[[discs.tracks]]
title = "Secret in the world."

[[discs.tracks]]
title = "Christmas of summer."

[[discs.tracks]]
title = "Stille Nache, heilige Nacht feat.S.Kuze."

[[discs.tracks]]
title = "Bouquet."

[[discs.tracks]]
title = "ever forever"
artist = "原田ひとみ"
type = "normal"

[[discs.tracks]]
title = "eternal feather (without vocals)"
type = "instrumental"

[[discs.tracks]]
title = "emotinal flutter (without vocals)"
type = "instrumental"

[[discs.tracks]]
title = "ever forever (without vocals)"
type = "instrumental"
