[album]
album_id = "dd0a6030-0ab8-49b7-a262-e4be3890f25e"
title = "無職転生 ～異世界行ったら本気だす～ Original Soundtrack 2 Special Edition"
artist = "藤澤慶昌"
date = 2022-01-19
type = "absolute"
catalog = "TBR31096D-2"
tags = ["アニメ「無職転生 ～異世界行ったら本気だす～」", "OST"]

[[discs]]
catalog = "TBR31096D-2"

[[discs.tracks]]
title = "心の奥底"

[[discs.tracks]]
title = "もう大丈夫"

[[discs.tracks]]
title = "格式ある家系"

[[discs.tracks]]
title = "計略"

[[discs.tracks]]
title = "目的"

[[discs.tracks]]
title = "したごころ"

[[discs.tracks]]
title = "陽気な日"

[[discs.tracks]]
title = "額の目"

[[discs.tracks]]
title = "知っていること"

[[discs.tracks]]
title = "たくらみ"

[[discs.tracks]]
title = "アジト"

[[discs.tracks]]
title = "虚無の世界"

[[discs.tracks]]
title = "アイシャ"

[[discs.tracks]]
title = "初めての海"

[[discs.tracks]]
title = "魔界大帝キシリカ・キシリス!?"

[[discs.tracks]]
title = "ギレーヌのこと"

[[discs.tracks]]
title = "信頼を得る為に"

[[discs.tracks]]
title = "ウェンポート"

[[discs.tracks]]
title = "密輸組織"

[[discs.tracks]]
title = "作戦会議"

[[discs.tracks]]
title = "笑顔の力"

[[discs.tracks]]
title = "快適な牢屋"

[[discs.tracks]]
title = "先輩と新入"

[[discs.tracks]]
title = "ドルディア族"

[[discs.tracks]]
title = "共闘"

[[discs.tracks]]
title = "再会"

[[discs.tracks]]
title = "冒険者"

[[discs.tracks]]
title = "慰め"

[[discs.tracks]]
title = "待ってる"

[[discs.tracks]]
title = "神聖な世界"

[[discs.tracks]]
title = "シーローン王宮"

[[discs.tracks]]
title = "秘密の作戦"

[[discs.tracks]]
title = "まさか!?"

[[discs.tracks]]
title = "旅人の唄 -EP17 Inst Ver.-"

[[discs.tracks]]
title = "ロキシーへの想い"

[[discs.tracks]]
title = "ザノバの力"

[[discs.tracks]]
title = "圧倒的力との遭遇"
