[album]
album_id = "0f9bd13e-34cf-459a-8d93-1aa33e6eeb98"
title = "LONELY ALICE"
artist = "Pyxis（豊田萌絵、伊藤美来）"
date = 2018-05-23
type = "normal"
catalog = "TECI-619"

[[discs]]
catalog = "TECI-619"

[[discs.tracks]]
title = "LONELY ALICE"

[[discs.tracks]]
title = "流れ星ハーモニー"

[[discs.tracks]]
title = "LONELY ALICE（Instrumental）"
type = "instrumental"

[[discs.tracks]]
title = "流れ星ハーモニー（Instrumental）"
type = "instrumental"
