[album]
album_id = "76293f2a-89f9-4ade-9c1e-e1e7020e9299"
title = "恋せよみんな、ハイ！"
artist = "Pyxis（豊田萌絵、伊藤美来）"
date = 2019-06-05
type = "normal"
catalog = "TECI-676"

[[discs]]
catalog = "TECI-676"

[[discs.tracks]]
title = "恋せよみんな、ハイ！"

[[discs.tracks]]
title = "Pyxisランド"
