[album]
album_id = "e4582bcd-c21a-4572-b677-128951f31071"
title = "You are a ghost, I am a ghost 〜劇場のゴースト〜"
artist = "スタァライト九九組（愛城華恋（小山百代）、神楽ひかり（三森すずこ）、天堂真矢（富田麻帆）、星見純那（佐藤日向）、露崎まひる（岩田陽葵）、大場なな（小泉萌香）、西條クロディーヌ（相羽あいな）、石動双葉（生田輝）、花柳香子（伊藤彩沙））"
date = 2018-12-26
type = "normal"
catalog = "TGCS-10948"

[[discs]]
catalog = "TGCS-10948"

[[discs.tracks]]
title = "You are a ghost, I am a ghost 〜劇場のゴースト〜"

[[discs.tracks]]
title = "You are a ghost, I am a ghost 〜劇場のゴースト〜(Instrumental)"
type = "instrumental"
