[album]
title = "恋は太陽 ~CIRCUS!~"
artist = "スタァライト九九組（愛城華恋（小山百代）、神楽ひかり（三森すずこ）、天堂真矢（富田麻帆）、星見純那（佐藤日向）、露崎まひる（岩田陽葵）、大場なな（小泉萌香）、西條クロディーヌ（相羽あいな）、石動双葉（生田輝）、花柳香子（伊藤彩沙））"
date = 2019-02-27
type = "normal"
catalog = "TGCS-10949"

[[discs]]
catalog = "TGCS-10949"

[[discs.tracks]]
title = "恋は太陽 ~CIRCUS!~"

[[discs.tracks]]
title = "恋は太陽 ~CIRCUS!~(Instrumental)"
type = "instrumental"
