[album]
title = "H-A-J-I-M-A-L-B-U-M-!!"
artist = "Tokyo 7th シスターズ"
date = 2015-05-20
type = "normal"
catalog = "TS-0003"
tags = ["Tokyo 7th シスターズ"]

[[discs]]
catalog = "TS-0003-01"

[[discs.tracks]]
title = "H-A-J-I-M-A-R-I-U-T-A-!!"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "Cocoro Magical"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "KILL☆ER☆TUNE☆R"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "Girls Talk!!"
artist = "NI+CORA（天堂寺ムスビ（高田憂希）、アレサンドラ・スース（大西沙織））"

[[discs.tracks]]
title = "SAKURA"
artist = "WITCH NUMBER 4（春日部ハル（篠田みなみ）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織））"

[[discs.tracks]]
title = "お願い☆My Boy"
artist = "SiSH（臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏））"

[[discs.tracks]]
title = "Clover×Clover"
artist = "サンボンリボン（晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "ワタシ・愛・forU!!"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "Hello...my friend"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "B.A.A.B."
artist = "KARAKURI（空栗ヒトハ（秋奈）、空栗フタバ（秋奈））"

[[discs.tracks]]
title = "Sparkle☆Time!!"
artist = "セブンスシスターズ（七咲ニコル（水瀬いのり）、羽生田ミト（渕上舞）、御園尾マナ（前田玲奈）、寿クルト（黒瀬ゆうこ）、若王子ルイ（川崎芽衣子）、遊佐メモル（辻あゆみ））"

[[discs]]
catalog = "TS-0003-02"

[[discs.tracks]]
title = "UPDATING??SISTERS!!"
artist = "六咲コニー（水瀬いのり）、777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"
type = "drama"
