[album]
album_id = "eacafa4f-2d18-4453-8501-246ead71017e"
title = "The Sunshower"
edition = "へやキャン△盤"
artist = "亜咲花"
date = 2020-01-29
type = "normal"
catalog = "USSW-0230"
tags = ["へやキャン△"]

[[discs]]
catalog = "USSW-0230"

[[discs.tracks]]
title = "オリジナルミニドラマ「AFTERSCHOOL」"
artist = "各務原なでしこ（花守ゆみり）、鳥羽美波（伊藤静）"
type = "drama"

[[discs.tracks]]
title = "The Sunshower"

[[discs.tracks]]
title = "Isn't It Fun?"

[[discs.tracks]]
title = "1000miles"

[[discs.tracks]]
title = "The Sunshower -off vocal-"
type = "instrumental"

[[discs.tracks]]
title = "Isn't It Fun? -off vocal-"
type = "instrumental"

[[discs.tracks]]
title = "1000miles -off vocal-"
type = "instrumental"
