[album]
album_id = "60a7329d-f455-45a4-b660-6b24b7014996"
title = "TVアニメ「五等分の花嫁」オリジナル・サウンドトラック"
artist = "田渕夏海、中村巴奈重、櫻井美希"
date = 2019-03-06
type = "absolute"
catalog = "UZCL-2153"

[[discs]]
catalog = "UZCL-2153"

[[discs.tracks]]
title = "五等分の花嫁"

[[discs.tracks]]
title = "五つ子のテーマ"

[[discs.tracks]]
title = "一花のテーマ"

[[discs.tracks]]
title = "二乃のテーマ"

[[discs.tracks]]
title = "三玖のテーマ"

[[discs.tracks]]
title = "四葉のテーマ"

[[discs.tracks]]
title = "五月のテーマ"

[[discs.tracks]]
title = "らいはのテーマ"

[[discs.tracks]]
title = "風太郎のテーマ"

[[discs.tracks]]
title = "五つ子の父のテーマ"

[[discs.tracks]]
title = "五つ子のテーマ-赤点必須!-"

[[discs.tracks]]
title = "振り回す五つ子"

[[discs.tracks]]
title = "五等分の花嫁-日常-"

[[discs.tracks]]
title = "学園生活"

[[discs.tracks]]
title = "止まらない減らず口"

[[discs.tracks]]
title = "意味深ですね"

[[discs.tracks]]
title = "ヤバい空気…?"

[[discs.tracks]]
title = "誘惑サスペンス"

[[discs.tracks]]
title = "健気さ"

[[discs.tracks]]
title = "五つ子のテーマ-日常-"

[[discs.tracks]]
title = "悩みごと"

[[discs.tracks]]
title = "お母さんの思い出"

[[discs.tracks]]
title = "っえ…!!"

[[discs.tracks]]
title = "ムカムカ"

[[discs.tracks]]
title = "小悪魔の罠"

[[discs.tracks]]
title = "みんなの決意"

[[discs.tracks]]
title = "一致団結"

[[discs.tracks]]
title = "センチメンタル"

[[discs.tracks]]
title = "恋のボルテージアップ!"

[[discs.tracks]]
title = "ド・ギ・マ・ギ"

[[discs.tracks]]
title = "揺れる心"

[[discs.tracks]]
title = "期待と不安"

[[discs.tracks]]
title = "妄想乙女"

[[discs.tracks]]
title = "もやもや風太郎"

[[discs.tracks]]
title = "振り回される風太郎"

[[discs.tracks]]
title = "キンキュウジタイ!?"

[[discs.tracks]]
title = "虫の知らせ"

[[discs.tracks]]
title = "チェイス!"

[[discs.tracks]]
title = "遅刻!!??"

[[discs.tracks]]
title = "肝試し"

[[discs.tracks]]
title = "武将戦国Quiz"

[[discs.tracks]]
title = "お料理対決!!"

[[discs.tracks]]
title = "五つ子のテーマ-家族愛-"

[[discs.tracks]]
title = "試験開始"

[[discs.tracks]]
title = "だましだまされ"

[[discs.tracks]]
title = "変なヤツ..."

[[discs.tracks]]
title = "NEO結婚行進曲"
