[album]
album_id = "2174d0bf-b5c7-4c1b-a0b3-94fb0c6e8570"
title = "TVアニメ「安達としまむら」オリジナル・サウンドトラック"
artist = "田渕夏海、中村巴奈重、櫻井美希"
date = 2020-12-09
type = "absolute"
catalog = "UZCL-2200"

[[discs]]
catalog = "UZCL-2200"

[[discs.tracks]]
title = "居場所"
artist = "中村巴奈重"

[[discs.tracks]]
title = "昼休み"
artist = "櫻井美希"

[[discs.tracks]]
title = "君の隣"
artist = "田渕夏海"

[[discs.tracks]]
title = "小さな高揚"
artist = "櫻井美希"

[[discs.tracks]]
title = "人付き合いとは"
artist = "田渕夏海"

[[discs.tracks]]
title = "お出かけ"
artist = "中村巴奈重"

[[discs.tracks]]
title = "漆黒の世界"
artist = "中村巴奈重"

[[discs.tracks]]
title = "未来人"
artist = "櫻井美希"

[[discs.tracks]]
title = "未知のコミュニケーション"
artist = "櫻井美希"

[[discs.tracks]]
title = "何気ない毎日"
artist = "中村巴奈重"

[[discs.tracks]]
title = "不真面目な私たち"
artist = "田渕夏海"

[[discs.tracks]]
title = "恥じらいと妄想"
artist = "中村巴奈重"

[[discs.tracks]]
title = "抑えたい気持ち"
artist = "櫻井美希"

[[discs.tracks]]
title = "歯がゆい想い"
artist = "田渕夏海"

[[discs.tracks]]
title = "もしも…のどきどき"
artist = "中村巴奈重"

[[discs.tracks]]
title = "一緒に帰ろう"
artist = "田渕夏海"

[[discs.tracks]]
title = "妹"
artist = "田渕夏海"

[[discs.tracks]]
title = "見られた…"
artist = "櫻井美希"

[[discs.tracks]]
title = "私の一番とあなたの一番"
artist = "田渕夏海"

[[discs.tracks]]
title = "ともだち"
artist = "櫻井美希"

[[discs.tracks]]
title = "距離感"
artist = "櫻井美希"

[[discs.tracks]]
title = "ほどけた心"
artist = "中村巴奈重"

[[discs.tracks]]
title = "弾ける想い"
artist = "櫻井美希"

[[discs.tracks]]
title = "現実"
artist = "櫻井美希"

[[discs.tracks]]
title = "軟弱だぞ"
artist = "田渕夏海"

[[discs.tracks]]
title = "悪いことの共有"
artist = "田渕夏海"

[[discs.tracks]]
title = "拗ねる"
artist = "中村巴奈重"

[[discs.tracks]]
title = "すれ違う気持ち"
artist = "中村巴奈重"

[[discs.tracks]]
title = "どぎまぎ"
artist = "櫻井美希"

[[discs.tracks]]
title = "仲良くなりたい"
artist = "田渕夏海"

[[discs.tracks]]
title = "安心感"
artist = "櫻井美希"

[[discs.tracks]]
title = "これから"
artist = "中村巴奈重"

[[discs.tracks]]
title = "今までも"
artist = "櫻井美希"

[[discs.tracks]]
title = "伝えよう"
artist = "中村巴奈重"

[[discs.tracks]]
title = "想いを抱きしめ"
artist = "田渕夏海"
