[album]
album_id = "5cd7f9e0-b48a-4907-b4e4-5bf2f1d0d24f"
title = "『Tokyo 7th シスターズ -僕らは青空になる-』 オリジナルサウンドトラック"
artist = "Tokyo 7th シスターズ"
date = 2021-02-24
type = "absolute"
catalog = "VICL-65474"
tags = ["Tokyo 7th シスターズ"]

[[discs]]
catalog = "VICL-65474"

[[discs.tracks]]
title = "ようこそナナスタへ!!"

[[discs.tracks]]
title = "Wake up SISTERS!!"

[[discs.tracks]]
title = "Don't stop SISTERS!!!"

[[discs.tracks]]
title = "イン・トラブル"

[[discs.tracks]]
title = "和気あいあい"

[[discs.tracks]]
title = "Tokyo-7th"

[[discs.tracks]]
title = "八角スタジオ"

[[discs.tracks]]
title = "Situation BAD"

[[discs.tracks]]
title = "時代の流れ"

[[discs.tracks]]
title = "埃と栄光"

[[discs.tracks]]
title = "夕陽の決意"

[[discs.tracks]]
title = "誰かの背中"

[[discs.tracks]]
title = "まなざし"

[[discs.tracks]]
title = "Destructive"

[[discs.tracks]]
title = "雨中の覚悟"

[[discs.tracks]]
title = "審判のとき"

[[discs.tracks]]
title = "嘘と敗北"

[[discs.tracks]]
title = "アイドルはアイドルじゃなくてもいい"

[[discs.tracks]]
title = "光、集まる"

[[discs.tracks]]
title = "Outro -to be the Blue Sky-"

[[discs.tracks]]
title = "ハッピーエンド (Ver.AO)"

[[discs.tracks]]
title = "Departures -あしたの歌- (Movie Edit)"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"
type = "normal"
