[album]
title = "スタートライン／STAY☆GOLD"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"
date = 2017-08-30
type = "normal"
catalog = "VIZL-1192"
tags = ["777☆SISTERS"]

[[discs]]
catalog = "VIZL-1192"

[[discs.tracks]]
title = "スタートライン"

[[discs.tracks]]
title = "STAY☆GOLD"

[[discs.tracks]]
title = "スタートライン -OFF VOCAL-"
type = "instrumental"

[[discs.tracks]]
title = "STAY☆GOLD -OFF VOCAL-"
type = "instrumental"
