[album]
album_id = "5c1952b7-9c79-43fd-9fb3-df74d911c669"
title = "THE STRAIGHT LIGHT"
artist = "Tokyo 7th シスターズ"
date = 2018-07-04
type = "normal"
catalog = "VIZL-1396"
tags = ["Tokyo 7th シスターズ"]

[[discs]]
catalog = "VIZL-1396-01"

[[discs.tracks]]
title = "The Straight Light"
type = "absolute"

[[discs.tracks]]
title = "スタートライン"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "星屑☆シーカー"
artist = "WITCH NUMBER 4（春日部ハル（篠田みなみ）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織））"

[[discs.tracks]]
title = "プレシャス・セトラ"
artist = "SiSH（臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏））"

[[discs.tracks]]
title = "CHECK’MATE"
artist = "NI+CORA（天堂寺ムスビ（高田憂希）、アレサンドラ・スース（大西沙織））"

[[discs.tracks]]
title = "14歳のサマーソーダ"
artist = "サンボンリボン（晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "SHAKE!!～フリフリしちゃえ～"
artist = "はる☆ジカ(ちいさな)（春日部ハル（篠田みなみ）、晴海カジカ（高井舞香））"

[[discs.tracks]]
title = "タンポポ"
artist = "Le☆S☆Ca（上杉・ウエバス・キョーコ（吉井彩実）、荒木レナ（藤田茜）、西園ホノカ（植田ひかる））"

[[discs.tracks]]
title = "トワイライト"
artist = "Le☆S☆Ca（上杉・ウエバス・キョーコ（吉井彩実）、荒木レナ（藤田茜）、西園ホノカ（植田ひかる））"

[[discs.tracks]]
title = "ひまわりのストーリー"
artist = "Le☆S☆Ca（上杉・ウエバス・キョーコ（吉井彩実）、荒木レナ（藤田茜）、西園ホノカ（植田ひかる））"

[[discs.tracks]]
title = "STAY☆GOLD"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "Dear Straight Lights"
type = "absolute"

[[discs.tracks]]
title = "ハルカゼ～You were here～"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs]]
catalog = "VIZL-1396-02"

[[discs.tracks]]
title = "PUNCH’D RANKER"
artist = "セブンスシスターズ（七咲ニコル（水瀬いのり）、羽生田ミト（渕上舞）、御園尾マナ（前田玲奈）、寿クルト（黒瀬ゆうこ）、若王子ルイ（川崎芽衣子）、遊佐メモル（辻あゆみ））"

[[discs.tracks]]
title = "TRIGGER"
artist = "The QUEEN of PURPLE（越前ムラサキ（野村麻衣子）、瀬戸ファーブ（広瀬ゆうき）、屋ユメノ（山本彩乃）、三森マツリ（巽悠衣子））"

[[discs.tracks]]
title = "Fire and Rose"
artist = "The QUEEN of PURPLE（越前ムラサキ（野村麻衣子）、瀬戸ファーブ（広瀬ゆうき）、屋ユメノ（山本彩乃）、三森マツリ（巽悠衣子））"

[[discs.tracks]]
title = "Lucky☆Lucky"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "Lucky☆Lucky (EMO edit)"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "Lucky☆Lucky (HINA edit)"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "Winning Day"
artist = "KARAKURI（空栗ヒトハ（秋奈）、空栗フタバ（秋奈））"

[[discs.tracks]]
title = "WORLD’S END"
artist = "セブンスシスターズ（七咲ニコル（水瀬いのり）、羽生田ミト（渕上舞）、御園尾マナ（前田玲奈）、寿クルト（黒瀬ゆうこ）、若王子ルイ（川崎芽衣子）、遊佐メモル（辻あゆみ））"

[[discs]]
title = "THE STRAIGHT LIGHT - t7s オリジナルサウンドトラック 1.5「-FORGET ME NOT-」"
catalog = "VIZL-1396-03"
type = "absolute"

[[discs.tracks]]
title = "喧々諤々（Episode Event:1）"

[[discs.tracks]]
title = "平穏無事（Episode Event:2）"

[[discs.tracks]]
title = "CLAP HANDS SAY YES（New Scout）"

[[discs.tracks]]
title = "Round and Around（Raid Event OP）"

[[discs.tracks]]
title = "BRIGHTNESS（Performance Match Battle）"

[[discs.tracks]]
title = "ON THE EDGE（Performance Match OP）"

[[discs.tracks]]
title = "STEP☆UP 7th!!"

[[discs.tracks]]
title = "それぞれの現実"

[[discs.tracks]]
title = "沈んだ太陽"

[[discs.tracks]]
title = "きっと忘れない～FORGET ME NOT～"

[[discs]]
catalog = "VIZL-1396-04"
type = "instrumental"

[[discs.tracks]]
title = "スタートライン -OFF VOCAL-"
artist = "777☆SISTERS"

[[discs.tracks]]
title = "星屑☆シーカー -OFF VOCAL-"
artist = "WITCH NUMBER 4"

[[discs.tracks]]
title = "プレシャス・セトラ -OFF VOCAL-"
artist = "SiSH"

[[discs.tracks]]
title = "CHECK'MATE -OFF VOCAL-"
artist = "NI+CORA"

[[discs.tracks]]
title = "14歳のサマーソーダ -OFF VOCAL-"
artist = "サンボンリボン"

[[discs.tracks]]
title = "SHAKE!!～フリフリしちゃえ～ -OFF VOCAL-"
artist = "はる☆ジカ (ちいさな)"

[[discs.tracks]]
title = "タンポポ -OFF VOCAL-"
artist = "Le☆S☆Ca"

[[discs.tracks]]
title = "トワイライト -OFF VOCAL-"
artist = "Le☆S☆Ca"

[[discs.tracks]]
title = "ひまわりのストーリー -OFF VOCAL-"
artist = "Le☆S☆Ca"

[[discs.tracks]]
title = "STAY☆GOLD -OFF VOCAL-"
artist = "777☆SISTERS"

[[discs.tracks]]
title = "ハルカゼ～You were here～ -OFF VOCAL-"
artist = "777☆SISTERS"

[[discs.tracks]]
title = "PUNCH'D RANKER -OFF VOCAL-"
artist = "セブンスシスターズ"

[[discs.tracks]]
title = "TRIGGER -OFF VOCAL-"
artist = "The QUEEN of PURPLE"

[[discs.tracks]]
title = "Fire and Rose -OFF VOCAL-"
artist = "The QUEEN of PURPLE"

[[discs.tracks]]
title = "Lucky☆Lucky -OFF VOCAL-"
artist = "4U"

[[discs.tracks]]
title = "Winning Day -OFF VOCAL-"
artist = "KARAKURI"

[[discs.tracks]]
title = "WORLD'S END -OFF VOCAL-"
artist = "セブンスシスターズ"
