[album]
album_id = "164d4c14-ea32-44ad-9004-205b202e9e47"
title = "WORLD'S END"
artist = "セブンスシスターズ（七咲ニコル（水瀬いのり）、羽生田ミト（渕上舞）、御園尾マナ（前田玲奈）、寿クルト（黒瀬ゆうこ）、若王子ルイ（川崎芽衣子）、遊佐メモル（辻あゆみ））"
date = 2017-07-26
type = "normal"
catalog = "VIZL-1191"
tags = ["セブンスシスターズ"]

[[discs]]
catalog = "VIZL-1191"

[[discs.tracks]]
title = "WORLD'S END"

[[discs.tracks]]
title = "PUNCH'D RANKER"

[[discs.tracks]]
title = "WORLD'S END-OFF VOCAL-"
type = "instrumental"

[[discs.tracks]]
title = "PUNCH'D RANKER-OFF VOCAL-"
type = "instrumental"
