[album]
title = "Are You Ready 7th-TYPES??"
artist = "Tokyo 7th シスターズ"
date = 2016-06-29
type = "normal"
catalog = "VIZL-988"
tags = ["Tokyo 7th シスターズ"]

[[discs]]
catalog = "VIZL-988-01"

[[discs.tracks]]
title = "Intro ～Are You Ready 7th-TYPES??～"
type = "absolute"

[[discs.tracks]]
title = "SEVENTH HAVEN"
artist = "セブンスシスターズ（七咲ニコル（水瀬いのり）、羽生田ミト（渕上舞）、御園尾マナ（前田玲奈）、寿クルト（黒瀬ゆうこ）、若王子ルイ（川崎芽衣子）、遊佐メモル（辻あゆみ））"

[[discs.tracks]]
title = "FALLING DOWN"
artist = "セブンスシスターズ（七咲ニコル（水瀬いのり）、羽生田ミト（渕上舞）、御園尾マナ（前田玲奈）、寿クルト（黒瀬ゆうこ）、若王子ルイ（川崎芽衣子）、遊佐メモル（辻あゆみ））"

[[discs.tracks]]
title = "-Zero"
artist = "KARAKURI（空栗ヒトハ（秋奈）、空栗フタバ（秋奈））"

[[discs.tracks]]
title = "TREAT OR TREAT?"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "TREAT OR TREAT? (EMO Edit)"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "TREAT OR TREAT? (HINA Edit)"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "Is This it, Sisters!?"
type = "drama"

[[discs]]
catalog = "VIZL-988-02"

[[discs.tracks]]
title = "Intro -to be the Blue Sky...-"
type = "absolute"

[[discs.tracks]]
title = "僕らは青空になる"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "FUNBARE☆RUNNER"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "ラバ×ラバ"
artist = "WITCH NUMBER 4（春日部ハル（篠田みなみ）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織））"

[[discs.tracks]]
title = "さよならレイニーレイディ"
artist = "SiSH（臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏））"

[[discs.tracks]]
title = "You Can't Win"
artist = "NI+CORA（天堂寺ムスビ（高田憂希）、アレサンドラ・スース（大西沙織））"

[[discs.tracks]]
title = "セカイのヒミツ"
artist = "サンボンリボン（晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "YELLOW"
artist = "Le☆S☆Ca（上杉・ウエバス・キョーコ（吉井彩実）、荒木レナ（藤田茜）、西園ホノカ（植田ひかる））"

[[discs.tracks]]
title = "Behind Moon"
artist = "Le☆S☆Ca（上杉・ウエバス・キョーコ（吉井彩実）、荒木レナ（藤田茜）、西園ホノカ（植田ひかる））"

[[discs.tracks]]
title = "ハネ☆る!!"
artist = "はる☆ジカ(ちいさな)（春日部ハル（篠田みなみ）、晴海カジカ（高井舞香））"

[[discs.tracks]]
title = 'Snow in "I love you"'
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "I need you ～「僕らは青空になる」 Original Piano Arrange～"
type = "absolute"

[[discs.tracks]]
title = "またあした"
artist = "春日部ハル（篠田みなみ）"

[[discs]]
catalog = "VIZL-988-03"

[[discs.tracks]]
title = "Intro -HAJIMALI-"
type = "absolute"

[[discs.tracks]]
title = "H-A-J-I-M-A-R-I-U-T-A-!!"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "Sparkle☆Time!!"
artist = "セブンスシスターズ（七咲ニコル（水瀬いのり）、羽生田ミト（渕上舞）、御園尾マナ（前田玲奈）、寿クルト（黒瀬ゆうこ）、若王子ルイ（川崎芽衣子）、遊佐メモル（辻あゆみ））"

[[discs.tracks]]
title = "オ・モ・イ アプローチ"
artist = "NI+CORA（天堂寺ムスビ（高田憂希）、アレサンドラ・スース（大西沙織））"

[[discs.tracks]]
title = "Girls Talk!!"
artist = "NI+CORA（天堂寺ムスビ（高田憂希）、アレサンドラ・スース（大西沙織））"

[[discs.tracks]]
title = "AOZORA TRAIN"
artist = "SiSH（臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏））"

[[discs.tracks]]
title = "お願い☆My Boy"
artist = "SiSH（臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏））"

[[discs.tracks]]
title = "ワタシ・愛・forU!!"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "Hello...my friend"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "Clover×Clover"
artist = "サンボンリボン（晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "たいくつりぼん"
artist = "サンボンリボン（晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "B.A.A.B."
artist = "KARAKURI（空栗ヒトハ（秋奈）、空栗フタバ（秋奈））"

[[discs.tracks]]
title = "PRIZM♪RIZM"
artist = "WITCH NUMBER 4（春日部ハル（篠田みなみ）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織））"

[[discs.tracks]]
title = "SAKURA"
artist = "WITCH NUMBER 4（春日部ハル（篠田みなみ）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織））"

[[discs.tracks]]
title = "Cocoro Magical"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "KILL☆ER☆TUNE☆R"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "Message from t7s –星の瞬き-(MC)"
type = "vocal"

[[discs.tracks]]
title = "Star☆Glitter"

[[discs]]
catalog = "VIZL-988-04"
type = "instrumental"

[[discs.tracks]]
title = "SEVENTH HAVEN -Off Vocal-"
artist = "セブンスシスターズ"

[[discs.tracks]]
title = "FALLING DOWN -Off Vocal-"
artist = "セブンスシスターズ"

[[discs.tracks]]
title = "-Zero -Off Vocal-"
artist = "KARAKURI"

[[discs.tracks]]
title = "TREAT OR TREAT? -Off Vocal-"
artist = "4U"

[[discs.tracks]]
title = "僕らは青空になる -Off Vocal-"
artist = "777☆SISTERS"

[[discs.tracks]]
title = "FUNBARE☆RUNNER -Off Vocal-"
artist = "777☆SISTERS"

[[discs.tracks]]
title = "ラバ×ラバ -Off Vocal-"
artist = "WITCH NUMBER 4"

[[discs.tracks]]
title = "さよならレイニーレディ -Off Vocal-"
artist = "SiSH"

[[discs.tracks]]
title = "You Can't Win -Off Vocal-"
artist = "NI+CORA"

[[discs.tracks]]
title = "セカイのヒミツ -Off Vocal-"
artist = "サンボンリボン"

[[discs.tracks]]
title = "YELLOW -Off Vocal-"
artist = "Le☆S☆Ca"

[[discs.tracks]]
title = "Behind Moon -Off Vocal-"
artist = "Le☆S☆Ca"

[[discs.tracks]]
title = "ハネ☆る!! -Off Vocal-"
artist = "はる☆ジカ(ちいさな)"

[[discs.tracks]]
title = 'Snow in "I love you" -OFF VOCAL-'
artist = "777☆SISTERS"
