[album]
title = "IT'S A PERFECT BLUE"
artist = "Tokyo 7th シスターズ"
date = 2021-03-17
type = "normal"
catalog = "VIZL-1871"
tags = ["Tokyo 7th シスターズ"]

[[discs]]
title = "IT'S A PERFECT BLUE - Summer Sky"
catalog = "VIZL-1871-01"

[[discs.tracks]]
title = "Overture〜WITH A TINY BLUE〜"
type = "absolute"

[[discs.tracks]]
title = "MELODY IN THE POCKET"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "夏のビードロ☆シンフォニー"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "ラブリー♡オンリー"
artist = "SU♡SUTA(きゅうとな)（アレサンドラ・スース（大西沙織）、臼田スミレ（清水彩香））"

[[discs.tracks]]
title = "シトラスは片想い"
artist = "Ci+LUS（玉坂マコト（山崎エリイ）、折笠アユム（田中美海））"

[[discs.tracks]]
title = "アイコトバ"
artist = "Ci+LUS（玉坂マコト（山崎エリイ）、折笠アユム（田中美海））"

[[discs.tracks]]
title = "TRICK"
artist = "Ci+LUS（玉坂マコト（山崎エリイ）、折笠アユム（田中美海））"

[[discs.tracks]]
title = "空色スキップ"
artist = "Ci+LUS（玉坂マコト（山崎エリイ）、折笠アユム（田中美海））"

[[discs.tracks]]
title = "SHOW TIME"
artist = "CASQUETTE’S（川澄シサラ（末柄里恵）、浅見ミワコ（優木かな）、鳳チャチャ（大地葉）、二川ミミ（齋藤綾））"

[[discs.tracks]]
title = "マスカレード・ナイト"
artist = "CASQUETTE’S（川澄シサラ（末柄里恵）、浅見ミワコ（優木かな）、鳳チャチャ（大地葉）、二川ミミ（齋藤綾））"

[[discs.tracks]]
title = "SCARLET"
artist = "CASQUETTE’S（川澄シサラ（末柄里恵）、浅見ミワコ（優木かな）、鳳チャチャ（大地葉）、二川ミミ（齋藤綾））"

[[discs.tracks]]
title = "HEAVEN'S RAVE"
artist = "AXiS（天神ネロ（水瀬いのり）、比嘉アグリ（渕上舞）、蓬莱タキ（川﨑芽衣子）、志摩サビナ（前田玲奈）、鹿込オト（黒瀬ゆうこ）、帝塚セネカ（辻あゆみ））"

[[discs.tracks]]
title = "COCYTUS"
artist = "AXiS（天神ネロ（水瀬いのり）、比嘉アグリ（渕上舞）、蓬莱タキ（川﨑芽衣子）、志摩サビナ（前田玲奈）、鹿込オト（黒瀬ゆうこ）、帝塚セネカ（辻あゆみ））"

[[discs.tracks]]
title = "NATSUKAGE-夏陰-"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs]]
title = "IT'S A PERFECT BLUE - Rainbow Sky"
catalog = "VIZL-1871-02"

[[discs.tracks]]
title = "Shooting Sky"
artist = "セブンスシスターズ（七咲ニコル（水瀬いのり）、羽生田ミト（渕上舞）、御園尾マナ（前田玲奈）、寿クルト（黒瀬ゆうこ）、若王子ルイ（川崎芽衣子）、遊佐メモル（辻あゆみ））"

[[discs.tracks]]
title = "光"
artist = "七咲ニコル（水瀬いのり）"

[[discs.tracks]]
title = "花咲キオトメ"
artist = "七花少女（榎並マドカ（藤井アユ美）、前園リシュリ（ルゥティン）、夜舞サヲリ（稲川英里）、雲巻モナカ（桜木アミサ）、白鳥トモエ（宝木久美）、逢原ミウ（高野麻里佳）、シャオ・ヘイフォン（森千早都））"

[[discs.tracks]]
title = "スノードロップ"
artist = "七花少女（榎並マドカ（藤井アユ美）、前園リシュリ（ルゥティン）、夜舞サヲリ（稲川英里）、雲巻モナカ（桜木アミサ）、白鳥トモエ（宝木久美）、逢原ミウ（高野麻里佳）、シャオ・ヘイフォン（森千早都））"

[[discs.tracks]]
title = "マイ・グラデイション"
artist = "七花少女（榎並マドカ（藤井アユ美）、前園リシュリ（ルゥティン）、夜舞サヲリ（稲川英里）、雲巻モナカ（桜木アミサ）、白鳥トモエ（宝木久美）、逢原ミウ（高野麻里佳）、シャオ・ヘイフォン（森千早都））"

[[discs.tracks]]
title = "Fall in Love"
artist = "SEASON OF LOVE"

[[discs.tracks]]
title = "コドーモ・デ・ヒーロ"
artist = "コドモ連合"

[[discs.tracks]]
title = "LOVE AND DEVIL"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "AMATERRAS"
artist = "KARAKURI（空栗ヒトハ（秋奈）、空栗フタバ（秋奈））"

[[discs.tracks]]
title = "アイノシズク"
artist = "KARAKURI 2039"

[[discs.tracks]]
title = "Departures -あしたの歌-"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "リボン"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "IT'S A PERFECT BLUE, THANK YOU"
type = "absolute"

[[discs.tracks]]
title = "Across the Rainbow"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs]]
title = "IT'S A PERFECT BLUE - Off Vocal Tracks"
catalog = "VIZL-1871-03"
type = "instrumental"

[[discs.tracks]]
title = "Shooting Sky -OFF VOCAL-"
artist = "セブンスシスターズ"

[[discs.tracks]]
title = "SUN SUN SUN -OFF VOCAL-"
artist = "Le☆S☆Ca"

[[discs.tracks]]
title = "AMATERRAS -OFF VOCAL-"
artist = "KARAKURI"

[[discs.tracks]]
title = "光 -OFF VOCAL-"
artist = "七咲ニコル"

[[discs]]
title = "IT'S A PERFECT BLUE - Live Digest"
catalog = "VIZL-1871-04"

# 4U 1st Live!!!「The Pres“id”ent 4U」より
[[discs.tracks]]
title = "メロディーフラッグ"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "TREAT OR TREAT?"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "SAKURA〜WNo4 Cover〜"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

[[discs.tracks]]
title = "プレゼント・フォー・ユー"
artist = "4U（佐伯ヒナ（長縄まりあ）、鰐淵エモコ（吉岡茉祐）、九条ウメ（山下まみ））"

# The QUEEN of PURPLE 1st Live “I'M THE QUEEN, AND YOU？” より
[[discs.tracks]]
title = "Majesty"
artist = "The QUEEN of PURPLE（越前ムラサキ（野村麻衣子）、瀬戸ファーブ（広瀬ゆうき）、屋ユメノ（山本彩乃）、三森マツリ（巽悠衣子））"

[[discs.tracks]]
title = "THUNDERBOLT"
artist = "The QUEEN of PURPLE（越前ムラサキ（野村麻衣子）、瀬戸ファーブ（広瀬ゆうき）、屋ユメノ（山本彩乃）、三森マツリ（巽悠衣子））"

[[discs.tracks]]
title = "I AM"
artist = "The QUEEN of PURPLE（越前ムラサキ（野村麻衣子）、瀬戸ファーブ（広瀬ゆうき）、屋ユメノ（山本彩乃）、三森マツリ（巽悠衣子））"

[[discs.tracks]]
title = "DAYS"
artist = "The QUEEN of PURPLE（越前ムラサキ（野村麻衣子）、瀬戸ファーブ（広瀬ゆうき）、屋ユメノ（山本彩乃）、三森マツリ（巽悠衣子））"

# t7s 5th Anniversary Live -SEASON OF LOVE- in Makuhari Messe より
[[discs.tracks]]
title = "FUNBARE☆RUNNER"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"

[[discs.tracks]]
title = "ミツバチ"
artist = "Le☆S☆Ca（上杉・ウエバス・キョーコ（井上ほの花）、荒木レナ（飯塚麻結）、西園ホノカ（植田ひかる））"

[[discs.tracks]]
title = "花咲キオトメ"
artist = "七花少女（榎並マドカ（藤井アユ美）、前園リシュリ（ルゥティン）、夜舞サヲリ（稲川英里）、雲巻モナカ（桜木アミサ）、白鳥トモエ（宝木久美）、逢原ミウ（高野麻里佳）、シャオ・ヘイフォン（森千早都））"

[[discs.tracks]]
title = "AMATERRAS"
artist = "KARAKURI（空栗ヒトハ（秋奈）、空栗フタバ（秋奈））"

[[discs.tracks]]
title = "CHECK’MATE"
artist = "NI+CORA（天堂寺ムスビ（高田憂希）、アレサンドラ・スース（大西沙織））"

[[discs.tracks]]
title = "ハルカゼ〜You were here〜"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"
