[album]
album_id = "894bca53-6e5c-4b20-a0a8-79eacbde0b56"
title = 'Snow in "I love you"'
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"
date = 2015-12-09
type = "normal"
catalog = "VIZL-911"
tags = ["777☆SISTERS"]

[[discs]]
catalog = "VIZL-911"

[[discs.tracks]]
title = 'Snow in "I love you"'

[[discs.tracks]]
title = "ハネ☆る!!"
artist = "はる☆ジカ(ちいさな)（春日部ハル（篠田みなみ）、晴海カジカ（高井舞香））"

[[discs.tracks]]
title = 'Snow in "I love you" -OFF VOCAL-'
type = "instrumental"

[[discs.tracks]]
title = "ハネ☆る!! -OFF VOCAL-"
artist = "はる☆ジカ(ちいさな)"
type = "instrumental"

[[discs.tracks]]
title = "はる☆ジカ、聖夜の２日前"
type = "drama"
