[album]
album_id = "a197e12f-02ab-4812-867c-b2c63b130f28"
title = "ごまかし／うつろい"
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
date = 2020-03-11
type = "normal"
catalog = "VVCL-1630"

[[discs]]
catalog = "VVCL-1630"

[[discs.tracks]]
title = "ごまかし"

[[discs.tracks]]
title = "うつろい"

[[discs.tracks]]
title = "ごまかし -Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "うつろい -Instrumental-"
type = "instrumental"
