[album]
album_id = "fac650e6-566e-4835-ab78-15e1d07a3aa8"
title = "WANTED GIRL"
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
date = 2018-03-04
type = "normal"
catalog = "VVCL-1188"

[[discs]]
catalog = "VVCL-1188"

[[discs.tracks]]
title = "WANTED GIRL"

[[discs.tracks]]
title = "散歩道"

[[discs.tracks]]
title = "WANTED GIRL -Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "散歩道 -Instrumental-"
type = "instrumental"
