[album]
album_id = "0a1336a6-27a0-444b-b9fe-c122d405f88f"
title = "azure"
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
date = 2018-11-14
type = "normal"
catalog = "VVCL-1328"

[[discs]]
catalog = "VVCL-1328"

[[discs.tracks]]
title = "azure"

[[discs.tracks]]
title = "Make Me Happy?"

[[discs.tracks]]
title = "azure -Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "Make Me Happy? -Instrumental-"
type = "instrumental"
