[album]
album_id = "af14fe0e-92c8-4331-9768-004582bea8d9"
title = "アリシア／シグナル"
artist = "ClariS（クララ、カレン）"
date = 2020-03-04
type = "normal"
catalog = "VVCL-1613"
tags = ["マギアレコード 魔法少女まどか☆マギカ外伝:Anime"]

[[discs]]
catalog = "VVCL-1613"

[[discs.tracks]]
title = "アリシア"

[[discs.tracks]]
title = "シグナル"

[[discs.tracks]]
title = "ユニゾン"

[[discs.tracks]]
title = "アリシア –TV MIX-"

[[discs.tracks]]
title = "シグナル -GAME MIX-"
