[album]
album_id = "752ca8ff-aecc-4eb4-9a51-1e385d32014c"
title = 'TrySail Live Tour 2019 "The TrySail Odyssey"'
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
date = 2019-12-11
type = "normal"
catalog = "VVXL-47"

[[discs]]
catalog = "VVXL-47"

[[discs.tracks]]
title = "WANTED GIRL"

[[discs.tracks]]
title = "CODING"

[[discs.tracks]]
title = "未来キュレーション"

[[discs.tracks]]
title = "またね、"

[[discs.tracks]]
title = "Make Me Happy?"

[[discs.tracks]]
title = "whiz"

[[discs.tracks]]
title = "BraveSail"

[[discs.tracks]]
title = "バン!バン!!バンザイ!!!"

[[discs.tracks]]
title = "コバルト (コーラス)"

[[discs.tracks]]
title = "Take a step forward"

[[discs.tracks]]
title = "Truth."

[[discs.tracks]]
title = "Believe"

[[discs.tracks]]
title = "Sunset カンフー"

[[discs.tracks]]
title = "azure"

[[discs.tracks]]
title = "Baby My Step"

[[discs.tracks]]
title = "TryAgain"
