[album]
title = "THE IDOLM@STER MASTER BOX IV"
artist = "THE IDOLM@STER"
date = 2008-09-24
type = "normal"
catalog = "XT-2615~9"
tags = ["THE IDOLM@STER MASTER BOX"]

[[discs]]
catalog = "XT-2615"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "First Stage (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs]]
catalog = "XT-2616"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "萩原雪歩（落合祐里香）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs]]
catalog = "XT-2617"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "如月千早（今井麻美）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs]]
catalog = "XT-2618"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "菊地真（平田宏美）"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "秋月律子（若林直美）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs]]
catalog = "XT-2619"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "Here we go!! (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "おはよう!!朝ご飯 (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "蒼い鳥 (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "9:02 pm (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "太陽のジェラシー (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "ポジティブ! (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "エージェント夜を往く (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "THE IDOLM@STER (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "First Stage (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "魔法をかけて! (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "GO MY WAY!! (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "思い出をありがとう (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "relations (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "私はアイドル♡ (REMIX-B)"
artist = "双海亜美（下田麻美）、双海真美（下田麻美）"

[[discs.tracks]]
title = "relations (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "まっすぐ (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"

[[discs.tracks]]
title = "My Best Friend (REMIX-B)(オリジナルカラオケ)"
type = "instrumental"
