[album]
album_id = "9664aec9-4a6e-45b2-8325-c042aa92e7d5"
title = "TVアニメ『宇宙よりも遠い場所』オリジナルサウンドトラック"
artist = "藤澤慶昌"
date = 2018-03-28
type = "absolute"
catalog = "ZMCZ-11957"

[[discs]]
catalog = "ZMCZ-11957-01"

[[discs.tracks]]
title = "南極の太陽"

[[discs.tracks]]
title = "青春のはじまり"

[[discs.tracks]]
title = "のんびり昼下がり"

[[discs.tracks]]
title = "朝が来た"

[[discs.tracks]]
title = "通いあうココロ"

[[discs.tracks]]
title = "憩いの自販機前"

[[discs.tracks]]
title = "井戸端会議"

[[discs.tracks]]
title = "よっし始めようか！"

[[discs.tracks]]
title = "夕暮れ時の帰り道"

[[discs.tracks]]
title = "いい天気だねー"

[[discs.tracks]]
title = "南極少女"

[[discs.tracks]]
title = "軽く死ねますね"

[[discs.tracks]]
title = "まあなんとかなるんじゃない？"

[[discs.tracks]]
title = "ちょっと待ちなさーい！"

[[discs.tracks]]
title = "待って待って待ってー！"

[[discs.tracks]]
title = "ホッと一息"

[[discs.tracks]]
title = "えーっと…え？"

[[discs.tracks]]
title = "無理無理無理！"

[[discs.tracks]]
title = "だぁかぁらぁ！"

[[discs.tracks]]
title = "何か隠してることはなぁい？"

[[discs.tracks]]
title = 'き"も"ち"わ"る"い"…'

[[discs.tracks]]
title = 'あ"ー…'

[[discs.tracks]]
title = "確かめたいことがあるから"

[[discs.tracks]]
title = "大人からのYell"

[[discs.tracks]]
title = "忘れ形見"

[[discs]]
catalog = "ZMCZ-11957-02"

[[discs.tracks]]
title = "ともだち"

[[discs.tracks]]
title = "おもいで"

[[discs.tracks]]
title = "ひとりぼっち"

[[discs.tracks]]
title = "見つけた答え"

[[discs.tracks]]
title = "私たちは必ず南極に行く"

[[discs.tracks]]
title = "最後まで諦めない"

[[discs.tracks]]
title = "もう届かない想い"

[[discs.tracks]]
title = "心に絡まる鎖"

[[discs.tracks]]
title = "消せない記憶"

[[discs.tracks]]
title = "失った親友の面影"

[[discs.tracks]]
title = "溢れ出す想い"

[[discs.tracks]]
title = "ぜっこう"

[[discs.tracks]]
title = "失われた命"

[[discs.tracks]]
title = "親友との約束"

[[discs.tracks]]
title = "Bon Voyage !　〜Main Theme〜"

[[discs.tracks]]
title = "任務遂行"

[[discs.tracks]]
title = "状況説明"

[[discs.tracks]]
title = "予感"

[[discs.tracks]]
title = "緊急事態"

[[discs.tracks]]
title = "きっと忘れない"

[[discs.tracks]]
title = "The Girls Are Alright! 〜Piano Version〜"

[[discs.tracks]]
title = "ここから、ここから 〜Piano Version〜"

[[discs.tracks]]
title = "またね"
artist = "saya"
type = "normal"
