[album]
album_id = "e7bbc3e0-937c-4c1c-bc2a-f5660920ef4f"
title = "回復術士のやり直し オリジナルサウンドトラックCD①"
artist = "Team-MAX"
date = 2021-04-28
type = "absolute"
catalog = "ZMXZ-14662"
tags = ["回復術士のやり直し"]

[[discs]]
catalog = "ZMXZ-14662"

[[discs.tracks]]
title = "回復術士のやり直し"
artist = "藤泽健至"

[[discs.tracks]]
title = "激闘の荒野"
artist = "Johannes Nilsson"

[[discs.tracks]]
title = "血戦の果てに"
artist = "Johannes Nilsson"

[[discs.tracks]]
title = "ヒール!"
artist = "Johannes Nilsson"

[[discs.tracks]]
title = "悪い夢"
artist = "鈴木暁也"

[[discs.tracks]]
title = "精霊のキス"
artist = "鈴木暁也"

[[discs.tracks]]
title = "ひとときのよろこび"
artist = "鈴木暁也"

[[discs.tracks]]
title = "王都への道"
artist = "鈴木暁也"

[[discs.tracks]]
title = "王家の紋章"
artist = "Johannes Nilsson"

[[discs.tracks]]
title = "いいのよ、来て"
artist = "鈴木暁也"

[[discs.tracks]]
title = "フレアの微笑"
artist = "藤泽健至"

[[discs.tracks]]
title = "壊れていく心"
artist = "Johannes Nilsson"

[[discs.tracks]]
title = "覚醒"
artist = "鈴木暁也"

[[discs.tracks]]
title = "さあ、復讐を始めよう"
artist = "Johannes Nilsson"

[[discs.tracks]]
title = "蹂躙"
artist = "鈴木暁也"

[[discs.tracks]]
title = "この残酷な地上に"
artist = "藤泽健至"

[[discs.tracks]]
title = "純白の想い"
artist = "藤泽健至"

[[discs.tracks]]
title = "不穏な雲行き"
artist = "鈴木暁也"

[[discs.tracks]]
title = "声をひそめて"
artist = "Johannes Nilsson"

[[discs.tracks]]
title = "胸に燃える熾火"
artist = "鈴木暁也"

[[discs.tracks]]
title = "その日のために"
artist = "鈴木暁也"
