[category]
name = "雨宮天"
type = "A"
albums = [
  "SMCL-346",
  "SMCL-359",
  "SMCL-386",
  "SMCL-436",
  "SMCL-492",
  "SMCL-521",
  "SMCL-539",
  "SMCL-546",
  "SMCL-577",
  "SMCL-604",
  "SMCL-623",
  "SMCL-640",
  "SMCL-673",
  "SMCL-700",
  "SMCL-717",
]
