[category]
name = "麻倉もも"
type = "A"
albums = [
  "SMCL-454",
  "SMCL-483",
  "SMCL-515",
  "SMCL-552",
  "SMCL-561",
  "SMCL-591",
  "SMCL-600",
  "SMCL-614",
  "SMCL-653",
  "SMCL-676",
  "SMCL-720",
]
