[category]
name = "THE IDOLM@STER MILLION LIVE"
type = "AAAA"
albums = []

[[subcategory]]
name = "THE IDOLM@STER LIVE THE@TER PERFORMANCE"
albums = [
  "LACM-14080",
  "LACA-15300",
  "LACA-15313",
  "LACA-15314",
  "LACA-15315",
  "LACA-15316",
  "LACA-15317",
  "LACA-15318",
  "LACA-15319",
  "LACA-15320",
  "LACA-15321",
  "LACA-15322",
  "LACA-15323",
]

[[subcategory]]
name = "THE IDOLM@STER LIVE THE@TER HARMONY"
albums = [
  "LACA-15431",
  "LACA-15432",
  "LACA-15433",
  "LACA-15434",
  "LACA-15435",
  "LACA-15436",
  "LACA-15437",
  "LACA-15438",
  "LACA-15439",
  "LACA-15440",
]

[[subcategory]]
name = "THE IDOLM@STER LIVE THE@TER DREAMERS"
albums = [
  "LACM-14411",
  "LACM-14412",
  "LACM-14413",
  "LACM-14414",
  "LACM-14415",
  "LACM-14416",
]

[[subcategory]]
name = "THE IDOLM@STER THE@TER ACTIVITIES"
albums = ["LACM-14531", "LACM-14532", "LACM-14533"]

[[subcategory]]
name = "THE IDOLM@STER LIVE THE@TER FORWARD"
albums = ["LACA-15611", "LACA-15612", "LACA-15613"]

[[subcategory]]
name = "THE IDOLM@STER MILLION THE@TER GENERATION"
albums = [
  "LACM-14631",
  "LACM-14632",
  "LACM-14633",
  "LACM-14634",
  "LACM-14635",
  "LACM-14636",
  "LACM-14637",
  "LACM-14638",
  "LACM-14639",
  "LACM-14640",
  "LACM-14641",
  "LACM-14642",
  "LACM-14823",
  "LACM-14824",
  "LACM-14825",
  "LACM-14826",
  "LACM-14827",
  "LACM-14828",
]

[[subcategory]]
name = "THE IDOLM@STER M@STER SPARKLE"
albums = [
  "LACA-15671",
  "LACA-15672",
  "LACA-15673",
  "LACA-15674",
  "LACA-15675",
  "LACA-15676",
  "LACA-15677",
  "LACA-15678",
]

[[subcategory]]
name = "THE IDOLM@STER THE@TER BOOST"
albums = ["LACM-14811", "LACM-14812", "LACM-14813"]

[[subcategory]]
name = "THE IDOLM@STER THE@TER CHALLENGE"
albums = ["LACM-14947", "LACM-14948", "LACM-14949"]

[[subcategory]]
name = "THE IDOLM@STER MILLION THE@TER WAVE"
albums = [
  "LACM-14891",
  "LACM-14892",
  "LACM-14893",
  "LACM-14894",
  "LACM-14895",
  "LACM-14896",
  "LACM-14897",
  "LACM-14898",
  "LACM-14899",
  "LACM-14900",
  "LACM-14901",
  "LACM-14902",
  "LACM-14903",
  "LACM-14904",
  "LACM-14905",
  "LACM-24106",
  "LACM-24107",
  "LACM-24108",
]

[[subcategory]]
name = "THE IDOLM@STER LIVE THE@TER PERFORMANCE Remix"
albums = [
  "LACZ-10046",
  "LACZ-10047",
  "LACZ-10053",
  "LACZ-10054",
  "LACZ-10055",
  "LACZ-10056",
]

[[subcategory]]
name = "THE IDOLM@STER LIVE THE@TER PERFORMANCE Instrumental"
albums = [
  "LACZ-10044",
  "LACZ-10045",
  "LACZ-10049",
  "LACZ-10050",
  "LACZ-10051",
  "LACZ-10052",
]

[[subcategory]]
name = "THE IDOLM@STER LIVE THE@TER SOLO COLLECTION"
albums = [
  "LZM-2124~5",
  "LZM-2130~1",
  "LZM-2141",
  "LZM-2142",
  "LZM-2143",
  "LZM-2155",
  "LZM-2156",
  "LZM-2157",
  "LZM-2165",
  "LACZ-10002",
  "LACZ-10003",
  "LACZ-10004",
  "LACZ-10020",
  "LACZ-10021",
  "LACZ-10022",
  "LACZ-10034",
  "LACZ-10035",
  "LACZ-10036",
]

[[subcategory]]
name = "THE IDOLM@STER MILLION LIVE SPECIAL ALBUMS"
albums = [
  # THE IDOLM@STER LIVE THE@TER SELECTION
  "BNGI-00007",
  # THE IDOLM@STER MILLION LIVE! 1stLIVE HAPPY☆PERFORM@NCE!! Blu-ray "COMPLETE THE@TER" CD
  "LAPC-1073",
  # THE IDOLM@STER MILLION LIVE! 765プロライブシアター記念パーティードラマCD
  "BNGI-00002",
  # THE IDOLM@STER 765PRO LIVE THE@TER COLLECTION Vol.1
  "LACA-9398~9",
  # THE IDOLM@STER MILLION LIVE! 2ndLIVE ENJOY H@RMONY!! LIVE Blu-ray "COMPLETE THE@TER" CD
  "LAPC-1074",
  # THE IDOLM@STER MILLION LIVE! 765プロライブシアター 3周年記念イベントリポート ドラマCD
  "BNEI-00003",
  # THE IDOLM@STER MILLION LIVE! 4th ANNIVERSARY 五十一人一首 朗読CD
  "BNEI-ML／RI-2017",
  # 君との明日を願うから
  "LZC-1132",
  # THE IDOLM@STER 765 MILLIONSTARS HOTCHPOTCH FESTIV@L!! LIVE CD
  "LAPP-1107",
  # THE IDOLM@STER MILLION LIVE! 5thLIVE BRAND NEW PERFORM@NCE!!! LIVE CD
  "LAPP-1109",
  # THE IDOLM@STER MILLION LIVE! 6thLIVE TOUR UNI-ON@IR!!!! オリジナルLIVE音源 CD
  "LAPP-1120",
  # なんどでも笑おう【ミリオンライブ！盤】
  "LACM-24025",
  # THE IDOLM@STER MILLION LIVE! ZWEIGLANZ アライアンス・スターダスト
  "LACM-24004",
  # THE IDOLM@STER MILLION LIVE! STAR EQUINOX
  "LACM-24088",
  # リフレインキス (Brand New Ver.)
  "LZC-1901",
  # 花びらメモリーズ
  "LZC-1902"
]

[[subcategory]]
name = "THE IDOLM@STER MILLION LIVE! オリジナルCD"
albums = [
  "ISBN-9784091592033",
  "ISBN-9784091592132",
  "ISBN-9784091592217",
  "ISBN-9784091592354",
  "ISBN-9784099418847",
]

[[subcategory]]
name = "THE IDOLM@STER MILLION LIVE! Blooming Clover"
albums = [
  "ISBN-9784048932653",
  "ISBN-9784048932660",
  "ISBN-9784048938082",
  "ISBN-9784049121049",
  "ISBN-9784049124668",
  "ISBN-9784049129304",
  "ISBN-9784049131376",
  "ISBN-9784049134186",
  "ISBN-9784049137767",
]

[[subcategory]]
name = "THE IDOLM@STER MILLION LIVE! THEATER DAYS Brand New Song"
albums = [
  # THE IDOLM@STER MILLION LIVE! THEATER DAYS Brand New Song 1巻 特典CD
  "ISBN-9784758016261",
  # THE IDOLM@STER MILLION LIVE! THEATER DAYS Brand New Song 3巻 特典CD
  "ISBN-9784758016988",
  # THE IDOLM@STER MILLION LIVE! THEATER DAYS Brand New Song 4巻 特典CD
  "ISBN-9784758017305"
]

[[subcategory]]
name = "THE IDOLM@STER MILLION RADIO!"
albums = [
  # THE IDOLM@STER MILLION RADIO! 765PRO LIVE THE@TER ミリラジ劇場セレクション ～アニメイト～
  "LAPP-1063",
  # THE IDOLM@STER MILLION RADIO! 765PRO LIVE THE@TER ミリラジ劇場セレクション ～ゲーマーズ～
  "LAPP-1064",
  # THE IDOLM@STER MILLION RADIO! 765PRO LIVE THE@TER ミリラジ劇場セレクション ～とらのあな～
  "LAPP-1065",
  # THE IDOLM@STER MILLION RADIO! 765PRO LIVE THE@TER ミリラジ劇場セレクション ～ソフマップ～
  "LAPP-1066",
  # THE IDOLM@STER MILLION RADIO! U・N・M・E・I ライブ
  "LACM-34234",
  # THE IDOLM@STER MILLION RADIO! ターンオンタイム！
  "LACM-14506",
  # THE IDOLM@STER MILLION RADIO! ENDLESS TOUR
  "LACM-14961",
]
