[category]
name = "Tokyo 7th シスターズ"
type = "AAAA"
albums = [
  # t7s Longing for summer
  "TS-0001",
  # H-A-J-I-M-A-L-B-U-M-!!
  "TS-0003",
  # Are You Ready 7th-TYPES??
  "VIZL-988",
  # THE STRAIGHT LIGHT
  "VIZL-1396",
  # 『Tokyo 7th シスターズ -僕らは青空になる-』 オリジナルサウンドトラック
  "VICL-65474",
  # IT'S A PERFECT BLUE
  "VIZL-1871",
]

[[subcategory]]
name = "セブンスシスターズ"
# 七咲ニコル（水瀬いのり）
# 羽生田ミト（渕上舞）
# 御園尾マナ（前田玲奈）
# 寿クルト（黒瀬ゆうこ）
# 若王子ルイ（川崎芽衣子）
# 遊佐メモル（辻あゆみ）
albums = [
  # SEVENTH HAVEN
  "VIZL-934",
  # WORLD'S END
  "VIZL-1191"
]

[[subcategory]]
name = "777☆SISTERS"
# 春日部ハル（篠田みなみ）
# 天堂寺ムスビ（高田憂希）
# 角森ロナ（加隈亜衣）
# 野ノ原ヒメ（中島唯）
# 芹沢モモカ（井澤詩織）
# 臼田スミレ（清水彩香）
# 神城スイ（道井悠）
# 久遠寺シズカ（今井麻夏）
# アレサンドラ・スース（大西沙織）
# 晴海サワラ（中村桜）
# 晴海カジカ（高井舞香）
# 晴海シンジュ（桑原由気）
albums = [
  # 僕らは青空になる／FUNBARE☆RUNNER
  "VIZL-856",
  # Snow in "I love you"
  "VIZL-911",
  # ハルカゼ～You were here～
  "VIZL-1158",
  # スタートライン／STAY☆GOLD
  "VIZL-1192",
  # MELODY IN THE POCKET
  "VIZL-1449",
  # NATSUKAGE-夏陰-
  "VIZL-1602",
  # Across the Rainbow
  "VIZL-1822",
]

[[subcategory]]
name = "WITCH NUMBER 4"
# 春日部ハル（篠田みなみ）
# 角森ロナ（加隈亜衣）
# 野ノ原ヒメ（中島唯）
# 芹沢モモカ（井澤詩織）
albums = []

[[subcategory]]
name = "SiSH"
# 臼田スミレ（清水彩香）
# 神城スイ（道井悠）
# 久遠寺シズカ（今井麻夏）
albums = []

[[subcategory]]
name = "NI+CORA"
# 天堂寺ムスビ（高田憂希）
# アレサンドラ・スース（大西沙織）
albums = []

[[subcategory]]
name = "サンボンリボン"
# 晴海サワラ（中村桜）
# 晴海カジカ（高井舞香）
# 晴海シンジュ（桑原由気）
albums = []

[[subcategory]]
name = "Le☆S☆Ca"
# 上杉・ウエバス・キョーコ（吉井彩実） → 上杉・ウエバス・キョーコ（井上ほの花） [2019-02-28]
# 荒木レナ（藤田茜） → 荒木レナ（飯塚麻結）[2019-04-22]
# 西園ホノカ（植田ひかる）
albums = [
  # YELLOW
  "VIZL-912",
  # トワイライト／タンポポ
  "VIZL-1076",
]

[[subcategory]]
name = "The QUEEN of PURPLE"
# 越前ムラサキ（野村麻衣子）
# 瀬戸ファーブ（広瀬ゆうき）
# 堺屋ユメノ（山本彩乃）
# 三森マツリ（巽悠衣子）
albums = [
  # TRIGGER／Fire and Rose
  "VIZL-1064",
]

[[subcategory]]
name = "Ci+LUS"
# 玉坂マコト（山崎エリイ）
# 折笠アユム（田中美海）
albums = [
  # シトラスは片想い
  "VIZL-1380",
]

[[subcategory]]
name = "CASQUETTE’S"
# 川澄シサラ（末柄里恵）
# 浅見ミワコ（優木かな）
# 鳳チャチャ（大地葉）
# 二川ミミ（齋藤綾）
albums = []

[[subcategory]]
name = "七花少女"
# 榎並マドカ（藤井アユ美）
# 前園リシュリ（ルゥティン）
# 夜舞サヲリ（稲川英里）
# 雲巻モナカ（桜木アミサ）
# 白鳥トモエ（宝木久美）
# 逢原ミウ（高野麻里佳）
# シャオ・ヘイフォン（森千早都）
albums = []

[[subcategory]]
name = "はる☆ジカ(ちいさな)"
# 春日部ハル（篠田みなみ）
# 晴海カジカ（高井舞香）
albums = []

[[subcategory]]
name = "SU♡SUTA(きゅうとな)"
# アレサンドラ・スース（大西沙織）
# 臼田スミレ（清水彩香）
albums = []

[[subcategory]]
name = "4U"
# 佐伯ヒナ（長縄まりあ）
# 鰐淵エモコ（吉岡茉祐）
# 九条ウメ（山下まみ）
albums = [
  # The Present “4U”
  "VIZL-1284",
  # Winning Day／Lucky☆Lucky
  "VIZL-1075",
]

[[subcategory]]
name = "KARAKURI"
# 空栗ヒトハ（秋奈）
# 空栗フタバ（秋奈）
albums = [
  # Winning Day／Lucky☆Lucky
  "VIZL-1075",
]

[[subcategory]]
name = "AXiS"
# 天神ネロ（水瀬いのり）
# 比嘉アグリ（渕上舞）
# 蓬莱タキ（川﨑芽衣子）
# 志摩サビナ（前田玲奈）
# 鹿込オト（黒瀬ゆうこ）
# 帝塚セネカ（辻あゆみ）
albums = []
