[category]
name = "ご注文はうさぎですか？"
type = "Bangumi"
albums = []

[[subcategory]]
name = "ご注文はうさぎですか？"
albums = [
  "GNCA-0330",
  "GNCA-0335",
  "GNCA-1389",
  "GNXA-1681",
  "GNXA-1682",
  "GNXA-1683",
  "GNXA-1684",
  "GNXA-1685",
  "GNXA-1686",
]

[[subcategory]]
name = "TVアニメ「ご注文はうさぎですか？」キャラクターソング"
albums = ["GNCA-0337", "GNCA-0338", "GNCA-0339", "GNCA-0340", "GNCA-1418"]

[[subcategory]]
name = "2015年キャラクターソングシリーズ"
albums = ["GNCA-0390", "GNCA-0391", "GNCA-0392"]

[[subcategory]]
name = "ごちうさDJブレンド"
albums = ["GNCA-1471", "GNCA-1550"]

[[subcategory]]
name = "ご注文はうさぎですか？？"
albums = [
  "GNCA-0400",
  "GNCA-0402",
  "GNCA-1476",
  "GNXA-1771",
  "GNXA-1772",
  "GNXA-1773",
  "GNXA-1774",
  "GNXA-1775",
  "GNXA-1776",
  "GNCA-1590",
]

[[subcategory]]
name = "ご注文はうさぎですか？？キャラクターソングシリーズ"
albums = [
  "GNCA-1475",
  "GNCA-0451",
  "GNCA-0452",
  "GNCA-0453",
  "GNCA-0454",
  "GNCA-0455",
  "GNCA-0456",
  "GNCA-0457",
  "GNCA-0458",
  "LPR-762",
]

[[subcategory]]
name = "order the songs"
albums = ["GNCA-1501", "GNCA-1517"]

[[subcategory]]
name = "ご注文はうさぎですか？？～Dear My Sister～"
albums = [
  "GNCA-0515",
  "GNCA-0516",
  "GNCA-0517",
  "GNCA-1516",
  "GNXA-1217-01",
  "GNXA-1217-02",
]

[[subcategory]]
name = "ご注文はうさぎですか？？キャラクターソロシリーズ"
albums = [
  "GNCA-0551",
  "GNCA-0552",
  "GNCA-0558",
  "GNCA-0554",
  "GNCA-0555",
  "GNCA-0556",
  "GNCA-0557",
  "GNCA-0553",
  "GNCA-0559",
  "LPR-794",
]

[[subcategory]]
name = "ご注文はうさぎですか？？バースデイソングシリーズ"
albums = [
  "GNCA-0571",
  "GNCA-0572",
  "GNCA-0573",
  "GNCA-0574",
  "GNCA-0575",
  "GNCA-0576",
  "GNCA-0577",
  "GNCA-0578",
  "GNCA-0579",
  "LPR-809",
]

[[subcategory]]
name = "ご注文はうさぎですか?? ～Sing For You～"
albums = ["GNCA-0600", "GNXA-1219"]

[[subcategory]]
name = "ご注文はうさぎですか？BLOOM"
albums = [
  "GNCA-0620",
  "GNCA-0622",
  "GNCA-1599",
  "GNXA-1591",
  "GNXA-1592",
  "GNXA-1593",
  "GNXA-1594",
  "GNXA-1595",
  "GNXA-1596",
]

[[subcategory]]
name = "Others"
albums = ["GNCA-1500", "GNCA-1566", "GNCA-1567"]
