[[tag]]
name = "Key Sounds Label"
includes = ["Summer Pockets", "Kud Wafter", "神様になった日"]

[[tag]]
name = "Rewrite"
included-by = ["Key Sounds Label"]
includes = [
  "ラジオRewrite 月刊テラ・風祭学院支局",
  "Rewrite Harvest festa!",
  "TVアニメ「Rewrite」"
]
