[[tag]]
name = "プロジェクトセカイ カラフルステージ！feat.初音ミク"
names.zh-hans = "世界计划 缤纷舞台！ feat. 初音未来"
type = "project"
includes.group = [
  "Leo/need",
  "MORE MORE JUMP！",
  "Vivid BAD SQUAD",
  "ワンダーランズ×ショウタイム",
  "25時、ナイトコードで。"
]
