[[tag]]
name = "Tokyo 7th シスターズ"
type = "project"
includes.group = [
  #
  # 七咲ニコル（水瀬いのり）
  # 羽生田ミト（渕上舞）
  # 御園尾マナ（前田玲奈）
  # 寿クルト（黒瀬ゆうこ）
  # 若王子ルイ（川崎芽衣子）
  # 遊佐メモル（辻あゆみ）
  "セブンスシスターズ",
  #
  # 春日部ハル（篠田みなみ）
  # 天堂寺ムスビ（高田憂希）
  # 角森ロナ（加隈亜衣）
  # 野ノ原ヒメ（中島唯）
  # 芹沢モモカ（井澤詩織）
  # 臼田スミレ（清水彩香）
  # 神城スイ（道井悠）
  # 久遠寺シズカ（今井麻夏）
  # アレサンドラ・スース（大西沙織）
  # 晴海サワラ（中村桜）
  # 晴海カジカ（高井舞香）
  # 晴海シンジュ（桑原由気）
  "777☆SISTERS",
  #
  # 春日部ハル（篠田みなみ）
  # 角森ロナ（加隈亜衣）
  # 野ノ原ヒメ（中島唯）
  # 芹沢モモカ（井澤詩織）
  "WITCH NUMBER 4",
  #
  # 臼田スミレ（清水彩香）
  # 神城スイ（道井悠）
  # 久遠寺シズカ（今井麻夏）
  "SiSH",
  #
  # 天堂寺ムスビ（高田憂希）
  # アレサンドラ・スース（大西沙織）
  "NI+CORA",
  #
  # 晴海サワラ（中村桜）
  # 晴海カジカ（高井舞香）
  # 晴海シンジュ（桑原由気）
  "サンボンリボン",
  #
  # 上杉・ウエバス・キョーコ（吉井彩実） → 上杉・ウエバス・キョーコ（井上ほの花） [2019-02-28]
  # 荒木レナ（藤田茜） → 荒木レナ（飯塚麻結）[2019-04-22]
  # 西園ホノカ（植田ひかる）
  "Le☆S☆Ca",
  # 越前ムラサキ（野村麻衣子）
  # 瀬戸ファーブ（広瀬ゆうき）
  # 堺屋ユメノ（山本彩乃）
  # 三森マツリ（巽悠衣子）
  "The QUEEN of PURPLE",
  # 玉坂マコト（山崎エリイ）
  # 折笠アユム（田中美海）
  "Ci+LUS",
  #
  # 川澄シサラ（末柄里恵）
  # 浅見ミワコ（優木かな）
  # 鳳チャチャ（大地葉）
  # 二川ミミ（齋藤綾）
  "CASQUETTE’S",
  #
  # 榎並マドカ（藤井アユ美）
  # 前園リシュリ（ルゥティン）
  # 夜舞サヲリ（稲川英里）
  # 雲巻モナカ（桜木アミサ）
  # 白鳥トモエ（宝木久美）
  # 逢原ミウ（高野麻里佳）
  # シャオ・ヘイフォン（森千早都）
  "七花少女",
  #
  # 春日部ハル（篠田みなみ）
  # 晴海カジカ（高井舞香）
  "はる☆ジカ(ちいさな)",
  #
  # アレサンドラ・スース（大西沙織）
  # 臼田スミレ（清水彩香）
  "SU♡SUTA(きゅうとな)",
  #
  # 佐伯ヒナ（長縄まりあ）
  # 鰐淵エモコ（吉岡茉祐）
  # 九条ウメ（山下まみ）
  "4U",
  #
  # 空栗ヒトハ（秋奈）
  # 空栗フタバ（秋奈）
  "KARAKURI",
  #
  # 天神ネロ（水瀬いのり）
  # 比嘉アグリ（渕上舞）
  # 蓬莱タキ（川﨑芽衣子）
  # 志摩サビナ（前田玲奈）
  # 鹿込オト（黒瀬ゆうこ）
  # 帝塚セネカ（辻あゆみ）
  "AXiS",
  #
  # 晴海シンジュ（桑原由気）
  # ターシャ・ロマノフスキー（高岸美里亜）
  # 星柿マノン（山岡ゆり）
  # 有栖シラユキ（北方奈月）
  "SEASON OF LOVE",
  #
  # TODO
  "KARAKURI 2039",
  #
  # 桂木カヅミ（立花理香）
  "桂木カヅミ",
  #
  # ジェダ・ダイヤモンド（伊波杏樹）
  "ジェダ・ダイヤモンド",
  #
  # 星影アイ（天希かのん）
  # 月代ユウ（天野聡美）
  "Stella MiNE",
  #
  # 奈々星アイ（天希かのん）
  # 一ノ瀬マイ（星ノ谷しずく）
  # 朝凪シオネ（山田麻莉奈）
  "Asterline",
  #
  # 月代ユウ（天野聡美）
  # タン・シヨン（橘一花）
  # フラナ・リン（長谷川玲奈）
  "Roots.",
]
