[[tag]]
name = "BanG Dream!"
type = "project"
includes.group = [
  # Poppin'Party（戸山香澄（愛美）、花園たえ（大塚紗英）、牛込りみ（西本りみ）、山吹沙綾（大橋彩香）、市ヶ谷有咲（伊藤彩沙））
  "Poppin'Party",
  # ~180513
  # Roselia（湊友希那（相羽あいな）、氷川紗夜（工藤晴香）、今井リサ（遠藤ゆりか）、宇田川あこ（櫻川めぐ）、白金燐子（明坂聡美））
  # 180513~181107
  # Roselia（湊友希那（相羽あいな）、氷川紗夜（工藤晴香）、今井リサ（中島由貴）、宇田川あこ（櫻川めぐ）、白金燐子（明坂聡美））
  # 181107~
  # Roselia（湊友希那（相羽あいな）、氷川紗夜（工藤晴香）、今井リサ（中島由貴）、宇田川あこ（櫻川めぐ）、白金燐子（志崎樺音））
  "Roselia",
  # Afterglow（美竹蘭（佐倉綾音）、青葉モカ（三澤紗千香）、上原ひまり（加藤英美里）、宇田川巴（日笠陽子）、羽沢つぐみ（金元寿子））
  "Afterglow",
  # Pastel＊Palettes（丸山彩（前島亜美）、氷川日菜（小澤亜李）、白鷺千聖（上坂すみれ）、大和麻弥（中上育実）、若宮イヴ（秦佐和子））
  "Pastel＊Palettes",
  # ハロー、ハッピーワールド！（弦巻こころ（伊藤美来）、瀬田薫（田所あずさ）、北沢はぐみ（吉田有里）、松原花音（豊田萌絵）、ミッシェル（奥沢美咲（黒沢ともよ）））
  "ハロー、ハッピーワールド！",
  # RAISE A SUILEN（レイヤ（和奏レイ（Raychell））、ロック（朝日六花（小原莉子））、マスキング（佐藤ますき（夏芽））、パレオ（鳰原令王那（倉知玲鳳））、チュチュ（珠手ちゆ（紡木吏佐）））
  "RAISE A SUILEN",
  # Morfonica（倉田ましろ（進藤あまね）、桐ヶ谷透子（直田姫奈）、広町七深（西尾夕香）、二葉つくし（mika）、八潮瑠唯（Ayasa））
  "Morfonica",
  # Glitter*Green（牛込ゆり（三森すずこ）、鵜沢リィ（橘田いずみ）、鰐部七菜（佐々木未来）、二十騎ひなこ（徳井青空））
  "Glitter*Green",
  # CHiSPA（海野夏希（福圓美里）、大湖里実（南早紀）、川端真結（本泉莉奈）、森文華（朝日奈丸佳））
  "CHiSPA",
  # MyGO!!!!!（燈（Tomori）、愛音（Anon）、楽奈（Rāna）、そよ（Soyo）、立希（Taki））
  "MyGO!!!!!",
]
includes.animation = [
  "TVアニメ「BanG Dream!」",
  "劇場版「BanG Dream! FILM LIVE」",
  "劇場版「BanG Dream! FILM LIVE 2nd Stage」",
  "アニメ「BanG Dream! Morfonication」",
]
includes.series = [
  "バンドリ！ガールズバンドパーティ！カバーコレクション",
  "BanG Dream! Instrumental Collection",
]

[[tag]]
name = "劇場版「BanG Dream! Episode of Roselia」"
type = "animation"
included-by = ["BanG Dream!"]
includes.animation = [
  "劇場版「BanG Dream! Episode of Roselia Ⅰ : 約束」",
  "劇場版「BanG Dream! Episode of Roselia Ⅱ : Song I am.」",
]
