[[tag]]
name = "冴えない彼女の育てかた"
names.zh-hans = "路人女主的养成方法"
type = "animation"
includes.series = ["冴えない彼女の育てかた キャラクターイメージソング"]

[[tag]]
name = "冴えない彼女の育てかた♭"
names.zh-hans = "路人女主的养成方法♭"
type = "animation"
included-by = ["冴えない彼女の育てかた"]

[[tag]]
name = "冴えない彼女の育てかた Fine"
names.zh-hans = "路人女主的养成方法 Fine"
type = "animation"
included-by = ["冴えない彼女の育てかた"]
