[[tag]]
name = "本好きの下剋上 司書になるためには手段を選んでいられません"
names.zh-hans = "小书痴的下克上：为了成为图书管理员而不择手段"
type = "project"
includes.animation = [
    "TVアニメ「本好きの下剋上 司書になるためには手段を選んでいられません1」",
    "TVアニメ「本好きの下剋上 司書になるためには手段を選んでいられません2」",
    "TVアニメ「本好きの下剋上 司書になるためには手段を選んでいられません3」"
]
