################################################################################
# Artist
#
[[tag]]
name = "遠藤ゆりか"
type = "artist"

[[tag]]
name = "東山奈央"
type = "artist"

[[tag]]
name = "ReoNa"
type = "artist"

[[tag]]
name = "岡咲美保"
type = "artist"

[[tag]]
name = "LiSA"
type = "artist"

[[tag]]
name = "Aimer"
type = "artist"

[[tag]]
name = "YOASOBI"
type = "artist"

[[tag]]
name = "Liyuu"
type = "artist"

[[tag]]
name = "茅野愛衣"
type = "artist"

[[tag]]
name = "山崎はるか"
type = "artist"

[[tag]]
name = "夏川椎菜"
type = "artist"

[[tag]]
name = "富田美憂"
type = "artist"

[[tag]]
name = "水瀬いのり"
type = "artist"

[[tag]]
name = "中島由貴"
type = "artist"

[[tag]]
name = "田所あずさ"
type = "artist"

[[tag]]
name = "石原夏織"
type = "artist"

[[tag]]
name = "上田麗奈"
type = "artist"

[[tag]]
name = "樋口楓"
type = "artist"

[[tag]]
name = "伊藤美来"
type = "artist"

[[tag]]
name = "雨宮天"
type = "artist"

[[tag]]
name = "内田彩"
type = "artist"

[[tag]]
name = "高橋李依"
type = "artist"

[[tag]]
name = "麻倉もも"
type = "artist"

[[tag]]
name = "水樹奈々"
type = "artist"

[[tag]]
name = "春奈るな"
type = "artist"

[[tag]]
name = "沢井美空"
type = "artist"

[[tag]]
name = "いとうかなこ"
type = "artist"

[[tag]]
name = "高槻かなこ"
type = "artist"

[[tag]]
name = "相沢梨紗"
type = "artist"

[[tag]]
name = "鈴木このみ"
type = "artist"

[[tag]]
name = "平山笑美"
type = "artist"

[[tag]]
name = "渡部恵子"
type = "artist"

[[tag]]
name = "楠木ともり"
type = "artist"

[[tag]]
name = "神田沙也加"
type = "artist"
includes.artist = ["SAYAKA"]

[[tag]]
name = "鈴木みのり"
type = "artist"

[[tag]]
name = "やなぎなぎ"
type = "artist"
includes.artist = ["nagi"]

[[tag]]
name = "こゑだ"
type = "artist"

[[tag]]
name = "chelly"
type = "artist"
includes.artist = ["EGOIST"]

[[tag]]
name = "小倉唯"
type = "artist"

[[tag]]
name = "大原ゆい子"
type = "artist"

[[tag]]
name = "ヨルシカ"
type = "artist"

[[tag]]
name = "YURiKA"
type = "artist"

[[tag]]
name = "milet"
type = "artist"

[[tag]]
name = "幾田りら"
type = "artist"

[[tag]]
name = "大西亜玖璃"
type = "artist"

[[tag]]
name = "大橋彩香"
type = "artist"

[[tag]]
name = "ASCA"
type = "artist"
includes.artist = ["大倉明日香"]

[[tag]]
name = "西川貴教"
type = "artist"

[[tag]]
name = "佐藤聡美"
type = "artist"

[[tag]]
name = "竹内まりや"
type = "artist"

[[tag]]
name = "駒形友梨"
type = "artist"

[[tag]]
name = "亜咲花"
type = "artist"

[[tag]]
name = "佐々木恵梨"
type = "artist"

[[tag]]
name = "南條愛乃"
type = "artist"

[[tag]]
name = "eufonius"
type = "artist"

[[tag]]
name = "遠藤璃菜"
type = "artist"

[[tag]]
name = "さユり"
type = "artist"

[[tag]]
name = "halca"
type = "artist"

[[tag]]
name = "イソラ"
type = "artist"

[[tag]]
name = "鈴木愛奈"
type = "artist"

[[tag]]
name = "藍井エイル"
type = "artist"

[[tag]]
name = "井口裕香"
type = "artist"

################################################################################
# Group
#
# ~2019 22/7（佐藤麗華（帆風千春）、戸田ジュン（海乃るり）、藤間桜（天城サリー）、河野都（倉岡水巴）、斎藤ニコル（花川芽衣）、立川絢香（宮瀬玲奈）、滝川みう（西條和）、柊つぼみ（武田愛奈）、東条悠希（高辻麗）、神木みかみ（涼花萌）、丸山あかね（白沢かなえ））
# 2019~2022 22/7（佐藤麗華（帆風千春）、戸田ジュン（海乃るり）、藤間桜（天城サリー）、河野都（倉岡水巴）、斎藤ニコル（河瀬詩）、立川絢香（宮瀬玲奈）、滝川みう（西條和）、柊つぼみ（武田愛奈）、東条悠希（高辻麗）、神木みかみ（涼花萌）、丸山あかね（白沢かなえ））
# 2022~ 22/7（藤間桜（天城サリー）、斎藤ニコル（河瀬詩）、丸山あかね（白沢かなえ）、神木みかみ（涼花萌）、立川絢香（宮瀬玲奈）、西浦そら（相川奈央）、桐生塔子（麻丘真央）、八神叶愛（雨夜音）、永峰楓（清井美那）、織原純佳（椎名桜月）、一之瀬蛍（四条月）、氷室みず姫（月城咲舞）、瀬良穂乃花（望月りの））
[[tag]]
name = "ナナブンノニジュウニ"
type = "group"

[[tag]]
name = "Pyxis"
type = "group"

[[tag]]
name = "HoneyWorks"
type = "group"

[[tag]]
name = "ゆいかおり"
type = "group"

[[tag]]
name = "TrySail"
type = "group"

[[tag]]
name = "DIALOGUE+"
type = "group"

[[tag]]
name = "でんぱ組.inc"
type = "group"

[[tag]]
name = "ClariS"
type = "group"

[[tag]]
name = "妄想キャリブレーション"
type = "group"

[[tag]]
name = "Kalafina"
type = "group"

[[tag]]
name = "ARCANA PROJECT"
type = "group"

[[tag]]
name = "Mia REGINA"
type = "group"

[[tag]]
name = "スフィア"
type = "group"

[[tag]]
name = "純情のアフィリア"
type = "group"
includes.group = ["アフィリア・サーガ・イースト", "アフィリア・サーガ"]

[[tag]]
name = "SILENT SIREN"
type = "group"
includes.group = ["Silent Siren"]

[[tag]]
name = "BATON=RELAY"
type = "group"

[[tag]]
name = "supercell"
type = "group"

[[tag]]
name = "まねきケチャ"
type = "group"

[[tag]]
name = "HIMEHINA"
type = "group"

[[tag]]
name = "fhána"
type = "group"

# 1st ~ 8th =LOVE（大谷映美里、大場花菜、音嶋莉沙、齋藤樹愛羅、齊藤なぎさ、佐々木舞香、髙松瞳、瀧脇笙古、野口衣織、諸橋沙夏、山本杏奈、佐竹のん乃）
# 9th ~ =LOVE（大谷映美里、大場花菜、音嶋莉沙、齋藤樹愛羅、齊藤なぎさ、佐々木舞香、髙松瞳、瀧脇笙古、野口衣織、諸橋沙夏、山本杏奈）
[[tag]]
name = "=LOVE"
type = "group"

# ≠ME（尾木波菜、落合希来里、蟹沢萌子、河口夏音、川中子奈月心、櫻井もも、菅波美玲、鈴木瞳美、谷崎早耶、冨田菜々風、永田詩央里、本田珠由記）
[[tag]]
name = "≠ME"
type = "group"

[[tag]]
name = "キバオブアキバ"
type = "group"

[[tag]]
name = "RADWIMPS"
type = "group"

[[tag]]
name = "ヒーラーガールズ"
type = "group"

[[tag]]
name = "swing, sing"
type = "group"

[[tag]]
name = "harmoe"
type = "group"

[[tag]]
name = "OCHA NORMA"
type = "group"

# 2002~2009 fripSide（nao、八木沼悟志）
# 2009~2022 fripSide（南條愛乃、八木沼悟志）
# 2002~     fripSide（上杉真央、阿部寿世、八木沼悟志）
[[tag]]
name = "fripSide"
type = "group"
includes.group = ["fripSide NAO project!"]

[[tag]]
name = "angela"
type = "group"

################################################################################
# Animation
#
[[tag]]
name = "100万の命の上に俺は立っている"
type = "animation"

[[tag]]
name = "白い砂のアクアトープ"
type = "animation"
includes.series = ["白い砂のアクアトープ がまがま水族館 館内放送局"]

[[tag]]
name = "宇宙よりも遠い場所"
type = "animation"

[[tag]]
name = "High School Fleet"
type = "animation"

[[tag]]
name = "ひげを剃る。そして女子高生を拾う。"
type = "animation"

[[tag]]
name = "魔王城でおやすみ"
type = "animation"

[[tag]]
name = "安達としまむら"
type = "animation"

[[tag]]
name = "花咲くいろは"
type = "animation"

[[tag]]
name = "恋する小惑星"
type = "animation"

[[tag]]
name = "幼なじみが絶対に負けないラブコメ"
type = "animation"

[[tag]]
name = "魔女の旅々"
type = "animation"

[[tag]]
name = "回復術士のやり直し"
type = "animation"

[[tag]]
name = "誰ガ為のアルケミスト"
type = "animation"

[[tag]]
name = "少女終末旅行"
type = "animation"

[[tag]]
name = "アサルトリリィ BOUQUET"
type = "animation"

[[tag]]
name = "宝石の国"
type = "animation"

[[tag]]
name = "ぼくたちのリメイク"
type = "animation"

[[tag]]
name = "骸骨騎士様、只今異世界へお出掛け中"
type = "animation"

[[tag]]
name = "このヒーラー、めんどくさい"
type = "animation"

[[tag]]
name = "SLOW LOOP"
type = "animation"

[[tag]]
name = "社畜さんは幼女幽霊に癒されたい。"
type = "animation"

[[tag]]
name = "かぐや様は告らせたい～天才たちの恋愛頭脳戦～"
type = "animation"

[[tag]]
name = "白猫プロジェクト ZERO CHRONICLE"
type = "animation"

[[tag]]
name = "Fate/Apocrypha"
type = "animation"

[[tag]]
name = "グランクレスト戦記"
type = "animation"

[[tag]]
name = "ソードアート・オンライン アリシゼーション"
type = "animation"

[[tag]]
name = "ダーウィンズゲーム"
type = "animation"

[[tag]]
name = "ロード・エルメロイII世の事件簿 -魔眼蒐集列車 Grace note-"
type = "animation"

[[tag]]
name = "ロード・エルメロイII世の事件簿 -魔眼蒐集列車 Grace note- 特別編"
type = "animation"

[[tag]]
name = "すばらしきこのせかい The Animation"
type = "animation"

[[tag]]
name = "魔法科高校の劣等生 来訪者編"
type = "animation"

[[tag]]
name = "さくら荘のペットな彼女"
type = "animation"

[[tag]]
name = "HELLO WORLD"
type = "animation"

[[tag]]
name = "氷菓"
type = "animation"

[[tag]]
name = "たまこまーけっと"
type = "animation"

[[tag]]
name = "君の名は。"
type = "animation"

[[tag]]
name = "平家物語"
type = "animation"

[[tag]]
name = "TVアニメ「現実主義勇者の王国再建記」第二部"
type = "animation"

[[tag]]
name = "理系が恋に落ちたので証明してみた"
type = "animation"

[[tag]]
name = "アンジュ・ヴィエルジュ"
type = "animation"

[[tag]]
name = "フリージング ヴァイブレーション"
type = "animation"

[[tag]]
name = "私がモテないのはどう考えてもお前らが悪い!"
type = "animation"

[[tag]]
name = "黄昏乙女×アムネジア"
type = "animation"

[[tag]]
name = "アブソリュート・デュオ"
type = "animation"

[[tag]]
name = "魔弾の王と戦姫"
type = "animation"

[[tag]]
name = "Re:ゼロから始める異世界生活"
type = "animation"

[[tag]]
name = "ブブキ・ブランキ"
type = "animation"

[[tag]]
name = "LOST SONG"
type = "animation"

[[tag]]
name = "恋とプロデューサー～EVOL×LOVE"
type = "animation"

[[tag]]
name = "ロクでなし魔術講師と禁忌教典"
type = "animation"

[[tag]]
name = "蜘蛛ですが、なにか?"
type = "animation"

[[tag]]
name = "ソラとウミのアイダ"
type = "animation"

[[tag]]
name = "ひぐらしのなく頃に 卒"
type = "animation"

[[tag]]
name = "デカダンス"
type = "animation"

[[tag]]
name = "ディープインサニティ ザ・ロストチャイルド"
type = "animation"

[[tag]]
name = "映画「サマーゴースト」"
type = "animation"

[[tag]]
name = "キャロル＆チューズデイ"
type = "animation"

[[tag]]
name = "TVアニメ「SPY×FAMILY」"
type = "animation"

[[tag]]
name = "TVアニメ「阿波連さんははかれない」"
type = "animation"

[[tag]]
name = "TVアニメ「ギルティクラウン」"
type = "animation"

[[tag]]
name = "アニメ「ヒーラー・ガール」"
type = "animation"

[[tag]]
name = "TVアニメ「踏切時間」"
type = "animation"

[[tag]]
name = "TVアニメ「恋は世界征服のあとで」"
type = "animation"

[[tag]]
name = "モンスター娘のお医者さん"
type = "animation"

[[tag]]
name = "TVアニメ「このはな綺譚」"
type = "animation"

[[tag]]
name = "TVアニメ「リコリス・リコイル」"
type = "animation"

[[tag]]
name = "アニメ「グリザイアの果実」"
type = "animation"

[[tag]]
name = "グリザイアの楽園「カプリスの繭」編"
type = "animation"

[[tag]]
name = "グリザイアの楽園「ブランエールの種」編"
type = "animation"

[[tag]]
name = "東京レイヴンズ"
type = "animation"

[[tag]]
name = "ネトゲの嫁は女の子じゃないと思った？"
type = "animation"

[[tag]]
name = "アトム ザ・ビギニング"
type = "animation"

[[tag]]
name = "同居人はひざ、時々、頭のうえ。"
type = "animation"

[[tag]]
name = "グリザイア:ファントムトリガー THE ANIMATION"
type = "animation"

[[tag]]
name = "文豪とアルケミスト ～審判ノ歯車～"
type = "animation"

[[tag]]
name = "グリザイア：ファントムトリガー THE ANIMATION スターゲイザー"
type = "animation"

[[tag]]
name = "進化の実～知らないうちに勝ち組人生～"
type = "animation"

[[tag]]
name = "天才王子の赤字国家再生術"
type = "animation"

[[tag]]
name = "TVアニメ「それでも歩は寄せてくる」"
type = "animation"

[[tag]]
name = "劇場版 ハヤテのごとく！HEAVEN IS A PLACE ON EARTH"
type = "animation"

[[tag]]
name = "TVアニメ「ブラック・ブレット」"
type = "animation"

[[tag]]
name = "アニメ「フューチャーカード バディファイト ハンドレッド」"
type = "animation"

[[tag]]
name = "TVアニメ「終わりのセラフ」"
type = "animation"

[[tag]]
name = "TVシリーズ「亜人」"
type = "animation"

[[tag]]
name = "TVアニメ「クロックワーク・プラネット」"
type = "animation"

[[tag]]
name = "TVアニメ「されど罪人は竜と踊る」"
type = "animation"

[[tag]]
name = "TVアニメ「キリングバイツ」"
type = "animation"

[[tag]]
name = "TVアニメ「寄宿学校のジュリエット」"
type = "animation"

[[tag]]
name = "TVアニメ「キングスレイド 意志を継ぐものたち」"
type = "animation"

[[tag]]
name = "TVアニメ「失格紋の最強賢者」"
type = "animation"

[[tag]]
name = "TVアニメ「魔法使い黎明期」"
type = "animation"

[[tag]]
name = "TVアニメ「シャドーハウス」-2nd Season-"
type = "animation"

[[tag]]
name = "とある魔術の禁書目録 幻想収束"
type = "animation"

[[tag]]
name = "TVアニメ「恋姫†無双」"
type = "animation"

[[tag]]
name = "TVアニメ「シュヴァルツェスマーケン」"
type = "animation"

[[tag]]
name = "TVアニメ「ヲタクに恋は難しい」"
type = "animation"

[[tag]]
name = "アニメ『逆転裁判 ～その「真実」、異議あり！～Season2』"
type = "animation"

[[tag]]
name = "アニメ「ぼくたちは勉強ができない！」"
type = "animation"

[[tag]]
name = "TVアニメ「邪神ちゃんドロップキック’」"
type = "animation"

[[tag]]
name = "アニメ「彼女、お借りします」"
type = "animation"

[[tag]]
name = "アニメ「BORUTO-ボルト- NARUTO NEXT GENERATIONS」"
type = "animation"

[[tag]]
name = "アニメ「最近雇ったメイドが怪しい」"
type = "animation"

[[tag]]
name = "アニメ「シャインポスト」"
type = "animation"

[[tag]]
name = "アニメ「Engage Kiss」"
type = "animation"

[[tag]]
name = "アニメ「邪神ちゃんドロップキックX」"
type = "animation"

[[tag]]
name = "アニメ「継母の連れ子が元カノだった」"
type = "animation"

[[tag]]
name = "TVアニメ「Fate/Grand Order -絶対魔獣戦線バビロニア-」"
type = "animation"

################################################################################
# Game
#
[[tag]]
name = "ATRI -My Dear Moments-"
type = "game"

[[tag]]
name = "さくら、もゆ。-as the Night's, Reincarnation-"
type = "game"

[[tag]]
name = "ひまわり -Pebble in the Sky-"
type = "game"

[[tag]]
name = "ef - a fairy tale of the two."
type = "game"

[[tag]]
name = "明日方舟"
type = "game"

[[tag]]
name = "サクラノ詩-櫻の森の上を舞う-"
type = "game"

[[tag]]
name = "蒼の彼方のフォーリズム"
type = "game"

[[tag]]
name = "素晴らしき日々"
type = "game"

[[tag]]
name = "Outer Wilds"
type = "game"

[[tag]]
name = "9-nine-"
type = "game"

[[tag]]
name = "Persona 5"
type = "game"

[[tag]]
name = "Ever17"
type = "game"

[[tag]]
name = "Stellaris"
type = "game"

[[tag]]
name = "東京クロノス"
type = "game"

[[tag]]
name = "ソードアート・オンライン アンリーシュ・ブレイディング"
type = "game"

[[tag]]
name = "ALTDEUS: Beyond Chronos"
type = "game"

[[tag]]
name = "Re:ゼロから始める異世界生活 Lost in Memories"
type = "game"

[[tag]]
name = "永远的7日之都"
type = "game"

[[tag]]
name = "ドーナドーナ いっしょにわるいことをしよう"
type = "game"

[[tag]]
name = "ゲーム「レイギガント」ニル・フィニアス篇"
type = "game"

[[tag]]
name = "PSP(R)専用「とある科学の超電磁砲」"
type = "game"

[[tag]]
name = "超銀河船団"
type = "game"

[[tag]]
name = "ゲーム「少女珈琲枪」"
type = "game"

[[tag]]
name = "スマホゲーム「三国志幻想大陸」IF編"
type = "game"

[[tag]]
name = "D.C.III DASH ～ダ・カーポIII～ Ver.1.35"
type = "game"

[[tag]]
name = "カデンツァ フェルマータ アコルト：フォルテシモ"
type = "game"

[[tag]]
name = "ロストディメンション"
type = "game"

[[tag]]
name = "スマホゲーム「とある魔術の禁書目録」"
type = "game"

[[tag]]
name = "仙境传说RO：守护永恒的爱"
type = "game"

[[tag]]
name = "封印者M"
type = "game"

[[tag]]
name = "碧蓝航线"
type = "game"

[[tag]]
name = "PCゲーム「シュヴァルツェスマーケン 紅血の紋章」"
type = "game"

[[tag]]
name = "まいてつ"
type = "game"

################################################################################
# Project
#
[[tag]]
name = "東方Project"
type = "project"

[[tag]]
name = "Animelo Summer Live"
type = "project"

[[tag]]
name = "デート・ア・ライブ"
type = "project"
includes.animation = ["デート・ア・ライブIV"]

[[tag]]
name = "歴史秘話ヒストリア"
type = "project"

[[tag]]
name = "どっぷりアプリ"
type = "project"

[[tag]]
name = "この世の果てで恋を唄う少女YU-NO"
type = "project"
includes.animation = [
  "アニメ「この世の果てで恋を唄う少女YU-NO」現世編",
  "アニメ「この世の果てで恋を唄う少女YU-NO」異世界編"
]

[[tag]]
name = "ノーゲーム・ノーライフ"
type = "project"
includes.animation = [
  "アニメ「ノーゲーム・ノーライフ」",
  "映画「ノーゲーム・ノーライフ ゼロ」",
]

[[tag]]
name = "Nカフェ!!! 南條愛乃と語るモア"
type = "project"

[[tag]]
name = "とある科学の超電磁砲"
type = "project"
includes.animation = [
  "アニメ「とある科学の超電磁砲」",
  "アニメ「とある科学の超電磁砲 OVA」",
  "アニメ「とある科学の超電磁砲S」",
  "アニメ「とある科学の超電磁砲Ｔ」",
]

[[tag]]
name = "無職転生 ～異世界行ったら本気だす～"
type = "project"
includes.animation = [
  "アニメ「無職転生 ～異世界行ったら本気だす～」"
]

################################################################################
# Organization
#
[[tag]]
name = "Navel"
type = "organization"
includes.game = [
  "月に寄りそう乙女の作法",
  "乙女理論とその周辺",
  "月に寄りそう乙女の作法2",
  "乙女理論とその後の周辺",
  "月に寄りそう乙女の作法2.1 E×S×PAR!!",
  "月に寄りそう乙女の作法2.2 A×L+SA!!",
]

################################################################################
# Category
#
[[tag]]
name = "OP"
type = "category"

[[tag]]
name = "ED"
type = "category"

[[tag]]
name = "OST"
type = "category"
